-- If Supabase SQL Editor shows `relation "a" does not exist`, switch the results mode
-- from `Limit 100` to `No limit`, then rerun the script.

drop view if exists public.v_rotation_priority;
drop view if exists public.v_season_tier_transparency;
drop view if exists public.v_season_tier_scores;
-- FIX: remove legacy table that is not referenced anywhere in the current app or schema.
drop table if exists public.matchday_team_scores cascade;
drop table if exists public.season_players cascade;
drop table if exists public.matchday_player_stats cascade;
drop table if exists public.matchday_matches cascade;
drop table if exists public.matchday_assignments cascade;
drop table if exists public.matchdays cascade;
drop table if exists public.seasons cascade;
drop table if exists public.players cascade;

create table public.players (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  nickname text,
  nationality text not null,
  birth_date date,
  phone text,
  positions text[] not null default array['GK']::text[],
  skill_rating integer not null default 78,
  desired_tier text not null default 'core',
  status text not null default 'core',
  dominant_foot text not null default 'right',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint players_first_name_length check (char_length(trim(first_name)) between 2 and 40),
  constraint players_last_name_length check (char_length(trim(last_name)) between 2 and 40),
  constraint players_nickname_length check (
    nickname is null or char_length(trim(nickname)) between 1 and 50
  ),
  constraint players_nationality_length check (char_length(trim(nationality)) between 2 and 50),
  constraint players_birth_date_valid check (
    birth_date is null or (birth_date >= date '1900-01-01' and birth_date <= current_date)
  ),
  constraint players_skill_rating_range check (skill_rating between 40 and 99),
  constraint players_positions_allowed check (
    cardinality(positions) between 1 and 3
    and positions <@ array['GK', 'DEF', 'MID', 'ATT']::text[]
  ),
  constraint players_desired_tier_allowed check (
    desired_tier in ('core', 'flex', 'sub')
  ),
  constraint players_status_allowed check (
    status in ('core', 'flex', 'sub')
  ),
  constraint players_dominant_foot_allowed check (
    dominant_foot in ('right', 'left', 'both')
  ),
  constraint players_notes_length check (
    notes is null or char_length(notes) <= 240
  )
);

create unique index players_unique_name_idx
on public.players ((lower(trim(first_name)) || ' ' || lower(trim(last_name))));

create index players_desired_tier_idx on public.players (desired_tier);
create index players_status_idx on public.players (status);
create index players_created_at_idx on public.players (created_at desc);
create index players_positions_idx on public.players using gin (positions);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger players_set_updated_at
before update on public.players
for each row
execute procedure public.set_updated_at();

alter table public.players enable row level security;

create policy "Anyone can read players"
on public.players
for select
to anon
using (true);

create policy "Anyone can add players"
on public.players
for insert
to anon
with check (true);

create policy "Anyone can update players"
on public.players
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete players"
on public.players
for delete
to anon
using (true);

create table public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  total_matchdays integer not null,
  core_spots integer not null default 0,
  rotation_spots integer not null default 0,
  model_start_matchday integer not null default 1,
  attendance_points integer not null default 2,
  win_points integer not null default 2,
  draw_points integer not null default 1,
  loss_points integer not null default 0,
  goal_keep_points integer not null default 1,
  team_goal_points integer not null default 1,
  team_display_config jsonb not null default '{
    "magenta": { "label": "Magenta", "color": "#f472b6" },
    "blue": { "label": "Blue", "color": "#60a5fa" },
    "green": { "label": "Green", "color": "#4ade80" },
    "orange": { "label": "Orange", "color": "#fb923c" }
  }'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint seasons_name_length check (char_length(trim(name)) between 3 and 80),
  constraint seasons_total_matchdays_range check (total_matchdays between 1 and 60),
  constraint seasons_core_spots_range check (core_spots between 0 and 60),
  constraint seasons_rotation_spots_range check (rotation_spots between 0 and 60),
  constraint seasons_model_start_matchday_range check (
    model_start_matchday between 1 and total_matchdays
  ),
  constraint seasons_attendance_points_range check (attendance_points between 0 and 20),
  constraint seasons_win_points_range check (win_points between 0 and 20),
  constraint seasons_draw_points_range check (draw_points between 0 and 20),
  constraint seasons_loss_points_range check (loss_points between 0 and 20),
  constraint seasons_goal_keep_points_range check (goal_keep_points between 0 and 20),
  constraint seasons_team_goal_points_range check (team_goal_points between 0 and 20),
  constraint seasons_spot_targets_present check ((core_spots + rotation_spots) >= 1)
);

create unique index seasons_name_unique_idx
on public.seasons ((lower(trim(name))));

create index seasons_created_at_idx on public.seasons (created_at desc);

create trigger seasons_set_updated_at
before update on public.seasons
for each row
execute procedure public.set_updated_at();

alter table public.seasons enable row level security;

create policy "Anyone can read seasons"
on public.seasons
for select
to anon
using (true);

create policy "Anyone can add seasons"
on public.seasons
for insert
to anon
with check (true);

create policy "Anyone can update seasons"
on public.seasons
for update
to anon
using (true)
with check (true);

create table public.season_players (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  tier_status text not null default 'flex',
  tier_reason text,
  movement_note text,
  is_eligible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint season_players_tier_status_allowed check (
    tier_status in ('core', 'flex', 'sub')
  ),
  constraint season_players_reason_length check (
    tier_reason is null or char_length(trim(tier_reason)) <= 240
  ),
  constraint season_players_note_length check (
    movement_note is null or char_length(trim(movement_note)) <= 240
  )
);

create unique index season_players_unique_idx
on public.season_players (season_id, player_id);

create index season_players_tier_idx
on public.season_players (season_id, tier_status);

create trigger season_players_set_updated_at
before update on public.season_players
for each row
execute procedure public.set_updated_at();

create or replace function public.enforce_matchday_player_on_season_roster()
returns trigger
language plpgsql
as $$
declare
  roster_exists boolean;
begin
  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = new.matchday_id
      and sp.player_id = new.player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster for matchday %s before saving %s.',
        new.player_id,
        new.matchday_id,
        tg_table_name
      ),
      detail = format('matchday_id=%s, player_id=%s', new.matchday_id, new.player_id),
      hint = 'Add the player to season_players for the matchday season, then retry.';
  end if;

  return new;
end;
$$;

create or replace function public.prevent_orphaned_matchday_activity_from_season_roster_changes()
returns trigger
language plpgsql
as $$
declare
  affected_matchday_count integer;
begin
  select count(distinct md.id)
  into affected_matchday_count
  from public.matchdays md
  where md.season_id = old.season_id
    and (
      exists (
        select 1
        from public.matchday_assignments ma
        where ma.matchday_id = md.id
          and ma.player_id = old.player_id
      )
      or exists (
        select 1
        from public.matchday_player_stats mps
        where mps.matchday_id = md.id
          and mps.player_id = old.player_id
      )
    );

  if affected_matchday_count > 0 then
    raise exception using
      errcode = '23514',
      message = format(
        'Cannot remove player %s from season %s while matchday activity still exists.',
        old.player_id,
        old.season_id
      ),
      detail = format(
        'season_id=%s, player_id=%s, affected_matchdays=%s',
        old.season_id,
        old.player_id,
        affected_matchday_count
      ),
      hint = 'Delete or reassign the player''s matchday assignments and stats for that season before removing the season roster row.';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create or replace function public.enforce_matchday_season_roster_integrity()
returns trigger
language plpgsql
as $$
declare
  invalid_player_count integer;
begin
  select count(*)
  into invalid_player_count
  from (
    select distinct participant.player_id
    from (
      select ma.player_id
      from public.matchday_assignments ma
      where ma.matchday_id = new.id

      union

      select mps.player_id
      from public.matchday_player_stats mps
      where mps.matchday_id = new.id
    ) participant
    left join public.season_players sp
      on sp.season_id = new.season_id
     and sp.player_id = participant.player_id
    where sp.id is null
  ) invalid_players;

  if invalid_player_count > 0 then
    raise exception using
      errcode = '23514',
      message = format(
        'Cannot move matchday %s to season %s because some existing players are not on that season roster.',
        new.id,
        new.season_id
      ),
      detail = format('matchday_id=%s, season_id=%s, invalid_players=%s', new.id, new.season_id, invalid_player_count),
      hint = 'Add the players to the destination season roster or clear the matchday assignments/stats before changing the matchday season.';
  end if;

  return new;
end;
$$;

create constraint trigger season_players_preserve_matchday_integrity
after delete or update of season_id, player_id on public.season_players
deferrable initially deferred
for each row
execute procedure public.prevent_orphaned_matchday_activity_from_season_roster_changes();

alter table public.season_players enable row level security;

create policy "Anyone can read season players"
on public.season_players
for select
to anon
using (true);

create policy "Anyone can add season players"
on public.season_players
for insert
to anon
with check (true);

create policy "Anyone can update season players"
on public.season_players
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete season players"
on public.season_players
for delete
to anon
using (true);

create table public.matchdays (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  matchday_number integer not null,
  kickoff_at timestamptz,
  goals_count_as_points boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchdays_number_range check (matchday_number between 1 and 60)
);

create unique index matchdays_unique_number_idx
on public.matchdays (season_id, matchday_number);

create index matchdays_season_idx on public.matchdays (season_id, matchday_number);
create index matchdays_kickoff_idx on public.matchdays (kickoff_at);

create trigger matchdays_set_updated_at
before update on public.matchdays
for each row
execute procedure public.set_updated_at();

create constraint trigger matchdays_validate_season_roster_integrity
after update of season_id on public.matchdays
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_season_roster_integrity();

alter table public.matchdays enable row level security;

create policy "Anyone can read matchdays"
on public.matchdays
for select
to anon
using (true);

create policy "Anyone can add matchdays"
on public.matchdays
for insert
to anon
with check (true);

create policy "Anyone can update matchdays"
on public.matchdays
for update
to anon
using (true)
with check (true);

create table public.matchday_matches (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  round_number integer not null,
  match_order integer not null,
  home_team_code text,
  away_team_code text,
  home_score integer,
  away_score integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_matches_round_allowed check (round_number in (1, 2)),
  constraint matchday_matches_order_allowed check (match_order in (1, 2)),
  constraint matchday_matches_home_team_allowed check (
    home_team_code is null or home_team_code in ('magenta', 'blue', 'green', 'orange')
  ),
  constraint matchday_matches_away_team_allowed check (
    away_team_code is null or away_team_code in ('magenta', 'blue', 'green', 'orange')
  ),
  constraint matchday_matches_score_allowed check (
    (home_score is null or home_score >= 0)
    and (away_score is null or away_score >= 0)
  ),
  constraint matchday_matches_distinct_teams check (
    home_team_code is null or away_team_code is null or home_team_code <> away_team_code
  )
);

create unique index matchday_matches_unique_slot_idx
on public.matchday_matches (matchday_id, round_number, match_order);

create trigger matchday_matches_set_updated_at
before update on public.matchday_matches
for each row
execute procedure public.set_updated_at();

alter table public.matchday_matches enable row level security;

create policy "Anyone can read matchday matches"
on public.matchday_matches
for select
to anon
using (true);

create policy "Anyone can add matchday matches"
on public.matchday_matches
for insert
to anon
with check (true);

create policy "Anyone can update matchday matches"
on public.matchday_matches
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete matchday matches"
on public.matchday_matches
for delete
to anon
using (true);

create table public.matchday_player_stats (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  attended boolean not null default false,
  attendance_status text not null default 'out',
  goals integer not null default 0,
  goal_keeps integer not null default 0,
  clean_sheet boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_player_stats_nonnegative check (
    goals >= 0 and goal_keeps >= 0
  ),
  constraint matchday_player_stats_attendance_status_allowed check (
    attendance_status in ('out', 'in', 'attended', 'available', 'late_cancel', 'no_show')
  )
);

create unique index matchday_player_stats_unique_idx
on public.matchday_player_stats (matchday_id, player_id);

create index matchday_player_stats_matchday_idx
on public.matchday_player_stats (matchday_id, attended);

create index matchday_player_stats_status_idx
on public.matchday_player_stats (matchday_id, attendance_status);

create trigger matchday_player_stats_set_updated_at
before update on public.matchday_player_stats
for each row
execute procedure public.set_updated_at();

create constraint trigger matchday_player_stats_require_season_roster
after insert or update of matchday_id, player_id on public.matchday_player_stats
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_player_on_season_roster();

alter table public.matchday_player_stats enable row level security;

create policy "Anyone can read matchday player stats"
on public.matchday_player_stats
for select
to anon
using (true);

create policy "Anyone can add matchday player stats"
on public.matchday_player_stats
for insert
to anon
with check (true);

create policy "Anyone can update matchday player stats"
on public.matchday_player_stats
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete matchday player stats"
on public.matchday_player_stats
for delete
to anon
using (true);

create table public.matchday_assignments (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  team_code text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_assignments_team_code_allowed check (
    team_code in ('magenta', 'blue', 'green', 'orange')
  )
);

create unique index matchday_assignments_unique_player_idx
on public.matchday_assignments (matchday_id, player_id);

create index matchday_assignments_matchday_idx
on public.matchday_assignments (matchday_id, team_code);

create trigger matchday_assignments_set_updated_at
before update on public.matchday_assignments
for each row
execute procedure public.set_updated_at();

create constraint trigger matchday_assignments_require_season_roster
after insert or update of matchday_id, player_id on public.matchday_assignments
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_player_on_season_roster();

alter table public.matchday_assignments enable row level security;

create policy "Anyone can read matchday assignments"
on public.matchday_assignments
for select
to anon
using (true);

create policy "Anyone can add matchday assignments"
on public.matchday_assignments
for insert
to anon
with check (true);

create policy "Anyone can update matchday assignments"
on public.matchday_assignments
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete matchday assignments"
on public.matchday_assignments
for delete
to anon
using (true);

create or replace view public.v_season_tier_scores as
with completed_matchdays as (
  select
    md.id,
    md.season_id,
    md.matchday_number
  from public.matchdays md
  join public.seasons s
    on s.id = md.season_id
  left join public.matchday_matches mm
    on mm.matchday_id = md.id
  group by md.id, md.season_id, md.matchday_number, s.model_start_matchday
  having md.matchday_number >= coalesce(s.model_start_matchday, 1)
     and count(*) filter (
       where mm.round_number in (1, 2)
         and mm.match_order in (1, 2)
     ) = 4
     and count(*) filter (
       where mm.round_number in (1, 2)
         and mm.match_order in (1, 2)
         and mm.home_score is not null
         and mm.away_score is not null
     ) = 4
),
stats_with_status as (
  select
    cmd.id as matchday_id,
    cmd.season_id,
    cmd.matchday_number,
    mps.player_id,
    case
      when coalesce(mps.attendance_status, 'out') = 'out' and mps.attended then 'in'
      when coalesce(mps.attendance_status, 'out') = 'attended' then 'in'
      else coalesce(mps.attendance_status, 'out')
    end as effective_attendance_status
  from completed_matchdays cmd
  join public.matchday_player_stats mps
    on mps.matchday_id = cmd.id
),
season_attendance as (
  select
    sws.season_id,
    sws.player_id,
    count(*) filter (where sws.effective_attendance_status = 'in') as games_attended,
    count(*) filter (where sws.effective_attendance_status = 'available') as games_available,
    count(*) filter (where sws.effective_attendance_status = 'late_cancel') as late_cancels,
    count(*) filter (where sws.effective_attendance_status = 'no_show') as no_shows
  from stats_with_status sws
  group by sws.season_id, sws.player_id
),
recent_matchdays as (
  select
    cmd.id,
    cmd.season_id,
    row_number() over (
      partition by cmd.season_id
      order by cmd.matchday_number desc
    ) as recent_rank
  from completed_matchdays cmd
),
recent_attendance as (
  select
    rm.season_id,
    sws.player_id,
    count(*) filter (where sws.effective_attendance_status = 'in') as recent_games_attended,
    count(*) filter (where sws.effective_attendance_status = 'available') as recent_games_available,
    count(*) filter (where sws.effective_attendance_status = 'late_cancel') as recent_late_cancels,
    count(*) filter (where sws.effective_attendance_status = 'no_show') as recent_no_shows
  from recent_matchdays rm
  join stats_with_status sws
    on sws.matchday_id = rm.id
  where rm.recent_rank <= 8
  group by rm.season_id, sws.player_id
),
base as (
  select
    sp.id as season_player_id,
    sp.season_id,
    sp.player_id,
    sp.tier_status,
    coalesce(p.desired_tier, p.status) as default_status,
    coalesce(sa.games_attended, 0) as games_attended,
    coalesce(sa.games_available, 0) as games_available,
    coalesce(sa.late_cancels, 0) as late_cancels,
    coalesce(sa.no_shows, 0) as no_shows,
    ((coalesce(sa.games_attended, 0) * 2) + coalesce(sa.games_available, 0) - coalesce(sa.late_cancels, 0) - (coalesce(sa.no_shows, 0) * 2)) as attendance_score,
    coalesce(ra.recent_games_attended, 0) as recent_games_attended,
    coalesce(ra.recent_games_available, 0) as recent_games_available,
    coalesce(ra.recent_late_cancels, 0) as recent_late_cancels,
    coalesce(ra.recent_no_shows, 0) as recent_no_shows,
    ((coalesce(ra.recent_games_attended, 0) * 2) + coalesce(ra.recent_games_available, 0) - coalesce(ra.recent_late_cancels, 0) - (coalesce(ra.recent_no_shows, 0) * 2)) as recent_attendance_score,
    sp.tier_reason,
    sp.movement_note,
    sp.is_eligible,
    sp.created_at,
    sp.updated_at
  from public.season_players sp
  join public.players p
    on p.id = sp.player_id
  left join season_attendance sa
    on sa.season_id = sp.season_id
   and sa.player_id = sp.player_id
  left join recent_attendance ra
    on ra.season_id = sp.season_id
   and ra.player_id = sp.player_id
),
scored as (
  select
    base.*,
    case
      when not base.is_eligible then 'sub'
      -- FIX: Suggested tier now leans on the last 8 tracked matchdays, with season totals
      -- acting as guardrails so one short hot streak does not overwhelm the full season.
      when base.recent_attendance_score >= 7
        and base.recent_games_attended >= 3
        and base.recent_no_shows = 0
        and base.attendance_score >= 8
        and base.games_attended >= 4
        and base.no_shows <= 1 then 'core'
      when base.recent_attendance_score >= 2
        and base.recent_games_attended >= 1
        and base.no_shows <= 2 then 'flex'
      else 'sub'
    end as recommended_tier_status,
    case
      when not base.is_eligible then 'down'
      when base.recent_attendance_score >= 7
        and base.recent_games_attended >= 3
        and base.recent_no_shows = 0
        and base.attendance_score >= 8
        and base.games_attended >= 4
        and base.no_shows <= 1 then
        case
          when coalesce(base.tier_status, 'sub') = 'core' then 'steady'
          else 'up'
        end
      when base.recent_attendance_score >= 2
        and base.recent_games_attended >= 1
        and base.no_shows <= 2 then
        case
          when coalesce(base.tier_status, 'sub') = 'core' then 'down'
          when coalesce(base.tier_status, 'sub') = 'flex' then 'steady'
          else 'up'
        end
      else
        case
          when coalesce(base.tier_status, 'sub') = 'sub' then 'steady'
          else 'down'
        end
    end as trend
  from base
)
select
  scored.*,
  case
    when not scored.is_eligible then 'Ineligible. Restore eligibility before tier movement.'
    when scored.recommended_tier_status = 'core' and coalesce(scored.tier_status, 'sub') <> 'core' then 'Promotion case. The last 8 matchdays look core-level, and the season totals still clear the guardrails.'
    when scored.recommended_tier_status = 'flex' and coalesce(scored.tier_status, 'sub') = 'sub' then 'Trending up. The recent 8-match run now supports rotation minutes.'
    when scored.recommended_tier_status = 'sub' and coalesce(scored.tier_status, 'sub') <> 'sub' then 'Recent form has slipped below the current tier range, even with season totals included.'
    else coalesce(scored.movement_note, 'Stable in current tier range.')
  end as transparency_note,
  case
    when not scored.is_eligible then 'Restore eligibility'
    when scored.recommended_tier_status = 'core' then 'Keep the recent run strong and avoid no-shows'
    when scored.recommended_tier_status = 'flex' and scored.recent_games_attended < 3 then 'Turn the recent run into a longer stretch of availability'
    when scored.recommended_tier_status = 'flex' then 'Keep stacking recent attendance and push toward core'
    else 'Build a stronger recent 8-match run and reduce late changes'
  end as next_step
from scored;

create or replace view public.v_season_tier_transparency as
select
  v.season_id,
  s.name as season_name,
  s.model_start_matchday,
  v.player_id,
  p.first_name,
  p.last_name,
  p.nickname,
  p.nationality,
  v.default_status,
  v.tier_status,
  v.recommended_tier_status,
  v.games_attended,
  v.games_available,
  v.late_cancels,
  v.no_shows,
  v.attendance_score,
  v.recent_games_attended,
  v.recent_games_available,
  v.recent_late_cancels,
  v.recent_no_shows,
  v.recent_attendance_score,
  v.is_eligible,
  v.tier_reason,
  v.movement_note,
  v.transparency_note,
  v.next_step,
  v.trend,
  v.created_at,
  v.updated_at
from public.v_season_tier_scores v
join public.players p
  on p.id = v.player_id
join public.seasons s
  on s.id = v.season_id;

create or replace view public.v_rotation_priority as
select
  vt.season_id,
  vt.season_name,
  vt.model_start_matchday,
  vt.player_id,
  vt.first_name,
  vt.last_name,
  vt.nickname,
  vt.nationality,
  vt.default_status,
  vt.tier_status,
  vt.recommended_tier_status,
  vt.games_attended,
  vt.games_available,
  vt.late_cancels,
  vt.no_shows,
  vt.attendance_score,
  vt.recent_games_attended,
  vt.recent_games_available,
  vt.recent_late_cancels,
  vt.recent_no_shows,
  vt.recent_attendance_score,
  vt.is_eligible,
  vt.tier_reason,
  vt.movement_note,
  vt.transparency_note,
  vt.next_step,
  vt.trend,
  row_number() over (
    partition by vt.season_id
    order by vt.games_attended asc, vt.attendance_score desc, vt.no_shows asc, lower(trim(vt.last_name)), lower(trim(vt.first_name))
  ) as rotation_priority_rank
from public.v_season_tier_transparency vt
where vt.tier_status = 'flex'
  and vt.is_eligible = true;

-- Final verification query so Supabase SQL Editor has a safe SELECT result to return.
select
  to_regclass('public.players') is not null as players_ready,
  to_regclass('public.seasons') is not null as seasons_ready,
  to_regclass('public.season_players') is not null as season_players_ready,
  to_regclass('public.matchdays') is not null as matchdays_ready,
  to_regclass('public.matchday_matches') is not null as matchday_matches_ready,
  to_regclass('public.matchday_player_stats') is not null as matchday_player_stats_ready,
  to_regclass('public.matchday_assignments') is not null as matchday_assignments_ready,
  to_regclass('public.v_season_tier_scores') is not null as v_season_tier_scores_ready,
  to_regclass('public.v_season_tier_transparency') is not null as v_season_tier_transparency_ready,
  to_regclass('public.v_rotation_priority') is not null as v_rotation_priority_ready;
