-- STEP 1 OF 3: Schema — tables, functions, triggers, indexes, RLS policies, views.
-- Run this FIRST in the Supabase SQL Editor.

begin;

drop view if exists public.v_rotation_priority;
drop view if exists public.v_season_tier_transparency;
drop view if exists public.v_season_tier_scores;
-- FIX: remove legacy table that is not referenced anywhere in the current app or schema.
drop table if exists public.matchday_team_scores cascade;
drop table if exists public.season_roster_requests cascade;
drop table if exists public.season_players cascade;
drop table if exists public.matchday_player_stats cascade;
drop table if exists public.matchday_matches cascade;
drop table if exists public.matchday_team_captains cascade;
drop table if exists public.matchday_assignments cascade;
drop table if exists public.matchdays cascade;
drop table if exists public.admin_allowed_emails cascade;
drop table if exists public.player_accounts cascade;
drop table if exists public.seasons cascade;
drop table if exists public.players cascade;

create table public.players (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  nickname text,
  nationality text not null,
  birth_date date,
  phone text,
  positions text[] not null default array['GK']::text[],
  skill_rating integer not null default 78,
  desired_tier text not null default 'core',
  status text not null default 'core',
  dominant_foot text not null default 'right',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint players_first_name_length check (char_length(trim(first_name)) between 2 and 40),
  constraint players_last_name_length check (char_length(trim(last_name)) between 1 and 40),
  constraint players_nickname_length check (
    nickname is null or char_length(trim(nickname)) between 1 and 50
  ),
  constraint players_nationality_length check (char_length(trim(nationality)) between 2 and 50),
  constraint players_birth_date_valid check (
    birth_date is null or (birth_date >= date '1900-01-01' and birth_date <= current_date)
  ),
  constraint players_skill_rating_range check (skill_rating between 40 and 99),
  constraint players_positions_allowed check (
    cardinality(positions) between 1 and 3
    and positions <@ array['GK', 'DEF', 'MID', 'ATT']::text[]
  ),
  constraint players_desired_tier_allowed check (
    desired_tier in ('core', 'flex', 'sub')
  ),
  constraint players_status_allowed check (
    status in ('core', 'flex', 'sub')
  ),
  constraint players_dominant_foot_allowed check (
    dominant_foot in ('right', 'left', 'both')
  ),
  constraint players_notes_length check (
    notes is null or char_length(notes) <= 240
  )
);

create unique index players_unique_name_idx
on public.players ((lower(trim(first_name)) || ' ' || lower(trim(last_name))));

create index players_desired_tier_idx on public.players (desired_tier);
create index players_status_idx on public.players (status);
create index players_created_at_idx on public.players (created_at desc);
create index players_positions_idx on public.players using gin (positions);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger players_set_updated_at
before update on public.players
for each row
execute procedure public.set_updated_at();

alter table public.players enable row level security;

create policy "Anyone can read players"
on public.players
for select
to anon
using (true);

create policy "Anyone can add players"
on public.players
for insert
to anon
with check (true);

create policy "Anyone can update players"
on public.players
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete players"
on public.players
for delete
to anon
using (true);

create table public.seasons (
  id bigint generated by default as identity primary key,
  name text not null,
  total_matchdays integer not null,
  core_spots integer not null default 0,
  rotation_spots integer not null default 0,
  model_start_matchday integer not null default 1,
  season_start_date date,
  default_matchday_weekday integer,
  default_kickoff_time time without time zone,
  venue_name text not null default 'Alden E. Oliver',
  attendance_points integer not null default 2,
  win_points integer not null default 2,
  draw_points integer not null default 1,
  loss_points integer not null default 0,
  goal_keep_points integer not null default 1,
  team_goal_points integer not null default 1,
  team_display_config jsonb not null default '{
    "magenta": { "label": "Magenta", "color": "#f472b6" },
    "blue": { "label": "Blue", "color": "#60a5fa" },
    "green": { "label": "Green", "color": "#4ade80" },
    "orange": { "label": "Orange", "color": "#fb923c" }
  }'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint seasons_name_length check (char_length(trim(name)) between 3 and 80),
  constraint seasons_total_matchdays_range check (total_matchdays between 1 and 60),
  constraint seasons_core_spots_range check (core_spots between 0 and 60),
  constraint seasons_rotation_spots_range check (rotation_spots between 0 and 60),
  constraint seasons_model_start_matchday_range check (
    model_start_matchday between 1 and total_matchdays
  ),
  constraint seasons_default_matchday_weekday_range check (
    default_matchday_weekday is null or default_matchday_weekday between 0 and 6
  ),
  constraint seasons_venue_name_length check (
    char_length(trim(venue_name)) between 3 and 80
  ),
  constraint seasons_attendance_points_range check (attendance_points between 0 and 20),
  constraint seasons_win_points_range check (win_points between 0 and 20),
  constraint seasons_draw_points_range check (draw_points between 0 and 20),
  constraint seasons_loss_points_range check (loss_points between 0 and 20),
  constraint seasons_goal_keep_points_range check (goal_keep_points between 0 and 20),
  constraint seasons_team_goal_points_range check (team_goal_points between 0 and 20),
  constraint seasons_spot_targets_present check ((core_spots + rotation_spots) >= 1)
);

create unique index seasons_name_unique_idx
on public.seasons ((lower(trim(name))));

create index seasons_created_at_idx on public.seasons (created_at desc);

create trigger seasons_set_updated_at
before update on public.seasons
for each row
execute procedure public.set_updated_at();

alter table public.seasons enable row level security;

create policy "Anyone can read seasons"
on public.seasons
for select
to anon
using (true);

create policy "Anyone can add seasons"
on public.seasons
for insert
to anon
with check (true);

create policy "Anyone can update seasons"
on public.seasons
for update
to anon
using (true)
with check (true);

create table public.season_players (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  tier_status text not null default 'flex',
  registration_tier text not null default 'flex',
  payment_status text not null default 'unknown',
  tier_reason text,
  movement_note text,
  is_eligible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint season_players_tier_status_allowed check (
    tier_status in ('core', 'flex', 'sub')
  ),
  constraint season_players_registration_tier_allowed check (
    registration_tier in ('core', 'flex', 'sub')
  ),
  constraint season_players_payment_status_allowed check (
    payment_status in ('unknown', 'pending', 'paid', 'comped')
  ),
  constraint season_players_reason_length check (
    tier_reason is null or char_length(trim(tier_reason)) <= 240
  ),
  constraint season_players_note_length check (
    movement_note is null or char_length(trim(movement_note)) <= 240
  )
);

create unique index season_players_unique_idx
on public.season_players (season_id, player_id);

create index season_players_tier_idx
on public.season_players (season_id, tier_status);

create trigger season_players_set_updated_at
before update on public.season_players
for each row
execute procedure public.set_updated_at();

create or replace function public.enforce_matchday_player_on_season_roster()
returns trigger
language plpgsql
as $$
declare
  roster_exists boolean;
begin
  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = new.matchday_id
      and sp.player_id = new.player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster for matchday %s before saving %s.',
        new.player_id,
        new.matchday_id,
        tg_table_name
      ),
      detail = format('matchday_id=%s, player_id=%s', new.matchday_id, new.player_id),
      hint = 'Add the player to season_players for the matchday season, then retry.';
  end if;

  return new;
end;
$$;

create or replace function public.prevent_orphaned_matchday_activity_from_season_roster_changes()
returns trigger
language plpgsql
as $$
declare
  affected_matchday_count integer;
begin
  select count(distinct md.id)
  into affected_matchday_count
  from public.matchdays md
  where md.season_id = old.season_id
    and (
      exists (
        select 1
        from public.matchday_assignments ma
        where ma.matchday_id = md.id
          and ma.player_id = old.player_id
      )
      or exists (
        select 1
        from public.matchday_player_stats mps
        where mps.matchday_id = md.id
          and mps.player_id = old.player_id
      )
    );

  if affected_matchday_count > 0 then
    raise exception using
      errcode = '23514',
      message = format(
        'Cannot remove player %s from season %s while matchday activity still exists.',
        old.player_id,
        old.season_id
      ),
      detail = format(
        'season_id=%s, player_id=%s, affected_matchdays=%s',
        old.season_id,
        old.player_id,
        affected_matchday_count
      ),
      hint = 'Delete or reassign the player''s matchday assignments and stats for that season before removing the season roster row.';
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

create or replace function public.enforce_matchday_season_roster_integrity()
returns trigger
language plpgsql
as $$
declare
  invalid_player_count integer;
begin
  select count(*)
  into invalid_player_count
  from (
    select distinct participant.player_id
    from (
      select ma.player_id
      from public.matchday_assignments ma
      where ma.matchday_id = new.id

      union

      select mps.player_id
      from public.matchday_player_stats mps
      where mps.matchday_id = new.id
    ) participant
    left join public.season_players sp
      on sp.season_id = new.season_id
     and sp.player_id = participant.player_id
    where sp.id is null
  ) invalid_players;

  if invalid_player_count > 0 then
    raise exception using
      errcode = '23514',
      message = format(
        'Cannot move matchday %s to season %s because some existing players are not on that season roster.',
        new.id,
        new.season_id
      ),
      detail = format('matchday_id=%s, season_id=%s, invalid_players=%s', new.id, new.season_id, invalid_player_count),
      hint = 'Add the players to the destination season roster or clear the matchday assignments/stats before changing the matchday season.';
  end if;

  return new;
end;
$$;

create constraint trigger season_players_preserve_matchday_integrity
after delete or update of season_id, player_id on public.season_players
deferrable initially deferred
for each row
execute procedure public.prevent_orphaned_matchday_activity_from_season_roster_changes();

alter table public.season_players enable row level security;

create policy "Anyone can read season players"
on public.season_players
for select
to anon
using (true);

create policy "Anyone can add season players"
on public.season_players
for insert
to anon
with check (true);

create policy "Anyone can update season players"
on public.season_players
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete season players"
on public.season_players
for delete
to anon
using (true);

create table public.season_roster_requests (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  player_id bigint references public.players(id) on delete set null,
  request_type text not null default 'directory',
  requester_name text not null,
  requester_contact text,
  first_name text not null,
  last_name text not null,
  nickname text,
  nationality text not null,
  preferred_positions text[] not null default array['MID']::text[],
  requested_tier text not null default 'flex',
  note text,
  status text not null default 'pending',
  review_note text,
  approved_player_id bigint references public.players(id) on delete set null,
  approved_season_player_id bigint references public.season_players(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint season_roster_requests_type_allowed check (
    request_type in ('directory', 'new_directory')
  ),
  constraint season_roster_requests_requester_name_length check (
    char_length(trim(requester_name)) between 2 and 80
  ),
  constraint season_roster_requests_contact_length check (
    requester_contact is null or char_length(trim(requester_contact)) between 3 and 120
  ),
  constraint season_roster_requests_first_name_length check (
    char_length(trim(first_name)) between 2 and 40
  ),
  constraint season_roster_requests_last_name_length check (
    char_length(trim(last_name)) between 1 and 40
  ),
  constraint season_roster_requests_nickname_length check (
    nickname is null or char_length(trim(nickname)) between 1 and 50
  ),
  constraint season_roster_requests_nationality_length check (
    char_length(trim(nationality)) between 2 and 50
  ),
  constraint season_roster_requests_positions_allowed check (
    cardinality(preferred_positions) between 1 and 3
    and preferred_positions <@ array['GK', 'DEF', 'MID', 'ATT']::text[]
  ),
  constraint season_roster_requests_requested_tier_allowed check (
    requested_tier in ('core', 'flex', 'sub')
  ),
  constraint season_roster_requests_status_allowed check (
    status in ('pending', 'approved', 'denied')
  ),
  constraint season_roster_requests_note_length check (
    note is null or char_length(trim(note)) <= 240
  ),
  constraint season_roster_requests_review_note_length check (
    review_note is null or char_length(trim(review_note)) <= 240
  )
);

create index season_roster_requests_season_status_idx
on public.season_roster_requests (season_id, status, created_at desc);

create index season_roster_requests_player_status_idx
on public.season_roster_requests (player_id, status, created_at desc);

create unique index season_roster_requests_pending_player_idx
on public.season_roster_requests (season_id, player_id)
where status = 'pending' and player_id is not null;

create trigger season_roster_requests_set_updated_at
before update on public.season_roster_requests
for each row
execute procedure public.set_updated_at();

alter table public.season_roster_requests enable row level security;

create policy "Anyone can read season roster requests"
on public.season_roster_requests
for select
to anon
using (true);

create policy "Anyone can add season roster requests"
on public.season_roster_requests
for insert
to anon
with check (true);

create policy "Anyone can update season roster requests"
on public.season_roster_requests
for update
to anon
using (true)
with check (true);

create table public.matchdays (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  matchday_number integer not null,
  kickoff_at timestamptz,
  player_stats_open_at timestamptz,
  player_stats_close_at timestamptz,
  player_ratings_close_at timestamptz,
  admin_review_locked_at timestamptz,
  goals_count_as_points boolean not null default false,
  final_captain_order_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchdays_number_range check (matchday_number between 1 and 60)
);

create unique index matchdays_unique_number_idx
on public.matchdays (season_id, matchday_number);

create index matchdays_season_idx on public.matchdays (season_id, matchday_number);
create index matchdays_kickoff_idx on public.matchdays (kickoff_at);

create or replace function public.set_matchday_submission_windows()
returns trigger
language plpgsql
as $$
begin
  if new.kickoff_at is null then
    return new;
  end if;

  if new.player_stats_open_at is null then
    new.player_stats_open_at = new.kickoff_at + interval '1 hour';
  end if;

  if new.player_stats_close_at is null then
    new.player_stats_close_at = new.kickoff_at + interval '13 hours';
  end if;

  if new.player_ratings_close_at is null then
    new.player_ratings_close_at = new.kickoff_at + interval '7 days';
  end if;

  return new;
end;
$$;

create trigger matchdays_set_submission_windows
before insert or update of kickoff_at, player_stats_open_at, player_stats_close_at, player_ratings_close_at on public.matchdays
for each row
execute procedure public.set_matchday_submission_windows();

create trigger matchdays_set_updated_at
before update on public.matchdays
for each row
execute procedure public.set_updated_at();

create constraint trigger matchdays_validate_season_roster_integrity
after update of season_id on public.matchdays
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_season_roster_integrity();

alter table public.matchdays enable row level security;

create policy "Anyone can read matchdays"
on public.matchdays
for select
to anon
using (true);

create policy "Anyone can add matchdays"
on public.matchdays
for insert
to anon
with check (true);

create policy "Anyone can update matchdays"
on public.matchdays
for update
to anon
using (true)
with check (true);

create table public.matchday_matches (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  round_number integer not null,
  match_order integer not null,
  home_team_code text,
  away_team_code text,
  home_score integer,
  away_score integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_matches_round_allowed check (round_number in (1, 2)),
  constraint matchday_matches_order_allowed check (match_order in (1, 2)),
  constraint matchday_matches_home_team_allowed check (
    home_team_code is null or home_team_code in ('magenta', 'blue', 'green', 'orange')
  ),
  constraint matchday_matches_away_team_allowed check (
    away_team_code is null or away_team_code in ('magenta', 'blue', 'green', 'orange')
  ),
  constraint matchday_matches_score_allowed check (
    (home_score is null or home_score >= 0)
    and (away_score is null or away_score >= 0)
  ),
  constraint matchday_matches_distinct_teams check (
    home_team_code is null or away_team_code is null or home_team_code <> away_team_code
  )
);

create unique index matchday_matches_unique_slot_idx
on public.matchday_matches (matchday_id, round_number, match_order);

create trigger matchday_matches_set_updated_at
before update on public.matchday_matches
for each row
execute procedure public.set_updated_at();

alter table public.matchday_matches enable row level security;

create policy "Anyone can read matchday matches"
on public.matchday_matches
for select
to anon
using (true);

create policy "Anyone can add matchday matches"
on public.matchday_matches
for insert
to anon
with check (true);

create policy "Anyone can update matchday matches"
on public.matchday_matches
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete matchday matches"
on public.matchday_matches
for delete
to anon
using (true);

create table public.matchday_player_stats (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  attended boolean not null default false,
  attendance_status text not null default 'out',
  goals integer not null default 0,
  goal_keeps integer not null default 0,
  clean_sheet boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_player_stats_nonnegative check (
    goals >= 0 and goal_keeps >= 0
  ),
  constraint matchday_player_stats_attendance_status_allowed check (
    attendance_status in ('out', 'in', 'attended', 'available', 'late_cancel', 'no_show')
  )
);

create unique index matchday_player_stats_unique_idx
on public.matchday_player_stats (matchday_id, player_id);

create index matchday_player_stats_matchday_idx
on public.matchday_player_stats (matchday_id, attended);

create index matchday_player_stats_status_idx
on public.matchday_player_stats (matchday_id, attendance_status);

create trigger matchday_player_stats_set_updated_at
before update on public.matchday_player_stats
for each row
execute procedure public.set_updated_at();

create constraint trigger matchday_player_stats_require_season_roster
after insert or update of matchday_id, player_id on public.matchday_player_stats
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_player_on_season_roster();

alter table public.matchday_player_stats enable row level security;

create policy "Anyone can read matchday player stats"
on public.matchday_player_stats
for select
to anon
using (true);

create policy "Anyone can add matchday player stats"
on public.matchday_player_stats
for insert
to anon
with check (true);

create policy "Anyone can update matchday player stats"
on public.matchday_player_stats
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete matchday player stats"
on public.matchday_player_stats
for delete
to anon
using (true);

create table public.matchday_stat_submissions (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  submitted_by_player_id bigint not null references public.players(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  attendance_status text not null default 'in',
  goals integer not null default 0,
  goal_keeps integer not null default 0,
  clean_sheet boolean not null default false,
  note text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_stat_submissions_nonnegative check (
    goals >= 0 and goal_keeps >= 0
  ),
  constraint matchday_stat_submissions_attendance_allowed check (
    attendance_status in ('out', 'in', 'attended', 'available', 'late_cancel', 'no_show')
  ),
  constraint matchday_stat_submissions_note_length check (
    note is null or char_length(trim(note)) <= 400
  )
);

create unique index matchday_stat_submissions_unique_idx
on public.matchday_stat_submissions (matchday_id, submitted_by_player_id, player_id);

create index matchday_stat_submissions_matchday_idx
on public.matchday_stat_submissions (matchday_id, player_id);

create trigger matchday_stat_submissions_set_updated_at
before update on public.matchday_stat_submissions
for each row
execute procedure public.set_updated_at();

alter table public.matchday_stat_submissions enable row level security;

create policy "Anyone can read matchday stat submissions"
on public.matchday_stat_submissions
for select
to anon
using (true);

create policy "Anyone can add matchday stat submissions"
on public.matchday_stat_submissions
for insert
to anon
with check (true);

create policy "Anyone can update matchday stat submissions"
on public.matchday_stat_submissions
for update
to anon
using (true)
with check (true);

create table public.matchday_player_ratings (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  rater_player_id bigint not null references public.players(id) on delete cascade,
  ratee_player_id bigint not null references public.players(id) on delete cascade,
  relationship text not null,
  scores jsonb not null default '{}'::jsonb,
  comment text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_player_ratings_relationship_allowed check (
    relationship in ('teammate', 'opponent')
  ),
  constraint matchday_player_ratings_not_self check (
    rater_player_id <> ratee_player_id
  ),
  constraint matchday_player_ratings_scores_object check (
    jsonb_typeof(scores) = 'object'
  ),
  constraint matchday_player_ratings_comment_length check (
    comment is null or char_length(trim(comment)) <= 400
  )
);

create unique index matchday_player_ratings_unique_idx
on public.matchday_player_ratings (matchday_id, rater_player_id, ratee_player_id);

create index matchday_player_ratings_matchday_idx
on public.matchday_player_ratings (matchday_id, relationship);

create trigger matchday_player_ratings_set_updated_at
before update on public.matchday_player_ratings
for each row
execute procedure public.set_updated_at();

alter table public.matchday_player_ratings enable row level security;

create policy "Anyone can read matchday player ratings"
on public.matchday_player_ratings
for select
to anon
using (true);

create policy "Anyone can add matchday player ratings"
on public.matchday_player_ratings
for insert
to anon
with check (true);

create policy "Anyone can update matchday player ratings"
on public.matchday_player_ratings
for update
to anon
using (true)
with check (true);

create or replace function public.enforce_matchday_suggestion_author_on_roster()
returns trigger
language plpgsql
as $$
declare
  roster_exists boolean;
begin
  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = new.matchday_id
      and sp.player_id = new.author_player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster for matchday %s before saving matchday_suggestions.',
        new.author_player_id,
        new.matchday_id
      ),
      detail = format('matchday_id=%s, author_player_id=%s', new.matchday_id, new.author_player_id),
      hint = 'Add the player to season_players for the matchday season, then retry.';
  end if;

  return new;
end;
$$;

create table public.matchday_suggestions (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  author_player_id bigint not null references public.players(id) on delete cascade,
  title text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_suggestions_title_length check (
    char_length(trim(title)) between 3 and 120
  ),
  constraint matchday_suggestions_body_length check (
    char_length(trim(body)) between 1 and 1200
  )
);

create index matchday_suggestions_matchday_idx
on public.matchday_suggestions (matchday_id, created_at desc);

create index matchday_suggestions_author_idx
on public.matchday_suggestions (author_player_id, created_at desc);

create trigger matchday_suggestions_set_updated_at
before update on public.matchday_suggestions
for each row
execute procedure public.set_updated_at();

create constraint trigger matchday_suggestions_require_season_roster
after insert or update of matchday_id, author_player_id on public.matchday_suggestions
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_suggestion_author_on_roster();

alter table public.matchday_suggestions enable row level security;

create policy "Anyone can read matchday suggestions"
on public.matchday_suggestions
for select
to anon
using (true);

create policy "Anyone can add matchday suggestions"
on public.matchday_suggestions
for insert
to anon
with check (true);

create or replace function public.enforce_matchday_suggestion_reply_author_on_roster()
returns trigger
language plpgsql
as $$
declare
  target_matchday_id bigint;
  roster_exists boolean;
begin
  select suggestion.matchday_id
  into target_matchday_id
  from public.matchday_suggestions suggestion
  where suggestion.id = new.suggestion_id;

  if target_matchday_id is null then
    raise exception using
      errcode = '23503',
      message = format(
        'Suggestion %s must exist before saving matchday_suggestion_replies.',
        new.suggestion_id
      ),
      detail = format('suggestion_id=%s', new.suggestion_id);
  end if;

  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = target_matchday_id
      and sp.player_id = new.author_player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster for suggestion %s before saving matchday_suggestion_replies.',
        new.author_player_id,
        new.suggestion_id
      ),
      detail = format('suggestion_id=%s, author_player_id=%s', new.suggestion_id, new.author_player_id),
      hint = 'Add the player to season_players for the related matchday season, then retry.';
  end if;

  return new;
end;
$$;

create table public.matchday_suggestion_replies (
  id bigint generated by default as identity primary key,
  suggestion_id bigint not null references public.matchday_suggestions(id) on delete cascade,
  author_player_id bigint not null references public.players(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_suggestion_replies_body_length check (
    char_length(trim(body)) between 1 and 600
  )
);

create index matchday_suggestion_replies_suggestion_idx
on public.matchday_suggestion_replies (suggestion_id, created_at asc);

create index matchday_suggestion_replies_author_idx
on public.matchday_suggestion_replies (author_player_id, created_at desc);

create trigger matchday_suggestion_replies_set_updated_at
before update on public.matchday_suggestion_replies
for each row
execute procedure public.set_updated_at();

create constraint trigger matchday_suggestion_replies_require_season_roster
after insert or update of suggestion_id, author_player_id on public.matchday_suggestion_replies
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_suggestion_reply_author_on_roster();

alter table public.matchday_suggestion_replies enable row level security;

create policy "Anyone can read matchday suggestion replies"
on public.matchday_suggestion_replies
for select
to anon
using (true);

create policy "Anyone can add matchday suggestion replies"
on public.matchday_suggestion_replies
for insert
to anon
with check (true);

create or replace function public.enforce_matchday_suggestion_like_player_on_roster()
returns trigger
language plpgsql
as $$
declare
  target_matchday_id bigint;
  roster_exists boolean;
begin
  if new.suggestion_id is not null then
    select suggestion.matchday_id
    into target_matchday_id
    from public.matchday_suggestions suggestion
    where suggestion.id = new.suggestion_id;
  else
    select suggestion.matchday_id
    into target_matchday_id
    from public.matchday_suggestion_replies reply
    join public.matchday_suggestions suggestion
      on suggestion.id = reply.suggestion_id
    where reply.id = new.suggestion_reply_id;
  end if;

  if target_matchday_id is null then
    raise exception using
      errcode = '23503',
      message = 'A valid suggestion target is required before saving matchday_suggestion_likes.';
  end if;

  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = target_matchday_id
      and sp.player_id = new.liked_by_player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster before saving matchday_suggestion_likes.',
        new.liked_by_player_id
      ),
      detail = format(
        'suggestion_id=%s, suggestion_reply_id=%s, liked_by_player_id=%s',
        new.suggestion_id,
        new.suggestion_reply_id,
        new.liked_by_player_id
      ),
      hint = 'Add the player to season_players for the related matchday season, then retry.';
  end if;

  return new;
end;
$$;

create table public.matchday_suggestion_likes (
  id bigint generated by default as identity primary key,
  suggestion_id bigint references public.matchday_suggestions(id) on delete cascade,
  suggestion_reply_id bigint references public.matchday_suggestion_replies(id) on delete cascade,
  liked_by_player_id bigint not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint matchday_suggestion_likes_target_check check (
    (suggestion_id is not null and suggestion_reply_id is null)
    or (suggestion_id is null and suggestion_reply_id is not null)
  )
);

create unique index matchday_suggestion_likes_suggestion_unique_idx
on public.matchday_suggestion_likes (suggestion_id, liked_by_player_id)
where suggestion_id is not null;

create unique index matchday_suggestion_likes_reply_unique_idx
on public.matchday_suggestion_likes (suggestion_reply_id, liked_by_player_id)
where suggestion_reply_id is not null;

create index matchday_suggestion_likes_suggestion_idx
on public.matchday_suggestion_likes (suggestion_id, created_at desc)
where suggestion_id is not null;

create index matchday_suggestion_likes_reply_idx
on public.matchday_suggestion_likes (suggestion_reply_id, created_at desc)
where suggestion_reply_id is not null;

create index matchday_suggestion_likes_player_idx
on public.matchday_suggestion_likes (liked_by_player_id, created_at desc);

create constraint trigger matchday_suggestion_likes_require_season_roster
after insert or update of suggestion_id, suggestion_reply_id, liked_by_player_id on public.matchday_suggestion_likes
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_suggestion_like_player_on_roster();

alter table public.matchday_suggestion_likes enable row level security;

create policy "Anyone can read matchday suggestion likes"
on public.matchday_suggestion_likes
for select
to anon
using (true);

create policy "Anyone can add matchday suggestion likes"
on public.matchday_suggestion_likes
for insert
to anon
with check (true);

create policy "Anyone can delete matchday suggestion likes"
on public.matchday_suggestion_likes
for delete
to anon
using (true);

create table public.matchday_assignments (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  team_code text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_assignments_team_code_allowed check (
    team_code in ('magenta', 'blue', 'green', 'orange')
  )
);

create unique index matchday_assignments_unique_player_idx
on public.matchday_assignments (matchday_id, player_id);

create index matchday_assignments_matchday_idx
on public.matchday_assignments (matchday_id, team_code);

create trigger matchday_assignments_set_updated_at
before update on public.matchday_assignments
for each row
execute procedure public.set_updated_at();

create constraint trigger matchday_assignments_require_season_roster
after insert or update of matchday_id, player_id on public.matchday_assignments
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_player_on_season_roster();

alter table public.matchday_assignments enable row level security;

create policy "Anyone can read matchday assignments"
on public.matchday_assignments
for select
to anon
using (true);

create policy "Anyone can add matchday assignments"
on public.matchday_assignments
for insert
to anon
with check (true);

create policy "Anyone can update matchday assignments"
on public.matchday_assignments
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete matchday assignments"
on public.matchday_assignments
for delete
to anon
using (true);

create or replace function public.enforce_matchday_team_captain_eligibility()
returns trigger
language plpgsql
as $$
declare
  target_season_id bigint;
  current_tier_status text;
  assignment_exists boolean;
begin
  select md.season_id
  into target_season_id
  from public.matchdays md
  where md.id = new.matchday_id;

  if target_season_id is null then
    raise exception using
      errcode = '23503',
      message = format(
        'Matchday %s must exist before saving matchday_team_captains.',
        new.matchday_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s',
        new.matchday_id,
        new.team_code,
        new.player_id
      );
  end if;

  select lower(coalesce(sp.tier_status, ''))
  into current_tier_status
  from public.season_players sp
  where sp.season_id = target_season_id
    and sp.player_id = new.player_id
  limit 1;

  if current_tier_status not in ('core', 'flex') then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must be core or flex before saving a captain row for matchday %s.',
        new.player_id,
        new.matchday_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s, tier_status=%s',
        new.matchday_id,
        new.team_code,
        new.player_id,
        coalesce(current_tier_status, '<missing>')
      ),
      hint = 'Choose a core or flex player from the same season roster.';
  end if;

  if lower(coalesce(new.captain_tier, '')) <> current_tier_status then
    raise exception using
      errcode = '23514',
      message = format(
        'Captain tier %s does not match the current season tier %s for player %s.',
        coalesce(new.captain_tier, '<missing>'),
        current_tier_status,
        new.player_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s',
        new.matchday_id,
        new.team_code,
        new.player_id
      ),
      hint = 'Save the captain row with the player''s current core/flex season tier.';
  end if;

  select exists (
    select 1
    from public.matchday_assignments ma
    where ma.matchday_id = new.matchday_id
      and ma.player_id = new.player_id
      and ma.team_code = new.team_code
  )
  into assignment_exists;

  if not assignment_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must be assigned to team %s on matchday %s before saving a captain row.',
        new.player_id,
        new.team_code,
        new.matchday_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s',
        new.matchday_id,
        new.team_code,
        new.player_id
      ),
      hint = 'Assign the player to that team first, then save the captain selection.';
  end if;

  return new;
end;
$$;

create table public.matchday_team_captains (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  team_code text not null,
  player_id bigint not null references public.players(id) on delete cascade,
  captain_tier text not null,
  selection_method text not null default 'auto',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_team_captains_team_code_allowed check (
    team_code in ('magenta', 'blue', 'green', 'orange')
  ),
  constraint matchday_team_captains_captain_tier_allowed check (
    captain_tier in ('core', 'flex')
  ),
  constraint matchday_team_captains_selection_method_allowed check (
    selection_method in ('auto', 'replacement', 'manual')
  )
);

create unique index matchday_team_captains_matchday_team_idx
on public.matchday_team_captains (matchday_id, team_code);

create unique index matchday_team_captains_matchday_player_idx
on public.matchday_team_captains (matchday_id, player_id);

create index matchday_team_captains_player_idx
on public.matchday_team_captains (player_id, created_at desc);

create trigger matchday_team_captains_set_updated_at
before update on public.matchday_team_captains
for each row
execute procedure public.set_updated_at();

create constraint trigger matchday_team_captains_require_assignment
after insert or update of matchday_id, team_code, player_id, captain_tier on public.matchday_team_captains
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_team_captain_eligibility();

alter table public.matchday_team_captains enable row level security;

create policy "Anyone can read matchday team captains"
on public.matchday_team_captains
for select
to anon
using (true);

create policy "Anyone can add matchday team captains"
on public.matchday_team_captains
for insert
to anon
with check (true);

create policy "Anyone can update matchday team captains"
on public.matchday_team_captains
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete matchday team captains"
on public.matchday_team_captains
for delete
to anon
using (true);

create or replace view public.v_season_tier_scores as
with completed_matchdays as (
  select
    md.id,
    md.season_id,
    md.matchday_number
  from public.matchdays md
  join public.seasons s
    on s.id = md.season_id
  left join public.matchday_matches mm
    on mm.matchday_id = md.id
  group by md.id, md.season_id, md.matchday_number, s.model_start_matchday
  having md.matchday_number >= coalesce(s.model_start_matchday, 1)
     and count(*) filter (
       where mm.round_number in (1, 2)
         and mm.match_order in (1, 2)
     ) = 4
     and count(*) filter (
       where mm.round_number in (1, 2)
         and mm.match_order in (1, 2)
         and mm.home_score is not null
         and mm.away_score is not null
     ) = 4
),
stats_with_status as (
  select
    cmd.id as matchday_id,
    cmd.season_id,
    cmd.matchday_number,
    mps.player_id,
    case
      when coalesce(mps.attendance_status, 'out') = 'out' and mps.attended then 'in'
      when coalesce(mps.attendance_status, 'out') = 'attended' then 'in'
      else coalesce(mps.attendance_status, 'out')
    end as effective_attendance_status
  from completed_matchdays cmd
  join public.matchday_player_stats mps
    on mps.matchday_id = cmd.id
),
season_attendance as (
  select
    sws.season_id,
    sws.player_id,
    count(*) filter (where sws.effective_attendance_status = 'in') as games_attended,
    count(*) filter (where sws.effective_attendance_status = 'available') as games_available,
    count(*) filter (where sws.effective_attendance_status = 'late_cancel') as late_cancels,
    count(*) filter (where sws.effective_attendance_status = 'no_show') as no_shows
  from stats_with_status sws
  group by sws.season_id, sws.player_id
),
recent_matchdays as (
  select
    cmd.id,
    cmd.season_id,
    row_number() over (
      partition by cmd.season_id
      order by cmd.matchday_number desc
    ) as recent_rank
  from completed_matchdays cmd
),
recent_attendance as (
  select
    rm.season_id,
    sws.player_id,
    count(*) filter (where sws.effective_attendance_status = 'in') as recent_games_attended,
    count(*) filter (where sws.effective_attendance_status = 'available') as recent_games_available,
    count(*) filter (where sws.effective_attendance_status = 'late_cancel') as recent_late_cancels,
    count(*) filter (where sws.effective_attendance_status = 'no_show') as recent_no_shows
  from recent_matchdays rm
  join stats_with_status sws
    on sws.matchday_id = rm.id
  where rm.recent_rank <= 8
  group by rm.season_id, sws.player_id
),
base as (
  select
    sp.id as season_player_id,
    sp.season_id,
    sp.player_id,
    sp.tier_status,
    coalesce(p.desired_tier, p.status) as default_status,
    coalesce(sa.games_attended, 0) as games_attended,
    coalesce(sa.games_available, 0) as games_available,
    coalesce(sa.late_cancels, 0) as late_cancels,
    coalesce(sa.no_shows, 0) as no_shows,
    ((coalesce(sa.games_attended, 0) * 2) + coalesce(sa.games_available, 0) - coalesce(sa.late_cancels, 0) - (coalesce(sa.no_shows, 0) * 2)) as attendance_score,
    coalesce(ra.recent_games_attended, 0) as recent_games_attended,
    coalesce(ra.recent_games_available, 0) as recent_games_available,
    coalesce(ra.recent_late_cancels, 0) as recent_late_cancels,
    coalesce(ra.recent_no_shows, 0) as recent_no_shows,
    ((coalesce(ra.recent_games_attended, 0) * 2) + coalesce(ra.recent_games_available, 0) - coalesce(ra.recent_late_cancels, 0) - (coalesce(ra.recent_no_shows, 0) * 2)) as recent_attendance_score,
    sp.tier_reason,
    sp.movement_note,
    sp.is_eligible,
    sp.created_at,
    sp.updated_at
  from public.season_players sp
  join public.players p
    on p.id = sp.player_id
  left join season_attendance sa
    on sa.season_id = sp.season_id
   and sa.player_id = sp.player_id
  left join recent_attendance ra
    on ra.season_id = sp.season_id
   and ra.player_id = sp.player_id
),
scored as (
  select
    base.*,
    case
      when not base.is_eligible then 'sub'
      -- FIX: Suggested tier now follows full-season attendance first.
      -- Recent and historical attendance remain available as supporting evidence.
      when base.attendance_score >= 8
        and base.games_attended >= 4
        and base.no_shows <= 1 then 'core'
      when base.attendance_score >= 2
        and base.games_attended >= 1
        and base.no_shows <= 2 then 'flex'
      else 'sub'
    end as recommended_tier_status,
    case
      when not base.is_eligible then 'down'
      when base.attendance_score >= 8
        and base.games_attended >= 4
        and base.no_shows <= 1 then
        case
          when coalesce(base.tier_status, 'sub') = 'core' then 'steady'
          else 'up'
        end
      when base.attendance_score >= 2
        and base.games_attended >= 1
        and base.no_shows <= 2 then
        case
          when coalesce(base.tier_status, 'sub') = 'core' then 'down'
          when coalesce(base.tier_status, 'sub') = 'flex' then 'steady'
          else 'up'
        end
      else
        case
          when coalesce(base.tier_status, 'sub') = 'sub' then 'steady'
          else 'down'
        end
    end as trend
  from base
)
select
  scored.*,
  case
    when not scored.is_eligible then 'Ineligible. Restore eligibility before tier movement.'
    when scored.recommended_tier_status = 'core' and coalesce(scored.tier_status, 'sub') <> 'core' then 'Promotion case. Full-season attendance now clears the core line.'
    when scored.recommended_tier_status = 'flex' and coalesce(scored.tier_status, 'sub') = 'sub' then 'Trending up. Full-season attendance now supports rotation minutes.'
    when scored.recommended_tier_status = 'sub' and coalesce(scored.tier_status, 'sub') <> 'sub' then 'Season attendance has slipped below the current tier range.'
    else coalesce(scored.movement_note, 'Stable in current tier range.')
  end as transparency_note,
  case
    when not scored.is_eligible then 'Restore eligibility'
    when scored.recommended_tier_status = 'core' then 'Keep attendance high and avoid no-shows'
    when scored.recommended_tier_status = 'flex' and scored.games_attended < 3 then 'Build a longer attendance record'
    when scored.recommended_tier_status = 'flex' then 'Keep stacking attendance and push toward core'
    else 'Build stronger attendance and reduce late changes'
  end as next_step
from scored;

create or replace view public.v_season_tier_transparency as
select
  v.season_id,
  s.name as season_name,
  s.model_start_matchday,
  v.player_id,
  p.first_name,
  p.last_name,
  p.nickname,
  p.nationality,
  v.default_status,
  v.tier_status,
  v.recommended_tier_status,
  v.games_attended,
  v.games_available,
  v.late_cancels,
  v.no_shows,
  v.attendance_score,
  v.recent_games_attended,
  v.recent_games_available,
  v.recent_late_cancels,
  v.recent_no_shows,
  v.recent_attendance_score,
  v.is_eligible,
  v.tier_reason,
  v.movement_note,
  v.transparency_note,
  v.next_step,
  v.trend,
  v.created_at,
  v.updated_at
from public.v_season_tier_scores v
join public.players p
  on p.id = v.player_id
join public.seasons s
  on s.id = v.season_id;

create or replace view public.v_rotation_priority as
select
  vt.season_id,
  vt.season_name,
  vt.model_start_matchday,
  vt.player_id,
  vt.first_name,
  vt.last_name,
  vt.nickname,
  vt.nationality,
  vt.default_status,
  vt.tier_status,
  vt.recommended_tier_status,
  vt.games_attended,
  vt.games_available,
  vt.late_cancels,
  vt.no_shows,
  vt.attendance_score,
  vt.recent_games_attended,
  vt.recent_games_available,
  vt.recent_late_cancels,
  vt.recent_no_shows,
  vt.recent_attendance_score,
  vt.is_eligible,
  vt.tier_reason,
  vt.movement_note,
  vt.transparency_note,
  vt.next_step,
  vt.trend,
  row_number() over (
    partition by vt.season_id
    order by vt.games_attended asc, vt.attendance_score desc, vt.no_shows asc, lower(trim(vt.last_name)), lower(trim(vt.first_name))
  ) as rotation_priority_rank
from public.v_season_tier_transparency vt
where vt.tier_status = 'flex'
  and vt.is_eligible = true;

create table public.player_accounts (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  player_id bigint references public.players(id) on delete set null,
  role text not null default 'player',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint player_accounts_role_allowed check (role in ('player', 'admin'))
);

create index player_accounts_player_idx
on public.player_accounts (player_id)
where player_id is not null;

create trigger player_accounts_set_updated_at
before update on public.player_accounts
for each row
execute procedure public.set_updated_at();

alter table public.player_accounts enable row level security;

create policy "Users can read their own player account"
on public.player_accounts
for select
to authenticated
using (auth.uid() = auth_user_id);

revoke all on public.player_accounts from anon;
revoke all on public.player_accounts from authenticated;
grant select on public.player_accounts to authenticated;

create table public.admin_allowed_emails (
  id bigint generated by default as identity primary key,
  email text not null,
  note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_allowed_emails_email_present check (char_length(trim(email)) > 3)
);

create unique index admin_allowed_emails_email_key
on public.admin_allowed_emails ((lower(trim(email))));

create trigger admin_allowed_emails_set_updated_at
before update on public.admin_allowed_emails
for each row
execute procedure public.set_updated_at();

alter table public.admin_allowed_emails enable row level security;

revoke all on public.admin_allowed_emails from anon;
revoke all on public.admin_allowed_emails from authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_allowed_emails
    where lower(trim(email)) = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
      and is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Anyone can read players" on public.players;
drop policy if exists "Anyone can add players" on public.players;
drop policy if exists "Anyone can update players" on public.players;
drop policy if exists "Anyone can delete players" on public.players;

create policy "Anyone can read players"
on public.players
for select
to anon, authenticated
using (true);

create policy "Admins can add players"
on public.players
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update players"
on public.players
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete players"
on public.players
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read seasons" on public.seasons;
drop policy if exists "Anyone can add seasons" on public.seasons;
drop policy if exists "Anyone can update seasons" on public.seasons;
drop policy if exists "Admins can delete seasons" on public.seasons;

create policy "Anyone can read seasons"
on public.seasons
for select
to anon, authenticated
using (true);

create policy "Admins can add seasons"
on public.seasons
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update seasons"
on public.seasons
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete seasons"
on public.seasons
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read season players" on public.season_players;
drop policy if exists "Anyone can add season players" on public.season_players;
drop policy if exists "Anyone can update season players" on public.season_players;
drop policy if exists "Anyone can delete season players" on public.season_players;

create policy "Anyone can read season players"
on public.season_players
for select
to anon, authenticated
using (true);

create policy "Admins can add season players"
on public.season_players
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update season players"
on public.season_players
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete season players"
on public.season_players
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read season roster requests" on public.season_roster_requests;
drop policy if exists "Anyone can add season roster requests" on public.season_roster_requests;
drop policy if exists "Anyone can update season roster requests" on public.season_roster_requests;
drop policy if exists "Admins can delete season roster requests" on public.season_roster_requests;

create policy "Anyone can read season roster requests"
on public.season_roster_requests
for select
to anon, authenticated
using (true);

create policy "Anyone can add season roster requests"
on public.season_roster_requests
for insert
to anon, authenticated
with check (true);

create policy "Admins can update season roster requests"
on public.season_roster_requests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete season roster requests"
on public.season_roster_requests
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchdays" on public.matchdays;
drop policy if exists "Anyone can add matchdays" on public.matchdays;
drop policy if exists "Anyone can update matchdays" on public.matchdays;
drop policy if exists "Admins can delete matchdays" on public.matchdays;

create policy "Anyone can read matchdays"
on public.matchdays
for select
to anon, authenticated
using (true);

create policy "Admins can add matchdays"
on public.matchdays
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchdays"
on public.matchdays
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchdays"
on public.matchdays
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchday matches" on public.matchday_matches;
drop policy if exists "Anyone can add matchday matches" on public.matchday_matches;
drop policy if exists "Anyone can update matchday matches" on public.matchday_matches;
drop policy if exists "Anyone can delete matchday matches" on public.matchday_matches;

create policy "Anyone can read matchday matches"
on public.matchday_matches
for select
to anon, authenticated
using (true);

create policy "Admins can add matchday matches"
on public.matchday_matches
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchday matches"
on public.matchday_matches
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchday matches"
on public.matchday_matches
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchday player stats" on public.matchday_player_stats;
drop policy if exists "Anyone can add matchday player stats" on public.matchday_player_stats;
drop policy if exists "Anyone can update matchday player stats" on public.matchday_player_stats;
drop policy if exists "Anyone can delete matchday player stats" on public.matchday_player_stats;

create policy "Anyone can read matchday player stats"
on public.matchday_player_stats
for select
to anon, authenticated
using (true);

create policy "Admins can add matchday player stats"
on public.matchday_player_stats
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchday player stats"
on public.matchday_player_stats
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchday player stats"
on public.matchday_player_stats
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchday assignments" on public.matchday_assignments;
drop policy if exists "Anyone can add matchday assignments" on public.matchday_assignments;
drop policy if exists "Anyone can update matchday assignments" on public.matchday_assignments;
drop policy if exists "Anyone can delete matchday assignments" on public.matchday_assignments;

create policy "Anyone can read matchday assignments"
on public.matchday_assignments
for select
to anon, authenticated
using (true);

create policy "Admins can add matchday assignments"
on public.matchday_assignments
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchday assignments"
on public.matchday_assignments
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchday assignments"
on public.matchday_assignments
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchday team captains" on public.matchday_team_captains;
drop policy if exists "Anyone can add matchday team captains" on public.matchday_team_captains;
drop policy if exists "Anyone can update matchday team captains" on public.matchday_team_captains;
drop policy if exists "Anyone can delete matchday team captains" on public.matchday_team_captains;

create policy "Anyone can read matchday team captains"
on public.matchday_team_captains
for select
to anon, authenticated
using (true);

create policy "Admins can add matchday team captains"
on public.matchday_team_captains
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchday team captains"
on public.matchday_team_captains
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchday team captains"
on public.matchday_team_captains
for delete
to authenticated
using (public.is_admin());

commit;

select 'schema_ready' as status;
