-- STEP 3 OF 3: Seed canonical current season.
-- This file seeds the latest approved season from the canonical rebuild source.
-- Run this AFTER 01_schema.sql.
-- IMPORTANT: Set the dropdown to "No limit" before running.
-- Included workbooks:
-- 1. 2026 Spring: /Users/andresaguayo/mandarinas-club-hub copy/data/reseed_source/2026_spring/workbook.xlsx
-- Canonical rebuild rules applied:
-- 1. Player identities come from data/reseed_config/identity_map.csv and approved workbook sources.
-- 2. Slash/buddy rows are duplicated into each real player.
-- 3. Placeholder labels like Unknown/Imported are ignored.
-- 4. Team assignment conflicts prefer direct single-player rows over slash/buddy placeholders.
-- 5. Each season is fully replaced from workbook data.

begin;

with player_seed as (
  select *
  from (
    values
      ('Walter', 'Acero', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Andres', 'Aguayo', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Gabriel', 'Alava', 'Gabo', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('José', 'Blanco', 'Isco', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Jose', 'Cerf', 'Chato', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Pablo', 'Crespin', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Jesus', 'David', 'Chuchin', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Luis', 'de la Rosa', 'Chavito/Taliban', 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Nicky', 'Diaz', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Michael', 'Enriquez', 'Mikey', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Efrain', 'Jauregui', 'Poli', 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Min', 'Kim', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Guillermo', 'Lenz', 'Bolivia', 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Cesar', 'Lopez', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Luis', 'Marroquin', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Eder', 'Martinez', 'Eder', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Luis Enrique', 'Martinez', 'Cuñis', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rodrigo', 'Mena', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Gerardo', 'Mendizabal', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Alex', 'Meneses', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Gustavo', 'Moreno-Ortiz', 'Gustavo', 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Joseph', 'Muro', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Victor', 'Nizama', 'Victor N', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('José', 'Núñez', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Jhonatan', 'Ochoa', 'Coti', 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Alexis', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Cevallos', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Fabian', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Gus', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Karter', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Kevin', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Miguel', 'Player', 'Miguel A', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Mike', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Osmin', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Ramón', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rob', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Ruben', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Saul', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Sergio', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Uriel', 'Player', null, 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Valverde', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rudy', 'Ramirez', 'Rudy', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Oscar', 'Rosales', 'Pirlo', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Jhony', 'Sanchez', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Jose', 'Sarza', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Carlos', 'Silva', 'Carlos S', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Jordan', 'Toledo', 'Jordan', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rodolfo', 'Toledo', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('David', 'Toro', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Fernando', 'Urbano', 'Fer', 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Luis', 'Urueta', 'Javier', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Crisanto', 'Valencia', 'Valencia', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Asdruval', 'Villanueva', null, 'Unknown', array['MID']::text[], 'core', 'core')
  ) as seed(first_name, last_name, nickname, nationality, positions, desired_tier, status)
)
update public.players p
set
  nickname = player_seed.nickname,
  nationality = player_seed.nationality,
  positions = player_seed.positions,
  desired_tier = player_seed.desired_tier,
  status = player_seed.status
from player_seed
where lower(trim(p.first_name)) = lower(trim(player_seed.first_name))
  and lower(trim(p.last_name)) = lower(trim(player_seed.last_name));

with player_seed as (
  select *
  from (
    values
      ('Walter', 'Acero', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Andres', 'Aguayo', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Gabriel', 'Alava', 'Gabo', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('José', 'Blanco', 'Isco', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Jose', 'Cerf', 'Chato', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Pablo', 'Crespin', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Jesus', 'David', 'Chuchin', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Luis', 'de la Rosa', 'Chavito/Taliban', 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Nicky', 'Diaz', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Michael', 'Enriquez', 'Mikey', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Efrain', 'Jauregui', 'Poli', 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Min', 'Kim', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Guillermo', 'Lenz', 'Bolivia', 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Cesar', 'Lopez', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Luis', 'Marroquin', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Eder', 'Martinez', 'Eder', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Luis Enrique', 'Martinez', 'Cuñis', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rodrigo', 'Mena', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Gerardo', 'Mendizabal', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Alex', 'Meneses', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Gustavo', 'Moreno-Ortiz', 'Gustavo', 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Joseph', 'Muro', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Victor', 'Nizama', 'Victor N', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('José', 'Núñez', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Jhonatan', 'Ochoa', 'Coti', 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Alexis', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Cevallos', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Fabian', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Gus', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Karter', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Kevin', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Miguel', 'Player', 'Miguel A', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Mike', 'Player', null, 'Unknown', array['MID']::text[], 'rotation', 'rotation'),
      ('Osmin', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Ramón', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rob', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Ruben', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Saul', 'Player', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Sergio', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Uriel', 'Player', null, 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Valverde', 'Player', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rudy', 'Ramirez', 'Rudy', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Oscar', 'Rosales', 'Pirlo', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Jhony', 'Sanchez', null, 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Jose', 'Sarza', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Carlos', 'Silva', 'Carlos S', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Jordan', 'Toledo', 'Jordan', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rodolfo', 'Toledo', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('David', 'Toro', null, 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Fernando', 'Urbano', 'Fer', 'Unknown', array['MID']::text[], 'flex_sub', 'flex_sub'),
      ('Luis', 'Urueta', 'Javier', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Crisanto', 'Valencia', 'Valencia', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Asdruval', 'Villanueva', null, 'Unknown', array['MID']::text[], 'core', 'core')
  ) as seed(first_name, last_name, nickname, nationality, positions, desired_tier, status)
)
insert into public.players (
  first_name,
  last_name,
  nickname,
  nationality,
  positions,
  desired_tier,
  status
)
select
  player_seed.first_name,
  player_seed.last_name,
  player_seed.nickname,
  player_seed.nationality,
  player_seed.positions,
  player_seed.desired_tier,
  player_seed.status
from player_seed
where not exists (
  select 1
  from public.players p
  where lower(trim(p.first_name)) = lower(trim(player_seed.first_name))
    and lower(trim(p.last_name)) = lower(trim(player_seed.last_name))
);

-- ---------------------------------------------------------------------------
-- 2026 Spring
-- ---------------------------------------------------------------------------
delete from public.seasons
where lower(trim(name)) = lower('2026 Spring');

insert into public.seasons (
  name,
  total_matchdays,
  core_spots,
  rotation_spots,
  model_start_matchday,
  attendance_points,
  win_points,
  draw_points,
  loss_points,
  goal_keep_points,
  team_goal_points
)
values (
  '2026 Spring',
  8,
  31,
  10,
  1,
  2,
  2,
  1,
  0,
  1,
  1
);

with season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_seed as (
  select *
  from (
    values
      (1, timestamptz '2026-03-05 12:00:00 America/Los_Angeles', false),
      (2, timestamptz '2026-03-12 12:00:00 America/Los_Angeles', false),
      (3, timestamptz '2026-03-19 12:00:00 America/Los_Angeles', false),
      (4, timestamptz '2026-03-26 12:00:00 America/Los_Angeles', false),
      (5, timestamptz '2026-04-02 12:00:00 America/Los_Angeles', true),
      (6, timestamptz '2026-04-09 12:00:00 America/Los_Angeles', true),
      (7, timestamptz '2026-04-16 12:00:00 America/Los_Angeles', true),
      (8, timestamptz '2026-04-23 12:00:00 America/Los_Angeles', true)
  ) as seed(matchday_number, kickoff_at, goals_count_as_points)
)
insert into public.matchdays (season_id, matchday_number, kickoff_at, goals_count_as_points)
select
  season_row.id,
  matchday_seed.matchday_number,
  matchday_seed.kickoff_at,
  matchday_seed.goals_count_as_points
from season_row
cross join matchday_seed;

with season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_lookup as (
  select md.id, md.matchday_number
  from public.matchdays md
  join season_row on season_row.id = md.season_id
),
match_seed as (
  select *
  from (
    values
      (1, 1, 1, 'blue', 'magenta', 0, 3),
      (1, 1, 2, 'orange', 'green', 1, 4),
      (1, 2, 1, 'magenta', 'green', 2, 1),
      (1, 2, 2, 'orange', 'blue', 1, 2),
      (2, 1, 1, 'blue', 'magenta', 3, 2),
      (2, 1, 2, 'green', 'orange', 0, 0),
      (2, 2, 1, 'blue', 'green', 4, 1),
      (2, 2, 2, 'magenta', 'orange', 1, 1),
      (3, 1, 1, 'blue', 'magenta', 5, 0),
      (3, 1, 2, 'orange', 'green', 3, 1),
      (3, 2, 1, 'blue', 'orange', 1, 3),
      (3, 2, 2, 'magenta', 'green', 0, 6),
      (4, 1, 1, 'blue', 'magenta', 1, 3),
      (4, 1, 2, 'green', 'orange', 0, 1),
      (4, 2, 1, 'blue', 'green', 1, 2),
      (4, 2, 2, 'orange', 'magenta', 3, 2),
      (5, 1, 1, 'magenta', 'blue', 7, 1),
      (5, 1, 2, 'green', 'orange', 2, 4),
      (5, 2, 1, 'blue', 'green', 1, 7),
      (5, 2, 2, 'magenta', 'orange', 0, 0),
      (6, 1, 1, 'blue', 'magenta', 2, 0),
      (6, 1, 2, 'green', 'orange', 3, 3),
      (6, 2, 1, 'blue', 'green', 7, 1),
      (6, 2, 2, 'magenta', 'orange', 2, 1),
      (7, 1, 1, 'blue', 'magenta', 0, 0),
      (7, 1, 2, 'green', 'orange', 1, 2),
      (7, 2, 1, 'orange', 'magenta', 0, 0),
      (7, 2, 2, 'green', 'blue', 3, 4),
      (8, 1, 1, 'blue', 'orange', 5, 1),
      (8, 1, 2, 'magenta', 'green', 1, 0),
      (8, 2, 1, 'blue', 'magenta', 2, 3),
      (8, 2, 2, 'green', 'orange', 1, 2)
  ) as seed(matchday_number, round_number, match_order, home_team_code, away_team_code, home_score, away_score)
)
insert into public.matchday_matches (
  matchday_id,
  round_number,
  match_order,
  home_team_code,
  away_team_code,
  home_score,
  away_score
)
select
  matchday_lookup.id,
  match_seed.round_number,
  match_seed.match_order,
  match_seed.home_team_code,
  match_seed.away_team_code,
  match_seed.home_score,
  match_seed.away_score
from match_seed
join matchday_lookup
  on matchday_lookup.matchday_number = match_seed.matchday_number;

with season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
season_player_seed as (
  select *
  from (
    values
      ('Walter', 'Acero', 'core'),
      ('Andres', 'Aguayo', 'core'),
      ('Gabriel', 'Alava', 'core'),
      ('José', 'Blanco', 'core'),
      ('Jose', 'Cerf', 'core'),
      ('Pablo', 'Crespin', 'flex_sub'),
      ('Jesus', 'David', 'core'),
      ('Luis', 'de la Rosa', 'rotation'),
      ('Nicky', 'Diaz', 'core'),
      ('Michael', 'Enriquez', 'core'),
      ('Efrain', 'Jauregui', 'rotation'),
      ('Min', 'Kim', 'flex_sub'),
      ('Guillermo', 'Lenz', 'flex_sub'),
      ('Cesar', 'Lopez', 'rotation'),
      ('Luis', 'Marroquin', 'flex_sub'),
      ('Eder', 'Martinez', 'core'),
      ('Luis Enrique', 'Martinez', 'core'),
      ('Rodrigo', 'Mena', 'core'),
      ('Gerardo', 'Mendizabal', 'core'),
      ('Alex', 'Meneses', 'core'),
      ('Gustavo', 'Moreno-Ortiz', 'rotation'),
      ('Joseph', 'Muro', 'flex_sub'),
      ('Victor', 'Nizama', 'core'),
      ('José', 'Núñez', 'flex_sub'),
      ('Jhonatan', 'Ochoa', 'rotation'),
      ('Alexis', 'Player', 'rotation'),
      ('Cevallos', 'Player', 'core'),
      ('Fabian', 'Player', 'rotation'),
      ('Gus', 'Player', 'core'),
      ('Karter', 'Player', 'flex_sub'),
      ('Kevin', 'Player', 'rotation'),
      ('Miguel', 'Player', 'core'),
      ('Mike', 'Player', 'rotation'),
      ('Osmin', 'Player', 'flex_sub'),
      ('Ramón', 'Player', 'core'),
      ('Rob', 'Player', 'flex_sub'),
      ('Ruben', 'Player', 'core'),
      ('Saul', 'Player', 'flex_sub'),
      ('Sergio', 'Player', 'core'),
      ('Uriel', 'Player', 'rotation'),
      ('Valverde', 'Player', 'core'),
      ('Rudy', 'Ramirez', 'core'),
      ('Oscar', 'Rosales', 'core'),
      ('Jhony', 'Sanchez', 'flex_sub'),
      ('Jose', 'Sarza', 'core'),
      ('Carlos', 'Silva', 'core'),
      ('Jordan', 'Toledo', 'core'),
      ('Rodolfo', 'Toledo', 'core'),
      ('David', 'Toro', 'core'),
      ('Fernando', 'Urbano', 'flex_sub'),
      ('Luis', 'Urueta', 'core'),
      ('Crisanto', 'Valencia', 'core'),
      ('Asdruval', 'Villanueva', 'core')
  ) as seed(first_name, last_name, tier_status)
)
insert into public.season_players (
  season_id,
  player_id,
  tier_status,
  tier_reason,
  movement_note,
  is_eligible
)
select distinct
  season_row.id,
  p.id,
  season_player_seed.tier_status,
  null,
  null,
  true
from season_row
join season_player_seed
  on true
join public.players p
  on lower(trim(p.first_name)) = lower(trim(season_player_seed.first_name))
 and lower(trim(p.last_name)) = lower(trim(season_player_seed.last_name));

with season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_lookup as (
  select md.id, md.matchday_number
  from public.matchdays md
  join season_row on season_row.id = md.season_id
),
assignment_seed as (
  select *
  from (
    values
      ('Andres', 'Aguayo', 1, 'magenta'),
      ('Gabriel', 'Alava', 1, 'green'),
      ('José', 'Blanco', 1, 'blue'),
      ('Jose', 'Cerf', 1, 'magenta'),
      ('Pablo', 'Crespin', 1, 'green'),
      ('Jesus', 'David', 1, 'orange'),
      ('Nicky', 'Diaz', 1, 'green'),
      ('Michael', 'Enriquez', 1, 'orange'),
      ('Efrain', 'Jauregui', 1, 'magenta'),
      ('Cesar', 'Lopez', 1, 'blue'),
      ('Eder', 'Martinez', 1, 'orange'),
      ('Gerardo', 'Mendizabal', 1, 'magenta'),
      ('Alex', 'Meneses', 1, 'green'),
      ('Gustavo', 'Moreno-Ortiz', 1, 'blue'),
      ('Victor', 'Nizama', 1, 'orange'),
      ('José', 'Núñez', 1, 'blue'),
      ('Alexis', 'Player', 1, 'blue'),
      ('Cevallos', 'Player', 1, 'orange'),
      ('Fabian', 'Player', 1, 'magenta'),
      ('Gus', 'Player', 1, 'green'),
      ('Karter', 'Player', 1, 'green'),
      ('Kevin', 'Player', 1, 'green'),
      ('Miguel', 'Player', 1, 'blue'),
      ('Mike', 'Player', 1, 'green'),
      ('Rob', 'Player', 1, 'orange'),
      ('Ruben', 'Player', 1, 'green'),
      ('Sergio', 'Player', 1, 'blue'),
      ('Uriel', 'Player', 1, 'blue'),
      ('Valverde', 'Player', 1, 'orange'),
      ('Rudy', 'Ramirez', 1, 'magenta'),
      ('Jose', 'Sarza', 1, 'magenta'),
      ('Carlos', 'Silva', 1, 'green'),
      ('Jordan', 'Toledo', 1, 'magenta'),
      ('Rodolfo', 'Toledo', 1, 'magenta'),
      ('David', 'Toro', 1, 'blue'),
      ('Luis', 'Urueta', 1, 'magenta'),
      ('Crisanto', 'Valencia', 1, 'blue'),
      ('Asdruval', 'Villanueva', 1, 'blue'),
      ('Andres', 'Aguayo', 2, 'green'),
      ('Gabriel', 'Alava', 2, 'magenta'),
      ('José', 'Blanco', 2, 'green'),
      ('Jose', 'Cerf', 2, 'magenta'),
      ('Jesus', 'David', 2, 'blue'),
      ('Luis', 'de la Rosa', 2, 'orange'),
      ('Nicky', 'Diaz', 2, 'blue'),
      ('Michael', 'Enriquez', 2, 'orange'),
      ('Efrain', 'Jauregui', 2, 'green'),
      ('Guillermo', 'Lenz', 2, 'magenta'),
      ('Cesar', 'Lopez', 2, 'orange'),
      ('Luis', 'Marroquin', 2, 'magenta'),
      ('Eder', 'Martinez', 2, 'green'),
      ('Luis Enrique', 'Martinez', 2, 'green'),
      ('Gerardo', 'Mendizabal', 2, 'blue'),
      ('Alex', 'Meneses', 2, 'blue'),
      ('Gustavo', 'Moreno-Ortiz', 2, 'orange'),
      ('Victor', 'Nizama', 2, 'blue'),
      ('José', 'Núñez', 2, 'magenta'),
      ('Jhonatan', 'Ochoa', 2, 'orange'),
      ('Alexis', 'Player', 2, 'orange'),
      ('Cevallos', 'Player', 2, 'magenta'),
      ('Fabian', 'Player', 2, 'magenta'),
      ('Gus', 'Player', 2, 'green'),
      ('Ruben', 'Player', 2, 'orange'),
      ('Sergio', 'Player', 2, 'blue'),
      ('Uriel', 'Player', 2, 'orange'),
      ('Valverde', 'Player', 2, 'orange'),
      ('Oscar', 'Rosales', 2, 'green'),
      ('Jose', 'Sarza', 2, 'green'),
      ('Carlos', 'Silva', 2, 'orange'),
      ('Jordan', 'Toledo', 2, 'orange'),
      ('Rodolfo', 'Toledo', 2, 'blue'),
      ('David', 'Toro', 2, 'green'),
      ('Luis', 'Urueta', 2, 'magenta'),
      ('Asdruval', 'Villanueva', 2, 'blue'),
      ('Andres', 'Aguayo', 3, 'blue'),
      ('Gabriel', 'Alava', 3, 'green'),
      ('José', 'Blanco', 3, 'green'),
      ('Jose', 'Cerf', 3, 'blue'),
      ('Pablo', 'Crespin', 3, 'orange'),
      ('Jesus', 'David', 3, 'orange'),
      ('Luis', 'de la Rosa', 3, 'blue'),
      ('Nicky', 'Diaz', 3, 'blue'),
      ('Michael', 'Enriquez', 3, 'blue'),
      ('Efrain', 'Jauregui', 3, 'blue'),
      ('Guillermo', 'Lenz', 3, 'orange'),
      ('Cesar', 'Lopez', 3, 'green'),
      ('Eder', 'Martinez', 3, 'magenta'),
      ('Rodrigo', 'Mena', 3, 'magenta'),
      ('Gerardo', 'Mendizabal', 3, 'green'),
      ('Alex', 'Meneses', 3, 'green'),
      ('Gustavo', 'Moreno-Ortiz', 3, 'green'),
      ('Victor', 'Nizama', 3, 'green'),
      ('José', 'Núñez', 3, 'magenta'),
      ('Jhonatan', 'Ochoa', 3, 'blue'),
      ('Alexis', 'Player', 3, 'green'),
      ('Fabian', 'Player', 3, 'blue'),
      ('Karter', 'Player', 3, 'blue'),
      ('Kevin', 'Player', 3, 'blue'),
      ('Miguel', 'Player', 3, 'magenta'),
      ('Mike', 'Player', 3, 'blue'),
      ('Rob', 'Player', 3, 'magenta'),
      ('Ruben', 'Player', 3, 'orange'),
      ('Sergio', 'Player', 3, 'blue'),
      ('Uriel', 'Player', 3, 'green'),
      ('Rudy', 'Ramirez', 3, 'orange'),
      ('Oscar', 'Rosales', 3, 'magenta'),
      ('Jose', 'Sarza', 3, 'orange'),
      ('Carlos', 'Silva', 3, 'orange'),
      ('Jordan', 'Toledo', 3, 'magenta'),
      ('Rodolfo', 'Toledo', 3, 'green'),
      ('David', 'Toro', 3, 'green'),
      ('Fernando', 'Urbano', 3, 'magenta'),
      ('Luis', 'Urueta', 3, 'magenta'),
      ('Crisanto', 'Valencia', 3, 'orange'),
      ('Asdruval', 'Villanueva', 3, 'magenta'),
      ('Walter', 'Acero', 4, 'blue'),
      ('Andres', 'Aguayo', 4, 'green'),
      ('Gabriel', 'Alava', 4, 'green'),
      ('José', 'Blanco', 4, 'orange'),
      ('Jose', 'Cerf', 4, 'green'),
      ('Jesus', 'David', 4, 'green'),
      ('Nicky', 'Diaz', 4, 'orange'),
      ('Michael', 'Enriquez', 4, 'magenta'),
      ('Efrain', 'Jauregui', 4, 'green'),
      ('Guillermo', 'Lenz', 4, 'blue'),
      ('Cesar', 'Lopez', 4, 'magenta'),
      ('Luis Enrique', 'Martinez', 4, 'orange'),
      ('Rodrigo', 'Mena', 4, 'magenta'),
      ('Gerardo', 'Mendizabal', 4, 'magenta'),
      ('Alex', 'Meneses', 4, 'orange'),
      ('Gustavo', 'Moreno-Ortiz', 4, 'magenta'),
      ('Victor', 'Nizama', 4, 'orange'),
      ('José', 'Núñez', 4, 'magenta'),
      ('Alexis', 'Player', 4, 'magenta'),
      ('Cevallos', 'Player', 4, 'blue'),
      ('Fabian', 'Player', 4, 'green'),
      ('Gus', 'Player', 4, 'blue'),
      ('Kevin', 'Player', 4, 'green'),
      ('Miguel', 'Player', 4, 'green'),
      ('Mike', 'Player', 4, 'green'),
      ('Ramón', 'Player', 4, 'orange'),
      ('Rob', 'Player', 4, 'blue'),
      ('Ruben', 'Player', 4, 'magenta'),
      ('Uriel', 'Player', 4, 'magenta'),
      ('Valverde', 'Player', 4, 'green'),
      ('Rudy', 'Ramirez', 4, 'blue'),
      ('Oscar', 'Rosales', 4, 'blue'),
      ('Jose', 'Sarza', 4, 'blue'),
      ('Carlos', 'Silva', 4, 'magenta'),
      ('Jordan', 'Toledo', 4, 'orange'),
      ('Rodolfo', 'Toledo', 4, 'magenta'),
      ('David', 'Toro', 4, 'green'),
      ('Luis', 'Urueta', 4, 'orange'),
      ('Asdruval', 'Villanueva', 4, 'blue'),
      ('Walter', 'Acero', 5, 'blue'),
      ('Andres', 'Aguayo', 5, 'blue'),
      ('Gabriel', 'Alava', 5, 'magenta'),
      ('Jose', 'Cerf', 5, 'blue'),
      ('Pablo', 'Crespin', 5, 'green'),
      ('Jesus', 'David', 5, 'green'),
      ('Nicky', 'Diaz', 5, 'orange'),
      ('Michael', 'Enriquez', 5, 'magenta'),
      ('Efrain', 'Jauregui', 5, 'blue'),
      ('Guillermo', 'Lenz', 5, 'orange'),
      ('Cesar', 'Lopez', 5, 'orange'),
      ('Luis', 'Marroquin', 5, 'green'),
      ('Eder', 'Martinez', 5, 'magenta'),
      ('Gerardo', 'Mendizabal', 5, 'blue'),
      ('Alex', 'Meneses', 5, 'orange'),
      ('Gustavo', 'Moreno-Ortiz', 5, 'magenta'),
      ('Joseph', 'Muro', 5, 'orange'),
      ('Victor', 'Nizama', 5, 'blue'),
      ('José', 'Núñez', 5, 'orange'),
      ('Alexis', 'Player', 5, 'orange'),
      ('Fabian', 'Player', 5, 'blue'),
      ('Gus', 'Player', 5, 'green'),
      ('Miguel', 'Player', 5, 'orange'),
      ('Rob', 'Player', 5, 'blue'),
      ('Ruben', 'Player', 5, 'blue'),
      ('Saul', 'Player', 5, 'blue'),
      ('Uriel', 'Player', 5, 'magenta'),
      ('Rudy', 'Ramirez', 5, 'magenta'),
      ('Oscar', 'Rosales', 5, 'green'),
      ('Jhony', 'Sanchez', 5, 'green'),
      ('Jose', 'Sarza', 5, 'orange'),
      ('Carlos', 'Silva', 5, 'magenta'),
      ('Jordan', 'Toledo', 5, 'green'),
      ('Rodolfo', 'Toledo', 5, 'orange'),
      ('Luis', 'Urueta', 5, 'green'),
      ('Asdruval', 'Villanueva', 5, 'magenta'),
      ('Andres', 'Aguayo', 6, 'blue'),
      ('Gabriel', 'Alava', 6, 'green'),
      ('Jose', 'Cerf', 6, 'green'),
      ('Pablo', 'Crespin', 6, 'orange'),
      ('Jesus', 'David', 6, 'orange'),
      ('Nicky', 'Diaz', 6, 'magenta'),
      ('Michael', 'Enriquez', 6, 'orange'),
      ('Efrain', 'Jauregui', 6, 'blue'),
      ('Min', 'Kim', 6, 'orange'),
      ('Cesar', 'Lopez', 6, 'magenta'),
      ('Eder', 'Martinez', 6, 'magenta'),
      ('Luis Enrique', 'Martinez', 6, 'green'),
      ('Rodrigo', 'Mena', 6, 'blue'),
      ('Gerardo', 'Mendizabal', 6, 'green'),
      ('Alex', 'Meneses', 6, 'magenta'),
      ('Joseph', 'Muro', 6, 'blue'),
      ('Victor', 'Nizama', 6, 'orange'),
      ('José', 'Núñez', 6, 'orange'),
      ('Alexis', 'Player', 6, 'magenta'),
      ('Cevallos', 'Player', 6, 'magenta'),
      ('Fabian', 'Player', 6, 'blue'),
      ('Gus', 'Player', 6, 'orange'),
      ('Karter', 'Player', 6, 'orange'),
      ('Rob', 'Player', 6, 'green'),
      ('Ruben', 'Player', 6, 'blue'),
      ('Valverde', 'Player', 6, 'green'),
      ('Rudy', 'Ramirez', 6, 'green'),
      ('Jhony', 'Sanchez', 6, 'orange'),
      ('Jose', 'Sarza', 6, 'blue'),
      ('Carlos', 'Silva', 6, 'blue'),
      ('Rodolfo', 'Toledo', 6, 'magenta'),
      ('David', 'Toro', 6, 'blue'),
      ('Fernando', 'Urbano', 6, 'green'),
      ('Luis', 'Urueta', 6, 'blue'),
      ('Crisanto', 'Valencia', 6, 'magenta'),
      ('Asdruval', 'Villanueva', 6, 'green'),
      ('Walter', 'Acero', 7, 'magenta'),
      ('Gabriel', 'Alava', 7, 'green'),
      ('José', 'Blanco', 7, 'blue'),
      ('Jose', 'Cerf', 7, 'green'),
      ('Jesus', 'David', 7, 'orange'),
      ('Nicky', 'Diaz', 7, 'magenta'),
      ('Michael', 'Enriquez', 7, 'blue'),
      ('Efrain', 'Jauregui', 7, 'blue'),
      ('Min', 'Kim', 7, 'magenta'),
      ('Guillermo', 'Lenz', 7, 'orange'),
      ('Cesar', 'Lopez', 7, 'green'),
      ('Luis Enrique', 'Martinez', 7, 'orange'),
      ('Alex', 'Meneses', 7, 'magenta'),
      ('Gustavo', 'Moreno-Ortiz', 7, 'green'),
      ('Joseph', 'Muro', 7, 'green'),
      ('Victor', 'Nizama', 7, 'blue'),
      ('Alexis', 'Player', 7, 'green'),
      ('Cevallos', 'Player', 7, 'orange'),
      ('Fabian', 'Player', 7, 'blue'),
      ('Gus', 'Player', 7, 'green'),
      ('Karter', 'Player', 7, 'magenta'),
      ('Kevin', 'Player', 7, 'blue'),
      ('Miguel', 'Player', 7, 'blue'),
      ('Mike', 'Player', 7, 'blue'),
      ('Osmin', 'Player', 7, 'orange'),
      ('Ruben', 'Player', 7, 'orange'),
      ('Sergio', 'Player', 7, 'orange'),
      ('Uriel', 'Player', 7, 'green'),
      ('Valverde', 'Player', 7, 'magenta'),
      ('Rudy', 'Ramirez', 7, 'blue'),
      ('Oscar', 'Rosales', 7, 'orange'),
      ('Jhony', 'Sanchez', 7, 'green'),
      ('Jose', 'Sarza', 7, 'orange'),
      ('Carlos', 'Silva', 7, 'blue'),
      ('Jordan', 'Toledo', 7, 'magenta'),
      ('Rodolfo', 'Toledo', 7, 'magenta'),
      ('Fernando', 'Urbano', 7, 'magenta'),
      ('Luis', 'Urueta', 7, 'blue'),
      ('Crisanto', 'Valencia', 7, 'green'),
      ('Asdruval', 'Villanueva', 7, 'green'),
      ('Walter', 'Acero', 8, 'blue'),
      ('Andres', 'Aguayo', 8, 'blue'),
      ('Gabriel', 'Alava', 8, 'blue'),
      ('José', 'Blanco', 8, 'magenta'),
      ('Jose', 'Cerf', 8, 'orange'),
      ('Jesus', 'David', 8, 'orange'),
      ('Michael', 'Enriquez', 8, 'magenta'),
      ('Efrain', 'Jauregui', 8, 'orange'),
      ('Min', 'Kim', 8, 'magenta'),
      ('Cesar', 'Lopez', 8, 'magenta'),
      ('Eder', 'Martinez', 8, 'blue'),
      ('Luis Enrique', 'Martinez', 8, 'orange'),
      ('Rodrigo', 'Mena', 8, 'green'),
      ('Alex', 'Meneses', 8, 'orange'),
      ('Gustavo', 'Moreno-Ortiz', 8, 'blue'),
      ('Victor', 'Nizama', 8, 'orange'),
      ('José', 'Núñez', 8, 'orange'),
      ('Alexis', 'Player', 8, 'magenta'),
      ('Fabian', 'Player', 8, 'orange'),
      ('Kevin', 'Player', 8, 'green'),
      ('Miguel', 'Player', 8, 'blue'),
      ('Mike', 'Player', 8, 'green'),
      ('Osmin', 'Player', 8, 'blue'),
      ('Ruben', 'Player', 8, 'blue'),
      ('Sergio', 'Player', 8, 'magenta'),
      ('Uriel', 'Player', 8, 'blue'),
      ('Valverde', 'Player', 8, 'magenta'),
      ('Rudy', 'Ramirez', 8, 'magenta'),
      ('Jose', 'Sarza', 8, 'green'),
      ('Carlos', 'Silva', 8, 'magenta'),
      ('Jordan', 'Toledo', 8, 'magenta'),
      ('Rodolfo', 'Toledo', 8, 'green'),
      ('David', 'Toro', 8, 'green'),
      ('Fernando', 'Urbano', 8, 'green'),
      ('Luis', 'Urueta', 8, 'blue'),
      ('Crisanto', 'Valencia', 8, 'orange'),
      ('Asdruval', 'Villanueva', 8, 'green')
  ) as seed(first_name, last_name, matchday_number, team_code)
)
insert into public.matchday_assignments (matchday_id, player_id, team_code)
select
  matchday_lookup.id,
  p.id,
  assignment_seed.team_code
from assignment_seed
join public.players p
  on lower(trim(p.first_name)) = lower(trim(assignment_seed.first_name))
 and lower(trim(p.last_name)) = lower(trim(assignment_seed.last_name))
join matchday_lookup
  on matchday_lookup.matchday_number = assignment_seed.matchday_number;

with season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_lookup as (
  select md.id, md.matchday_number
  from public.matchdays md
  join season_row on season_row.id = md.season_id
),
stat_seed as (
  select *
  from (
    values
      ('Andres', 'Aguayo', 1, true, 'in', 1, 0, false),
      ('Gabriel', 'Alava', 1, true, 'in', 0, 0, false),
      ('José', 'Blanco', 1, true, 'in', 1, 0, false),
      ('Jose', 'Cerf', 1, true, 'in', 0, 0, false),
      ('Pablo', 'Crespin', 1, true, 'in', 0, 0, false),
      ('Jesus', 'David', 1, true, 'in', 1, 0, false),
      ('Nicky', 'Diaz', 1, true, 'in', 1, 0, false),
      ('Michael', 'Enriquez', 1, true, 'in', 0, 0, false),
      ('Efrain', 'Jauregui', 1, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 1, true, 'in', 0, 0, false),
      ('Eder', 'Martinez', 1, true, 'in', 0, 0, false),
      ('Gerardo', 'Mendizabal', 1, true, 'in', 3, 0, false),
      ('Alex', 'Meneses', 1, true, 'in', 2, 0, false),
      ('Gustavo', 'Moreno-Ortiz', 1, true, 'in', 0, 1, false),
      ('Victor', 'Nizama', 1, true, 'in', 0, 0, false),
      ('José', 'Núñez', 1, true, 'in', 0, 0, false),
      ('Alexis', 'Player', 1, true, 'in', 0, 0, false),
      ('Cevallos', 'Player', 1, true, 'in', 0, 1, false),
      ('Fabian', 'Player', 1, true, 'in', 0, 0, false),
      ('Gus', 'Player', 1, true, 'in', 0, 0, false),
      ('Karter', 'Player', 1, true, 'in', 0, 0, false),
      ('Kevin', 'Player', 1, true, 'in', 0, 0, false),
      ('Miguel', 'Player', 1, true, 'in', 0, 0, false),
      ('Mike', 'Player', 1, true, 'in', 0, 0, false),
      ('Rob', 'Player', 1, true, 'in', 0, 1, false),
      ('Ruben', 'Player', 1, true, 'in', 0, 0, false),
      ('Sergio', 'Player', 1, true, 'in', 0, 0, false),
      ('Uriel', 'Player', 1, true, 'in', 0, 1, false),
      ('Valverde', 'Player', 1, true, 'in', 0, 0, false),
      ('Rudy', 'Ramirez', 1, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 1, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 1, true, 'in', 0, 0, false),
      ('Jordan', 'Toledo', 1, true, 'in', 1, 0, false),
      ('Rodolfo', 'Toledo', 1, true, 'in', 0, 1, true),
      ('David', 'Toro', 1, true, 'in', 0, 0, false),
      ('Luis', 'Urueta', 1, true, 'in', 0, 0, false),
      ('Crisanto', 'Valencia', 1, true, 'in', 1, 0, false),
      ('Asdruval', 'Villanueva', 1, true, 'in', 0, 0, false),
      ('Andres', 'Aguayo', 2, true, 'in', 0, 1, true),
      ('Gabriel', 'Alava', 2, true, 'in', 1, 0, false),
      ('José', 'Blanco', 2, true, 'in', 0, 0, false),
      ('Jose', 'Cerf', 2, true, 'in', 1, 0, false),
      ('Jesus', 'David', 2, true, 'in', 1, 0, false),
      ('Luis', 'de la Rosa', 2, true, 'in', 0, 1, true),
      ('Nicky', 'Diaz', 2, true, 'in', 2, 0, false),
      ('Michael', 'Enriquez', 2, true, 'in', 0, 0, false),
      ('Efrain', 'Jauregui', 2, true, 'in', 0, 1, false),
      ('Guillermo', 'Lenz', 2, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 2, true, 'in', 0, 0, false),
      ('Luis', 'Marroquin', 2, true, 'in', 0, 0, false),
      ('Eder', 'Martinez', 2, true, 'in', 1, 0, false),
      ('Luis Enrique', 'Martinez', 2, true, 'in', 0, 0, false),
      ('Gerardo', 'Mendizabal', 2, true, 'in', 1, 0, false),
      ('Alex', 'Meneses', 2, true, 'in', 0, 0, false),
      ('Gustavo', 'Moreno-Ortiz', 2, true, 'in', 0, 0, false),
      ('Victor', 'Nizama', 2, true, 'in', 0, 0, false),
      ('José', 'Núñez', 2, true, 'in', 0, 0, false),
      ('Jhonatan', 'Ochoa', 2, true, 'in', 0, 1, true),
      ('Alexis', 'Player', 2, true, 'in', 0, 0, false),
      ('Cevallos', 'Player', 2, true, 'in', 0, 0, false),
      ('Fabian', 'Player', 2, true, 'in', 0, 1, false),
      ('Gus', 'Player', 2, true, 'in', 0, 0, false),
      ('Ruben', 'Player', 2, true, 'in', 0, 0, false),
      ('Sergio', 'Player', 2, true, 'in', 3, 0, false),
      ('Uriel', 'Player', 2, true, 'in', 0, 0, false),
      ('Valverde', 'Player', 2, true, 'in', 0, 0, false),
      ('Oscar', 'Rosales', 2, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 2, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 2, true, 'in', 0, 0, false),
      ('Jordan', 'Toledo', 2, true, 'in', 1, 0, false),
      ('Rodolfo', 'Toledo', 2, true, 'in', 0, 1, false),
      ('David', 'Toro', 2, true, 'in', 0, 0, false),
      ('Luis', 'Urueta', 2, true, 'in', 0, 0, false),
      ('Asdruval', 'Villanueva', 2, true, 'in', 0, 0, false),
      ('Andres', 'Aguayo', 3, true, 'in', 2, 0, false),
      ('Gabriel', 'Alava', 3, true, 'in', 2, 0, false),
      ('José', 'Blanco', 3, true, 'in', 0, 0, false),
      ('Jose', 'Cerf', 3, true, 'in', 1, 0, false),
      ('Pablo', 'Crespin', 3, true, 'in', 0, 0, false),
      ('Jesus', 'David', 3, true, 'in', 2, 0, false),
      ('Luis', 'de la Rosa', 3, true, 'in', 0, 0, false),
      ('Nicky', 'Diaz', 3, true, 'in', 1, 0, false),
      ('Michael', 'Enriquez', 3, true, 'in', 1, 0, false),
      ('Efrain', 'Jauregui', 3, true, 'in', 0, 0, false),
      ('Guillermo', 'Lenz', 3, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 3, true, 'in', 0, 0, false),
      ('Eder', 'Martinez', 3, true, 'in', 0, 0, false),
      ('Rodrigo', 'Mena', 3, true, 'in', 0, 1, false),
      ('Gerardo', 'Mendizabal', 3, true, 'in', 3, 0, false),
      ('Alex', 'Meneses', 3, true, 'in', 2, 0, false),
      ('Gustavo', 'Moreno-Ortiz', 3, true, 'in', 0, 0, false),
      ('Victor', 'Nizama', 3, true, 'in', 0, 0, false),
      ('José', 'Núñez', 3, true, 'in', 0, 0, false),
      ('Jhonatan', 'Ochoa', 3, true, 'in', 0, 0, false),
      ('Alexis', 'Player', 3, true, 'in', 0, 0, false),
      ('Fabian', 'Player', 3, true, 'in', 0, 0, false),
      ('Karter', 'Player', 3, true, 'in', 0, 0, false),
      ('Kevin', 'Player', 3, true, 'in', 0, 1, true),
      ('Miguel', 'Player', 3, true, 'in', 0, 0, false),
      ('Mike', 'Player', 3, true, 'in', 0, 1, true),
      ('Rob', 'Player', 3, true, 'in', 0, 1, false),
      ('Ruben', 'Player', 3, true, 'in', 1, 0, false),
      ('Sergio', 'Player', 3, true, 'in', 1, 0, false),
      ('Uriel', 'Player', 3, true, 'in', 0, 0, false),
      ('Rudy', 'Ramirez', 3, true, 'in', 1, 0, false),
      ('Oscar', 'Rosales', 3, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 3, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 3, true, 'in', 0, 0, false),
      ('Jordan', 'Toledo', 3, true, 'in', 0, 0, false),
      ('Rodolfo', 'Toledo', 3, true, 'in', 0, 1, true),
      ('David', 'Toro', 3, true, 'in', 0, 0, false),
      ('Fernando', 'Urbano', 3, true, 'in', 0, 0, false),
      ('Luis', 'Urueta', 3, true, 'in', 0, 0, false),
      ('Crisanto', 'Valencia', 3, true, 'in', 2, 0, false),
      ('Asdruval', 'Villanueva', 3, true, 'in', 0, 0, false),
      ('Walter', 'Acero', 4, true, 'in', 0, 0, false),
      ('Andres', 'Aguayo', 4, true, 'in', 0, 0, false),
      ('Gabriel', 'Alava', 4, true, 'in', 0, 0, false),
      ('José', 'Blanco', 4, true, 'in', 1, 0, false),
      ('Jose', 'Cerf', 4, true, 'in', 1, 0, false),
      ('Jesus', 'David', 4, true, 'in', 1, 0, false),
      ('Nicky', 'Diaz', 4, true, 'in', 3, 0, false),
      ('Michael', 'Enriquez', 4, true, 'in', 3, 0, false),
      ('Efrain', 'Jauregui', 4, true, 'in', 0, 0, false),
      ('Guillermo', 'Lenz', 4, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 4, true, 'in', 0, 0, false),
      ('Luis Enrique', 'Martinez', 4, true, 'in', 0, 0, false),
      ('Rodrigo', 'Mena', 4, true, 'in', 0, 0, false),
      ('Gerardo', 'Mendizabal', 4, true, 'in', 0, 0, false),
      ('Alex', 'Meneses', 4, true, 'in', 0, 0, false),
      ('Gustavo', 'Moreno-Ortiz', 4, true, 'in', 0, 0, false),
      ('Victor', 'Nizama', 4, true, 'in', 0, 0, false),
      ('José', 'Núñez', 4, true, 'in', 0, 0, false),
      ('Alexis', 'Player', 4, true, 'in', 0, 0, false),
      ('Cevallos', 'Player', 4, true, 'in', 0, 0, false),
      ('Fabian', 'Player', 4, true, 'in', 0, 0, false),
      ('Gus', 'Player', 4, true, 'in', 0, 0, false),
      ('Kevin', 'Player', 4, true, 'in', 0, 1, false),
      ('Miguel', 'Player', 4, true, 'in', 0, 0, false),
      ('Mike', 'Player', 4, true, 'in', 0, 1, false),
      ('Ramón', 'Player', 4, true, 'in', 0, 0, false),
      ('Rob', 'Player', 4, true, 'in', 0, 0, false),
      ('Ruben', 'Player', 4, true, 'in', 1, 0, false),
      ('Uriel', 'Player', 4, true, 'in', 0, 0, false),
      ('Valverde', 'Player', 4, true, 'in', 0, 0, false),
      ('Rudy', 'Ramirez', 4, true, 'in', 1, 0, false),
      ('Oscar', 'Rosales', 4, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 4, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 4, true, 'in', 0, 0, false),
      ('Jordan', 'Toledo', 4, true, 'in', 0, 1, true),
      ('Rodolfo', 'Toledo', 4, true, 'in', 0, 0, false),
      ('David', 'Toro', 4, true, 'in', 0, 0, false),
      ('Luis', 'Urueta', 4, true, 'in', 0, 0, false),
      ('Asdruval', 'Villanueva', 4, true, 'in', 0, 0, false),
      ('Walter', 'Acero', 5, true, 'in', 0, 0, false),
      ('Andres', 'Aguayo', 5, true, 'in', 0, 0, false),
      ('Gabriel', 'Alava', 5, true, 'in', 1, 0, false),
      ('Jose', 'Cerf', 5, true, 'in', 0, 0, false),
      ('Pablo', 'Crespin', 5, true, 'in', 0, 0, false),
      ('Jesus', 'David', 5, true, 'in', 4, 0, false),
      ('Nicky', 'Diaz', 5, true, 'in', 0, 0, false),
      ('Michael', 'Enriquez', 5, true, 'in', 1, 0, false),
      ('Efrain', 'Jauregui', 5, true, 'in', 0, 0, false),
      ('Guillermo', 'Lenz', 5, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 5, true, 'in', 0, 0, false),
      ('Luis', 'Marroquin', 5, true, 'in', 0, 0, false),
      ('Eder', 'Martinez', 5, true, 'in', 4, 0, true),
      ('Gerardo', 'Mendizabal', 5, true, 'in', 0, 0, false),
      ('Alex', 'Meneses', 5, true, 'in', 1, 0, false),
      ('Gustavo', 'Moreno-Ortiz', 5, true, 'in', 0, 0, false),
      ('Joseph', 'Muro', 5, true, 'in', 0, 0, false),
      ('Victor', 'Nizama', 5, true, 'in', 0, 0, false),
      ('José', 'Núñez', 5, true, 'in', 0, 0, false),
      ('Alexis', 'Player', 5, true, 'in', 0, 0, false),
      ('Fabian', 'Player', 5, true, 'in', 0, 0, false),
      ('Gus', 'Player', 5, true, 'in', 0, 0, false),
      ('Miguel', 'Player', 5, true, 'in', 0, 0, false),
      ('Rob', 'Player', 5, true, 'in', 0, 0, false),
      ('Ruben', 'Player', 5, true, 'in', 0, 0, false),
      ('Saul', 'Player', 5, true, 'in', 0, 0, false),
      ('Uriel', 'Player', 5, true, 'in', 0, 0, false),
      ('Rudy', 'Ramirez', 5, true, 'in', 0, 0, false),
      ('Oscar', 'Rosales', 5, true, 'in', 0, 0, false),
      ('Jhony', 'Sanchez', 5, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 5, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 5, true, 'in', 1, 0, false),
      ('Jordan', 'Toledo', 5, true, 'in', 0, 0, false),
      ('Rodolfo', 'Toledo', 5, true, 'in', 0, 1, true),
      ('Luis', 'Urueta', 5, true, 'in', 0, 0, false),
      ('Asdruval', 'Villanueva', 5, true, 'in', 0, 0, false),
      ('Andres', 'Aguayo', 6, true, 'in', 0, 1, true),
      ('Gabriel', 'Alava', 6, true, 'in', 2, 0, false),
      ('Jose', 'Cerf', 6, true, 'in', 1, 0, false),
      ('Pablo', 'Crespin', 6, true, 'in', 0, 0, false),
      ('Jesus', 'David', 6, true, 'in', 3, 0, false),
      ('Nicky', 'Diaz', 6, true, 'in', 1, 0, false),
      ('Michael', 'Enriquez', 6, true, 'in', 1, 0, false),
      ('Efrain', 'Jauregui', 6, true, 'in', 0, 0, false),
      ('Min', 'Kim', 6, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 6, true, 'in', 0, 0, false),
      ('Eder', 'Martinez', 6, true, 'in', 0, 0, false),
      ('Luis Enrique', 'Martinez', 6, true, 'in', 0, 0, false),
      ('Rodrigo', 'Mena', 6, true, 'in', 0, 0, false),
      ('Gerardo', 'Mendizabal', 6, true, 'in', 0, 0, false),
      ('Alex', 'Meneses', 6, true, 'in', 1, 0, false),
      ('Joseph', 'Muro', 6, true, 'in', 0, 0, false),
      ('Victor', 'Nizama', 6, true, 'in', 0, 1, false),
      ('José', 'Núñez', 6, true, 'in', 0, 0, false),
      ('Alexis', 'Player', 6, true, 'in', 0, 0, false),
      ('Cevallos', 'Player', 6, true, 'in', 0, 0, false),
      ('Fabian', 'Player', 6, true, 'in', 0, 0, false),
      ('Gus', 'Player', 6, true, 'in', 0, 0, false),
      ('Karter', 'Player', 6, true, 'in', 0, 0, false),
      ('Rob', 'Player', 6, true, 'in', 0, 0, false),
      ('Ruben', 'Player', 6, true, 'in', 3, 0, false),
      ('Valverde', 'Player', 6, true, 'in', 0, 0, false),
      ('Rudy', 'Ramirez', 6, true, 'in', 0, 0, false),
      ('Jhony', 'Sanchez', 6, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 6, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 6, true, 'in', 3, 0, false),
      ('Rodolfo', 'Toledo', 6, true, 'in', 0, 0, false),
      ('David', 'Toro', 6, true, 'in', 1, 0, false),
      ('Fernando', 'Urbano', 6, true, 'in', 0, 0, false),
      ('Luis', 'Urueta', 6, true, 'in', 0, 0, false),
      ('Crisanto', 'Valencia', 6, true, 'in', 0, 0, false),
      ('Asdruval', 'Villanueva', 6, true, 'in', 1, 0, false),
      ('Walter', 'Acero', 7, true, 'in', 0, 0, false),
      ('Gabriel', 'Alava', 7, true, 'in', 0, 0, false),
      ('José', 'Blanco', 7, true, 'in', 1, 0, false),
      ('Jose', 'Cerf', 7, true, 'in', 1, 0, false),
      ('Jesus', 'David', 7, true, 'in', 0, 0, false),
      ('Nicky', 'Diaz', 7, true, 'in', 0, 0, false),
      ('Michael', 'Enriquez', 7, true, 'in', 0, 0, false),
      ('Efrain', 'Jauregui', 7, true, 'in', 0, 0, false),
      ('Min', 'Kim', 7, true, 'in', 0, 0, false),
      ('Guillermo', 'Lenz', 7, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 7, true, 'in', 0, 0, false),
      ('Luis Enrique', 'Martinez', 7, true, 'in', 0, 0, false),
      ('Alex', 'Meneses', 7, true, 'in', 0, 0, false),
      ('Gustavo', 'Moreno-Ortiz', 7, true, 'in', 0, 0, false),
      ('Joseph', 'Muro', 7, true, 'in', 0, 0, false),
      ('Victor', 'Nizama', 7, true, 'in', 0, 0, false),
      ('Alexis', 'Player', 7, true, 'in', 0, 0, false),
      ('Cevallos', 'Player', 7, true, 'in', 0, 0, false),
      ('Fabian', 'Player', 7, true, 'in', 0, 0, false),
      ('Gus', 'Player', 7, true, 'in', 0, 0, false),
      ('Karter', 'Player', 7, true, 'in', 0, 0, false),
      ('Kevin', 'Player', 7, true, 'in', 0, 1, false),
      ('Miguel', 'Player', 7, true, 'in', 2, 0, false),
      ('Mike', 'Player', 7, true, 'in', 0, 1, false),
      ('Osmin', 'Player', 7, true, 'in', 0, 0, false),
      ('Ruben', 'Player', 7, true, 'in', 1, 0, false),
      ('Sergio', 'Player', 7, true, 'in', 0, 0, false),
      ('Uriel', 'Player', 7, true, 'in', 0, 0, false),
      ('Valverde', 'Player', 7, true, 'in', 0, 0, false),
      ('Rudy', 'Ramirez', 7, true, 'in', 0, 0, false),
      ('Oscar', 'Rosales', 7, true, 'in', 0, 0, false),
      ('Jhony', 'Sanchez', 7, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 7, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 7, true, 'in', 0, 0, false),
      ('Jordan', 'Toledo', 7, true, 'in', 0, 0, false),
      ('Rodolfo', 'Toledo', 7, true, 'in', 0, 1, true),
      ('Fernando', 'Urbano', 7, true, 'in', 0, 0, false),
      ('Luis', 'Urueta', 7, true, 'in', 0, 0, false),
      ('Crisanto', 'Valencia', 7, true, 'in', 0, 0, false),
      ('Asdruval', 'Villanueva', 7, true, 'in', 0, 0, false),
      ('Walter', 'Acero', 8, true, 'in', 0, 0, false),
      ('Andres', 'Aguayo', 8, true, 'in', 4, 0, false),
      ('Gabriel', 'Alava', 8, true, 'in', 1, 0, false),
      ('José', 'Blanco', 8, true, 'in', 0, 0, true),
      ('Jose', 'Cerf', 8, true, 'in', 0, 0, false),
      ('Jesus', 'David', 8, true, 'in', 0, 0, false),
      ('Michael', 'Enriquez', 8, true, 'in', 0, 0, false),
      ('Efrain', 'Jauregui', 8, true, 'in', 0, 0, false),
      ('Min', 'Kim', 8, true, 'in', 0, 0, false),
      ('Cesar', 'Lopez', 8, true, 'in', 0, 0, false),
      ('Eder', 'Martinez', 8, true, 'in', 0, 0, false),
      ('Luis Enrique', 'Martinez', 8, true, 'in', 0, 0, false),
      ('Rodrigo', 'Mena', 8, true, 'in', 0, 0, false),
      ('Alex', 'Meneses', 8, true, 'in', 0, 0, false),
      ('Gustavo', 'Moreno-Ortiz', 8, true, 'in', 0, 0, false),
      ('Victor', 'Nizama', 8, true, 'in', 0, 1, false),
      ('José', 'Núñez', 8, true, 'in', 0, 0, false),
      ('Alexis', 'Player', 8, true, 'in', 0, 0, false),
      ('Fabian', 'Player', 8, true, 'in', 0, 0, false),
      ('Kevin', 'Player', 8, true, 'in', 0, 1, false),
      ('Miguel', 'Player', 8, true, 'in', 1, 0, false),
      ('Mike', 'Player', 8, true, 'in', 0, 1, false),
      ('Osmin', 'Player', 8, true, 'in', 0, 0, false),
      ('Ruben', 'Player', 8, true, 'in', 0, 0, false),
      ('Sergio', 'Player', 8, true, 'in', 2, 0, false),
      ('Uriel', 'Player', 8, true, 'in', 0, 0, false),
      ('Valverde', 'Player', 8, true, 'in', 1, 0, false),
      ('Rudy', 'Ramirez', 8, true, 'in', 0, 0, false),
      ('Jose', 'Sarza', 8, true, 'in', 0, 0, false),
      ('Carlos', 'Silva', 8, true, 'in', 0, 0, false),
      ('Jordan', 'Toledo', 8, true, 'in', 0, 0, false),
      ('Rodolfo', 'Toledo', 8, true, 'in', 0, 0, false),
      ('David', 'Toro', 8, true, 'in', 0, 0, false),
      ('Fernando', 'Urbano', 8, true, 'in', 0, 0, false),
      ('Luis', 'Urueta', 8, true, 'in', 0, 1, false),
      ('Crisanto', 'Valencia', 8, true, 'in', 0, 0, false),
      ('Asdruval', 'Villanueva', 8, true, 'in', 0, 0, false)
  ) as seed(first_name, last_name, matchday_number, attended, attendance_status, goals, goal_keeps, clean_sheet)
)
insert into public.matchday_player_stats (
  matchday_id,
  player_id,
  attended,
  attendance_status,
  goals,
  goal_keeps,
  clean_sheet
)
select
  matchday_lookup.id,
  p.id,
  stat_seed.attended,
  stat_seed.attendance_status,
  stat_seed.goals,
  stat_seed.goal_keeps,
  stat_seed.clean_sheet
from stat_seed
join public.players p
  on lower(trim(p.first_name)) = lower(trim(stat_seed.first_name))
 and lower(trim(p.last_name)) = lower(trim(stat_seed.last_name))
join matchday_lookup
  on matchday_lookup.matchday_number = stat_seed.matchday_number;

commit;

select
  exists (select 1 from public.seasons where lower(trim(name)) = lower('2026 Spring')) as season_2026_spring_ready;
