-- Incremental upgrade: player-facing stat + rating submission foundation.
-- Run this on existing projects after sql/01_schema.sql and any prior upgrades.

begin;

alter table public.matchdays
  add column if not exists player_stats_open_at timestamptz,
  add column if not exists player_stats_close_at timestamptz,
  add column if not exists player_ratings_close_at timestamptz,
  add column if not exists admin_review_locked_at timestamptz;

create or replace function public.set_matchday_submission_windows()
returns trigger
language plpgsql
as $$
begin
  if new.kickoff_at is null then
    return new;
  end if;

  if new.player_stats_open_at is null then
    new.player_stats_open_at = new.kickoff_at + interval '1 hour';
  end if;

  if new.player_stats_close_at is null then
    new.player_stats_close_at = new.kickoff_at + interval '13 hours';
  end if;

  if new.player_ratings_close_at is null then
    new.player_ratings_close_at = new.kickoff_at + interval '7 days';
  end if;

  return new;
end;
$$;

drop trigger if exists matchdays_set_submission_windows on public.matchdays;

create trigger matchdays_set_submission_windows
before insert or update of kickoff_at, player_stats_open_at, player_stats_close_at, player_ratings_close_at
on public.matchdays
for each row
execute procedure public.set_matchday_submission_windows();

update public.matchdays
set
  player_stats_open_at = coalesce(player_stats_open_at, kickoff_at + interval '1 hour'),
  player_stats_close_at = coalesce(player_stats_close_at, kickoff_at + interval '13 hours'),
  player_ratings_close_at = coalesce(player_ratings_close_at, kickoff_at + interval '7 days')
where kickoff_at is not null;

create table if not exists public.matchday_stat_submissions (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  submitted_by_player_id bigint not null references public.players(id) on delete cascade,
  player_id bigint not null references public.players(id) on delete cascade,
  attendance_status text not null default 'in',
  goals integer not null default 0,
  goal_keeps integer not null default 0,
  clean_sheet boolean not null default false,
  note text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_stat_submissions_nonnegative check (
    goals >= 0 and goal_keeps >= 0
  ),
  constraint matchday_stat_submissions_attendance_allowed check (
    attendance_status in ('out', 'in', 'attended', 'available', 'late_cancel', 'no_show')
  ),
  constraint matchday_stat_submissions_note_length check (
    note is null or char_length(trim(note)) <= 400
  )
);

create unique index if not exists matchday_stat_submissions_unique_idx
on public.matchday_stat_submissions (matchday_id, submitted_by_player_id, player_id);

create index if not exists matchday_stat_submissions_matchday_idx
on public.matchday_stat_submissions (matchday_id, player_id);

drop trigger if exists matchday_stat_submissions_set_updated_at on public.matchday_stat_submissions;

create trigger matchday_stat_submissions_set_updated_at
before update on public.matchday_stat_submissions
for each row
execute procedure public.set_updated_at();

alter table public.matchday_stat_submissions enable row level security;

drop policy if exists "Anyone can read matchday stat submissions" on public.matchday_stat_submissions;
create policy "Anyone can read matchday stat submissions"
on public.matchday_stat_submissions
for select
to anon
using (true);

drop policy if exists "Anyone can add matchday stat submissions" on public.matchday_stat_submissions;
create policy "Anyone can add matchday stat submissions"
on public.matchday_stat_submissions
for insert
to anon
with check (true);

drop policy if exists "Anyone can update matchday stat submissions" on public.matchday_stat_submissions;
create policy "Anyone can update matchday stat submissions"
on public.matchday_stat_submissions
for update
to anon
using (true)
with check (true);

create table if not exists public.matchday_player_ratings (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  rater_player_id bigint not null references public.players(id) on delete cascade,
  ratee_player_id bigint not null references public.players(id) on delete cascade,
  relationship text not null,
  scores jsonb not null default '{}'::jsonb,
  comment text,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_player_ratings_relationship_allowed check (
    relationship in ('teammate', 'opponent')
  ),
  constraint matchday_player_ratings_not_self check (
    rater_player_id <> ratee_player_id
  ),
  constraint matchday_player_ratings_scores_object check (
    jsonb_typeof(scores) = 'object'
  ),
  constraint matchday_player_ratings_comment_length check (
    comment is null or char_length(trim(comment)) <= 400
  )
);

create unique index if not exists matchday_player_ratings_unique_idx
on public.matchday_player_ratings (matchday_id, rater_player_id, ratee_player_id);

create index if not exists matchday_player_ratings_matchday_idx
on public.matchday_player_ratings (matchday_id, relationship);

drop trigger if exists matchday_player_ratings_set_updated_at on public.matchday_player_ratings;

create trigger matchday_player_ratings_set_updated_at
before update on public.matchday_player_ratings
for each row
execute procedure public.set_updated_at();

alter table public.matchday_player_ratings enable row level security;

drop policy if exists "Anyone can read matchday player ratings" on public.matchday_player_ratings;
create policy "Anyone can read matchday player ratings"
on public.matchday_player_ratings
for select
to anon
using (true);

drop policy if exists "Anyone can add matchday player ratings" on public.matchday_player_ratings;
create policy "Anyone can add matchday player ratings"
on public.matchday_player_ratings
for insert
to anon
with check (true);

drop policy if exists "Anyone can update matchday player ratings" on public.matchday_player_ratings;
create policy "Anyone can update matchday player ratings"
on public.matchday_player_ratings
for update
to anon
using (true)
with check (true);

commit;
