-- Incremental upgrade: matchday suggestion threads with replies and likes.
-- Run this after sql/06_player_submission_foundation.sql on existing projects.

begin;

create or replace function public.enforce_matchday_suggestion_author_on_roster()
returns trigger
language plpgsql
as $$
declare
  roster_exists boolean;
begin
  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = new.matchday_id
      and sp.player_id = new.author_player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster for matchday %s before saving matchday_suggestions.',
        new.author_player_id,
        new.matchday_id
      ),
      detail = format('matchday_id=%s, author_player_id=%s', new.matchday_id, new.author_player_id),
      hint = 'Add the player to season_players for the matchday season, then retry.';
  end if;

  return new;
end;
$$;

create table if not exists public.matchday_suggestions (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  author_player_id bigint not null references public.players(id) on delete cascade,
  title text not null,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_suggestions_title_length check (
    char_length(trim(title)) between 3 and 120
  ),
  constraint matchday_suggestions_body_length check (
    char_length(trim(body)) between 1 and 1200
  )
);

create index if not exists matchday_suggestions_matchday_idx
on public.matchday_suggestions (matchday_id, created_at desc);

create index if not exists matchday_suggestions_author_idx
on public.matchday_suggestions (author_player_id, created_at desc);

drop trigger if exists matchday_suggestions_set_updated_at on public.matchday_suggestions;

create trigger matchday_suggestions_set_updated_at
before update on public.matchday_suggestions
for each row
execute procedure public.set_updated_at();

drop trigger if exists matchday_suggestions_require_season_roster on public.matchday_suggestions;

create constraint trigger matchday_suggestions_require_season_roster
after insert or update of matchday_id, author_player_id on public.matchday_suggestions
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_suggestion_author_on_roster();

alter table public.matchday_suggestions enable row level security;

drop policy if exists "Anyone can read matchday suggestions" on public.matchday_suggestions;
create policy "Anyone can read matchday suggestions"
on public.matchday_suggestions
for select
to anon
using (true);

drop policy if exists "Anyone can add matchday suggestions" on public.matchday_suggestions;
create policy "Anyone can add matchday suggestions"
on public.matchday_suggestions
for insert
to anon
with check (true);

create or replace function public.enforce_matchday_suggestion_reply_author_on_roster()
returns trigger
language plpgsql
as $$
declare
  target_matchday_id bigint;
  roster_exists boolean;
begin
  select suggestion.matchday_id
  into target_matchday_id
  from public.matchday_suggestions suggestion
  where suggestion.id = new.suggestion_id;

  if target_matchday_id is null then
    raise exception using
      errcode = '23503',
      message = format(
        'Suggestion %s must exist before saving matchday_suggestion_replies.',
        new.suggestion_id
      ),
      detail = format('suggestion_id=%s', new.suggestion_id);
  end if;

  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = target_matchday_id
      and sp.player_id = new.author_player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster for suggestion %s before saving matchday_suggestion_replies.',
        new.author_player_id,
        new.suggestion_id
      ),
      detail = format('suggestion_id=%s, author_player_id=%s', new.suggestion_id, new.author_player_id),
      hint = 'Add the player to season_players for the related matchday season, then retry.';
  end if;

  return new;
end;
$$;

create table if not exists public.matchday_suggestion_replies (
  id bigint generated by default as identity primary key,
  suggestion_id bigint not null references public.matchday_suggestions(id) on delete cascade,
  author_player_id bigint not null references public.players(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_suggestion_replies_body_length check (
    char_length(trim(body)) between 1 and 600
  )
);

create index if not exists matchday_suggestion_replies_suggestion_idx
on public.matchday_suggestion_replies (suggestion_id, created_at asc);

create index if not exists matchday_suggestion_replies_author_idx
on public.matchday_suggestion_replies (author_player_id, created_at desc);

drop trigger if exists matchday_suggestion_replies_set_updated_at on public.matchday_suggestion_replies;

create trigger matchday_suggestion_replies_set_updated_at
before update on public.matchday_suggestion_replies
for each row
execute procedure public.set_updated_at();

drop trigger if exists matchday_suggestion_replies_require_season_roster on public.matchday_suggestion_replies;

create constraint trigger matchday_suggestion_replies_require_season_roster
after insert or update of suggestion_id, author_player_id on public.matchday_suggestion_replies
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_suggestion_reply_author_on_roster();

alter table public.matchday_suggestion_replies enable row level security;

drop policy if exists "Anyone can read matchday suggestion replies" on public.matchday_suggestion_replies;
create policy "Anyone can read matchday suggestion replies"
on public.matchday_suggestion_replies
for select
to anon
using (true);

drop policy if exists "Anyone can add matchday suggestion replies" on public.matchday_suggestion_replies;
create policy "Anyone can add matchday suggestion replies"
on public.matchday_suggestion_replies
for insert
to anon
with check (true);

create or replace function public.enforce_matchday_suggestion_like_player_on_roster()
returns trigger
language plpgsql
as $$
declare
  target_matchday_id bigint;
  roster_exists boolean;
begin
  if new.suggestion_id is not null then
    select suggestion.matchday_id
    into target_matchday_id
    from public.matchday_suggestions suggestion
    where suggestion.id = new.suggestion_id;
  else
    select suggestion.matchday_id
    into target_matchday_id
    from public.matchday_suggestion_replies reply
    join public.matchday_suggestions suggestion
      on suggestion.id = reply.suggestion_id
    where reply.id = new.suggestion_reply_id;
  end if;

  if target_matchday_id is null then
    raise exception using
      errcode = '23503',
      message = 'A valid suggestion target is required before saving matchday_suggestion_likes.';
  end if;

  select exists (
    select 1
    from public.matchdays md
    join public.season_players sp
      on sp.season_id = md.season_id
    where md.id = target_matchday_id
      and sp.player_id = new.liked_by_player_id
  )
  into roster_exists;

  if not roster_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must belong to the season roster before saving matchday_suggestion_likes.',
        new.liked_by_player_id
      ),
      detail = format(
        'suggestion_id=%s, suggestion_reply_id=%s, liked_by_player_id=%s',
        new.suggestion_id,
        new.suggestion_reply_id,
        new.liked_by_player_id
      ),
      hint = 'Add the player to season_players for the related matchday season, then retry.';
  end if;

  return new;
end;
$$;

create table if not exists public.matchday_suggestion_likes (
  id bigint generated by default as identity primary key,
  suggestion_id bigint references public.matchday_suggestions(id) on delete cascade,
  suggestion_reply_id bigint references public.matchday_suggestion_replies(id) on delete cascade,
  liked_by_player_id bigint not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint matchday_suggestion_likes_target_check check (
    (suggestion_id is not null and suggestion_reply_id is null)
    or (suggestion_id is null and suggestion_reply_id is not null)
  )
);

create unique index if not exists matchday_suggestion_likes_suggestion_unique_idx
on public.matchday_suggestion_likes (suggestion_id, liked_by_player_id)
where suggestion_id is not null;

create unique index if not exists matchday_suggestion_likes_reply_unique_idx
on public.matchday_suggestion_likes (suggestion_reply_id, liked_by_player_id)
where suggestion_reply_id is not null;

create index if not exists matchday_suggestion_likes_suggestion_idx
on public.matchday_suggestion_likes (suggestion_id, created_at desc)
where suggestion_id is not null;

create index if not exists matchday_suggestion_likes_reply_idx
on public.matchday_suggestion_likes (suggestion_reply_id, created_at desc)
where suggestion_reply_id is not null;

create index if not exists matchday_suggestion_likes_player_idx
on public.matchday_suggestion_likes (liked_by_player_id, created_at desc);

drop trigger if exists matchday_suggestion_likes_require_season_roster on public.matchday_suggestion_likes;

create constraint trigger matchday_suggestion_likes_require_season_roster
after insert or update of suggestion_id, suggestion_reply_id, liked_by_player_id on public.matchday_suggestion_likes
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_suggestion_like_player_on_roster();

alter table public.matchday_suggestion_likes enable row level security;

drop policy if exists "Anyone can read matchday suggestion likes" on public.matchday_suggestion_likes;
create policy "Anyone can read matchday suggestion likes"
on public.matchday_suggestion_likes
for select
to anon
using (true);

drop policy if exists "Anyone can add matchday suggestion likes" on public.matchday_suggestion_likes;
create policy "Anyone can add matchday suggestion likes"
on public.matchday_suggestion_likes
for insert
to anon
with check (true);

drop policy if exists "Anyone can delete matchday suggestion likes" on public.matchday_suggestion_likes;
create policy "Anyone can delete matchday suggestion likes"
on public.matchday_suggestion_likes
for delete
to anon
using (true);

commit;
