-- Incremental upgrade: public season roster requests with admin approval.
-- Run this after sql/07_matchday_suggestions.sql on existing projects.

begin;

create table if not exists public.season_roster_requests (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  player_id bigint references public.players(id) on delete set null,
  request_type text not null default 'directory',
  requester_name text not null,
  requester_contact text,
  first_name text not null,
  last_name text not null,
  nickname text,
  nationality text not null,
  preferred_positions text[] not null default array['MID']::text[],
  requested_tier text not null default 'rotation',
  note text,
  status text not null default 'pending',
  review_note text,
  approved_player_id bigint references public.players(id) on delete set null,
  approved_season_player_id bigint references public.season_players(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint season_roster_requests_type_allowed check (
    request_type in ('directory', 'new_directory')
  ),
  constraint season_roster_requests_requester_name_length check (
    char_length(trim(requester_name)) between 2 and 80
  ),
  constraint season_roster_requests_contact_length check (
    requester_contact is null or char_length(trim(requester_contact)) between 3 and 120
  ),
  constraint season_roster_requests_first_name_length check (
    char_length(trim(first_name)) between 2 and 40
  ),
  constraint season_roster_requests_last_name_length check (
    char_length(trim(last_name)) between 1 and 40
  ),
  constraint season_roster_requests_nickname_length check (
    nickname is null or char_length(trim(nickname)) between 1 and 50
  ),
  constraint season_roster_requests_nationality_length check (
    char_length(trim(nationality)) between 2 and 50
  ),
  constraint season_roster_requests_positions_allowed check (
    cardinality(preferred_positions) between 1 and 3
    and preferred_positions <@ array['GK', 'DEF', 'MID', 'ATT']::text[]
  ),
  constraint season_roster_requests_requested_tier_allowed check (
    requested_tier in ('core', 'rotation', 'flex_sub')
  ),
  constraint season_roster_requests_status_allowed check (
    status in ('pending', 'approved', 'denied')
  ),
  constraint season_roster_requests_note_length check (
    note is null or char_length(trim(note)) <= 240
  ),
  constraint season_roster_requests_review_note_length check (
    review_note is null or char_length(trim(review_note)) <= 240
  )
);

create index if not exists season_roster_requests_season_status_idx
on public.season_roster_requests (season_id, status, created_at desc);

create index if not exists season_roster_requests_player_status_idx
on public.season_roster_requests (player_id, status, created_at desc);

create unique index if not exists season_roster_requests_pending_player_idx
on public.season_roster_requests (season_id, player_id)
where status = 'pending' and player_id is not null;

drop trigger if exists season_roster_requests_set_updated_at on public.season_roster_requests;

create trigger season_roster_requests_set_updated_at
before update on public.season_roster_requests
for each row
execute procedure public.set_updated_at();

alter table public.season_roster_requests enable row level security;

drop policy if exists "Anyone can read season roster requests" on public.season_roster_requests;
create policy "Anyone can read season roster requests"
on public.season_roster_requests
for select
to anon
using (true);

drop policy if exists "Anyone can add season roster requests" on public.season_roster_requests;
create policy "Anyone can add season roster requests"
on public.season_roster_requests
for insert
to anon
with check (true);

drop policy if exists "Anyone can update season roster requests" on public.season_roster_requests;
create policy "Anyone can update season roster requests"
on public.season_roster_requests
for update
to anon
using (true)
with check (true);

commit;
