-- Incremental upgrade: real Busses admin auth plus canonical write protection.
-- Run this after the existing schema/migrations on a live project.

begin;

create table if not exists public.player_accounts (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  player_id bigint references public.players(id) on delete set null,
  role text not null default 'player',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint player_accounts_role_allowed check (role in ('player', 'admin'))
);

create index if not exists player_accounts_player_idx
on public.player_accounts (player_id)
where player_id is not null;

drop trigger if exists player_accounts_set_updated_at on public.player_accounts;
create trigger player_accounts_set_updated_at
before update on public.player_accounts
for each row
execute procedure public.set_updated_at();

alter table public.player_accounts enable row level security;

drop policy if exists "Users can read their own player account" on public.player_accounts;
create policy "Users can read their own player account"
on public.player_accounts
for select
to authenticated
using (auth.uid() = auth_user_id);

revoke all on public.player_accounts from anon;
revoke all on public.player_accounts from authenticated;
grant select on public.player_accounts to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.player_accounts
    where auth_user_id = auth.uid()
      and role = 'admin'
      and is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "Anyone can read players" on public.players;
drop policy if exists "Anyone can add players" on public.players;
drop policy if exists "Anyone can update players" on public.players;
drop policy if exists "Anyone can delete players" on public.players;
drop policy if exists "Admins can add players" on public.players;
drop policy if exists "Admins can update players" on public.players;
drop policy if exists "Admins can delete players" on public.players;

create policy "Anyone can read players"
on public.players
for select
to anon, authenticated
using (true);

create policy "Admins can add players"
on public.players
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update players"
on public.players
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete players"
on public.players
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read seasons" on public.seasons;
drop policy if exists "Anyone can add seasons" on public.seasons;
drop policy if exists "Anyone can update seasons" on public.seasons;
drop policy if exists "Admins can add seasons" on public.seasons;
drop policy if exists "Admins can update seasons" on public.seasons;
drop policy if exists "Admins can delete seasons" on public.seasons;

create policy "Anyone can read seasons"
on public.seasons
for select
to anon, authenticated
using (true);

create policy "Admins can add seasons"
on public.seasons
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update seasons"
on public.seasons
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete seasons"
on public.seasons
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read season players" on public.season_players;
drop policy if exists "Anyone can add season players" on public.season_players;
drop policy if exists "Anyone can update season players" on public.season_players;
drop policy if exists "Anyone can delete season players" on public.season_players;
drop policy if exists "Admins can add season players" on public.season_players;
drop policy if exists "Admins can update season players" on public.season_players;
drop policy if exists "Admins can delete season players" on public.season_players;

create policy "Anyone can read season players"
on public.season_players
for select
to anon, authenticated
using (true);

create policy "Admins can add season players"
on public.season_players
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update season players"
on public.season_players
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete season players"
on public.season_players
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read season roster requests" on public.season_roster_requests;
drop policy if exists "Anyone can add season roster requests" on public.season_roster_requests;
drop policy if exists "Anyone can update season roster requests" on public.season_roster_requests;
drop policy if exists "Admins can update season roster requests" on public.season_roster_requests;
drop policy if exists "Admins can delete season roster requests" on public.season_roster_requests;

create policy "Anyone can read season roster requests"
on public.season_roster_requests
for select
to anon, authenticated
using (true);

create policy "Anyone can add season roster requests"
on public.season_roster_requests
for insert
to anon, authenticated
with check (true);

create policy "Admins can update season roster requests"
on public.season_roster_requests
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete season roster requests"
on public.season_roster_requests
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchdays" on public.matchdays;
drop policy if exists "Anyone can add matchdays" on public.matchdays;
drop policy if exists "Anyone can update matchdays" on public.matchdays;
drop policy if exists "Admins can add matchdays" on public.matchdays;
drop policy if exists "Admins can update matchdays" on public.matchdays;
drop policy if exists "Admins can delete matchdays" on public.matchdays;

create policy "Anyone can read matchdays"
on public.matchdays
for select
to anon, authenticated
using (true);

create policy "Admins can add matchdays"
on public.matchdays
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchdays"
on public.matchdays
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchdays"
on public.matchdays
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchday matches" on public.matchday_matches;
drop policy if exists "Anyone can add matchday matches" on public.matchday_matches;
drop policy if exists "Anyone can update matchday matches" on public.matchday_matches;
drop policy if exists "Anyone can delete matchday matches" on public.matchday_matches;
drop policy if exists "Admins can add matchday matches" on public.matchday_matches;
drop policy if exists "Admins can update matchday matches" on public.matchday_matches;
drop policy if exists "Admins can delete matchday matches" on public.matchday_matches;

create policy "Anyone can read matchday matches"
on public.matchday_matches
for select
to anon, authenticated
using (true);

create policy "Admins can add matchday matches"
on public.matchday_matches
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchday matches"
on public.matchday_matches
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchday matches"
on public.matchday_matches
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchday player stats" on public.matchday_player_stats;
drop policy if exists "Anyone can add matchday player stats" on public.matchday_player_stats;
drop policy if exists "Anyone can update matchday player stats" on public.matchday_player_stats;
drop policy if exists "Anyone can delete matchday player stats" on public.matchday_player_stats;
drop policy if exists "Admins can add matchday player stats" on public.matchday_player_stats;
drop policy if exists "Admins can update matchday player stats" on public.matchday_player_stats;
drop policy if exists "Admins can delete matchday player stats" on public.matchday_player_stats;

create policy "Anyone can read matchday player stats"
on public.matchday_player_stats
for select
to anon, authenticated
using (true);

create policy "Admins can add matchday player stats"
on public.matchday_player_stats
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchday player stats"
on public.matchday_player_stats
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchday player stats"
on public.matchday_player_stats
for delete
to authenticated
using (public.is_admin());

drop policy if exists "Anyone can read matchday assignments" on public.matchday_assignments;
drop policy if exists "Anyone can add matchday assignments" on public.matchday_assignments;
drop policy if exists "Anyone can update matchday assignments" on public.matchday_assignments;
drop policy if exists "Anyone can delete matchday assignments" on public.matchday_assignments;
drop policy if exists "Admins can add matchday assignments" on public.matchday_assignments;
drop policy if exists "Admins can update matchday assignments" on public.matchday_assignments;
drop policy if exists "Admins can delete matchday assignments" on public.matchday_assignments;

create policy "Anyone can read matchday assignments"
on public.matchday_assignments
for select
to anon, authenticated
using (true);

create policy "Admins can add matchday assignments"
on public.matchday_assignments
for insert
to authenticated
with check (public.is_admin());

create policy "Admins can update matchday assignments"
on public.matchday_assignments
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can delete matchday assignments"
on public.matchday_assignments
for delete
to authenticated
using (public.is_admin());

do $$
begin
  if to_regclass('public.matchday_team_captains') is not null then
    drop policy if exists "Anyone can read matchday team captains" on public.matchday_team_captains;
    drop policy if exists "Anyone can add matchday team captains" on public.matchday_team_captains;
    drop policy if exists "Anyone can update matchday team captains" on public.matchday_team_captains;
    drop policy if exists "Anyone can delete matchday team captains" on public.matchday_team_captains;
    drop policy if exists "Admins can add matchday team captains" on public.matchday_team_captains;
    drop policy if exists "Admins can update matchday team captains" on public.matchday_team_captains;
    drop policy if exists "Admins can delete matchday team captains" on public.matchday_team_captains;

    create policy "Anyone can read matchday team captains"
    on public.matchday_team_captains
    for select
    to anon, authenticated
    using (true);

    create policy "Admins can add matchday team captains"
    on public.matchday_team_captains
    for insert
    to authenticated
    with check (public.is_admin());

    create policy "Admins can update matchday team captains"
    on public.matchday_team_captains
    for update
    to authenticated
    using (public.is_admin())
    with check (public.is_admin());

    create policy "Admins can delete matchday team captains"
    on public.matchday_team_captains
    for delete
    to authenticated
    using (public.is_admin());
  end if;
end
$$;

commit;
