-- STEP 11: Matchday captain tracking.
-- Run this after sql/07_matchday_suggestions.sql on existing projects.

begin;

create or replace function public.enforce_matchday_team_captain_eligibility()
returns trigger
language plpgsql
as $$
declare
  target_season_id bigint;
  current_tier_status text;
  assignment_exists boolean;
begin
  select md.season_id
  into target_season_id
  from public.matchdays md
  where md.id = new.matchday_id;

  if target_season_id is null then
    raise exception using
      errcode = '23503',
      message = format(
        'Matchday %s must exist before saving matchday_team_captains.',
        new.matchday_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s',
        new.matchday_id,
        new.team_code,
        new.player_id
      );
  end if;

  select lower(coalesce(sp.tier_status, ''))
  into current_tier_status
  from public.season_players sp
  where sp.season_id = target_season_id
    and sp.player_id = new.player_id
  limit 1;

  if current_tier_status not in ('core', 'flex') then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must be core or flex before saving a captain row for matchday %s.',
        new.player_id,
        new.matchday_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s, tier_status=%s',
        new.matchday_id,
        new.team_code,
        new.player_id,
        coalesce(current_tier_status, '<missing>')
      ),
      hint = 'Choose a core or flex player from the same season roster.';
  end if;

  if lower(coalesce(new.captain_tier, '')) <> current_tier_status then
    raise exception using
      errcode = '23514',
      message = format(
        'Captain tier %s does not match the current season tier %s for player %s.',
        coalesce(new.captain_tier, '<missing>'),
        current_tier_status,
        new.player_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s',
        new.matchday_id,
        new.team_code,
        new.player_id
      ),
      hint = 'Save the captain row with the player''s current core/flex season tier.';
  end if;

  select exists (
    select 1
    from public.matchday_assignments ma
    where ma.matchday_id = new.matchday_id
      and ma.player_id = new.player_id
      and ma.team_code = new.team_code
  )
  into assignment_exists;

  if not assignment_exists then
    raise exception using
      errcode = '23514',
      message = format(
        'Player %s must be assigned to team %s on matchday %s before saving a captain row.',
        new.player_id,
        new.team_code,
        new.matchday_id
      ),
      detail = format(
        'matchday_id=%s, team_code=%s, player_id=%s',
        new.matchday_id,
        new.team_code,
        new.player_id
      ),
      hint = 'Assign the player to that team first, then save the captain selection.';
  end if;

  return new;
end;
$$;

create table if not exists public.matchday_team_captains (
  id bigint generated by default as identity primary key,
  matchday_id bigint not null references public.matchdays(id) on delete cascade,
  team_code text not null,
  player_id bigint not null references public.players(id) on delete cascade,
  captain_tier text not null default 'flex',
  selection_method text not null default 'auto',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.matchday_team_captains
  add column if not exists captain_tier text,
  add column if not exists selection_method text,
  add column if not exists updated_at timestamptz not null default now();

update public.matchday_team_captains mtc
set captain_tier = lower(coalesce(sp.tier_status, 'flex'))
from public.matchdays md,
     public.season_players sp
where md.id = mtc.matchday_id
  and sp.season_id = md.season_id
  and sp.player_id = mtc.player_id
  and (
    mtc.captain_tier is null
    or lower(coalesce(mtc.captain_tier, '')) not in ('core', 'flex')
  );

update public.matchday_team_captains
set selection_method = 'auto'
where selection_method is null
   or lower(coalesce(selection_method, '')) not in ('auto', 'replacement', 'manual');

alter table public.matchday_team_captains
  alter column captain_tier set default 'flex',
  alter column captain_tier set not null,
  alter column selection_method set default 'auto',
  alter column selection_method set not null,
  alter column updated_at set default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'matchday_team_captains_team_code_allowed'
  ) then
    alter table public.matchday_team_captains
      add constraint matchday_team_captains_team_code_allowed check (
        team_code in ('magenta', 'blue', 'green', 'orange')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'matchday_team_captains_captain_tier_allowed'
  ) then
    alter table public.matchday_team_captains
      add constraint matchday_team_captains_captain_tier_allowed check (
        captain_tier in ('core', 'flex')
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'matchday_team_captains_selection_method_allowed'
  ) then
    alter table public.matchday_team_captains
      add constraint matchday_team_captains_selection_method_allowed check (
        selection_method in ('auto', 'replacement', 'manual')
      );
  end if;
end;
$$;

create unique index if not exists matchday_team_captains_matchday_team_idx
on public.matchday_team_captains (matchday_id, team_code);

create unique index if not exists matchday_team_captains_matchday_player_idx
on public.matchday_team_captains (matchday_id, player_id);

create index if not exists matchday_team_captains_player_idx
on public.matchday_team_captains (player_id, created_at desc);

drop trigger if exists matchday_team_captains_set_updated_at on public.matchday_team_captains;

create trigger matchday_team_captains_set_updated_at
before update on public.matchday_team_captains
for each row
execute procedure public.set_updated_at();

drop trigger if exists matchday_team_captains_require_assignment on public.matchday_team_captains;

create constraint trigger matchday_team_captains_require_assignment
after insert or update of matchday_id, team_code, player_id, captain_tier on public.matchday_team_captains
deferrable initially deferred
for each row
execute procedure public.enforce_matchday_team_captain_eligibility();

alter table public.matchday_team_captains enable row level security;

drop policy if exists "Anyone can read matchday team captains" on public.matchday_team_captains;
drop policy if exists "Anyone can add matchday team captains" on public.matchday_team_captains;
drop policy if exists "Anyone can update matchday team captains" on public.matchday_team_captains;
drop policy if exists "Anyone can delete matchday team captains" on public.matchday_team_captains;
drop policy if exists "Admins can add matchday team captains" on public.matchday_team_captains;
drop policy if exists "Admins can update matchday team captains" on public.matchday_team_captains;
drop policy if exists "Admins can delete matchday team captains" on public.matchday_team_captains;

do $$
begin
  create policy "Anyone can read matchday team captains"
  on public.matchday_team_captains
  for select
  to anon, authenticated
  using (true);

  if to_regprocedure('public.is_admin()') is not null then
    create policy "Admins can add matchday team captains"
    on public.matchday_team_captains
    for insert
    to authenticated
    with check (public.is_admin());

    create policy "Admins can update matchday team captains"
    on public.matchday_team_captains
    for update
    to authenticated
    using (public.is_admin())
    with check (public.is_admin());

    create policy "Admins can delete matchday team captains"
    on public.matchday_team_captains
    for delete
    to authenticated
    using (public.is_admin());
  else
    create policy "Anyone can add matchday team captains"
    on public.matchday_team_captains
    for insert
    to anon
    with check (true);

    create policy "Anyone can update matchday team captains"
    on public.matchday_team_captains
    for update
    to anon
    using (true)
    with check (true);

    create policy "Anyone can delete matchday team captains"
    on public.matchday_team_captains
    for delete
    to anon
    using (true);
  end if;
end
$$;

commit;
