-- Incremental upgrade: swap Busses admin auth to magic-link email allowlist.
-- Run this after the existing auth/RLS migrations on a live project.

begin;

create table if not exists public.admin_allowed_emails (
  id bigint generated by default as identity primary key,
  email text not null,
  note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_allowed_emails_email_present check (char_length(trim(email)) > 3)
);

create unique index if not exists admin_allowed_emails_email_key
on public.admin_allowed_emails ((lower(trim(email))));

drop trigger if exists admin_allowed_emails_set_updated_at on public.admin_allowed_emails;
create trigger admin_allowed_emails_set_updated_at
before update on public.admin_allowed_emails
for each row
execute procedure public.set_updated_at();

alter table public.admin_allowed_emails enable row level security;

revoke all on public.admin_allowed_emails from anon;
revoke all on public.admin_allowed_emails from authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_allowed_emails
    where lower(trim(email)) = lower(trim(coalesce(auth.jwt() ->> 'email', '')))
      and is_active = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

commit;
