-- Seed generated from the 2026 Spring source workbook.
-- Run this AFTER supabase_setup.sql or supabase_setup_part1.sql + supabase_setup_part2.sql.
-- If Supabase SQL Editor shows `relation "a" does not exist`, switch the results mode
-- from `Limit 100` to `No limit`, then rerun the script.
-- Source tabs used:
-- 1. MATCH_DATES
-- 2. WEEKLY_TEAMS
-- 3. MATCH_INPUT
-- 4. PLAYER_STAT
-- 5. UPDATING SOCCER APP - PLAYERS.csv
-- Rules applied:
-- 1. The season is stored as "2026 Spring".
-- 2. Kickoff times default to 12:00 PM America/Los_Angeles and can be edited later in the UI.
-- 3. Names with "/" are treated as buddy pairs and seeded as rotation players.
-- 4. Labels starting with "(Sub)" are treated as flex/sub players.
-- 5. Blank scores mean the match has not been played yet, so scores stay null.
-- 6. Running this seed replaces only the "2026 Spring" season data.
-- 7. Matching player rows are refreshed in place, and missing players are inserted.

begin;

delete from public.seasons
where lower(trim(name)) = lower('2026 Spring');

with player_seed as (
  select *
  from (
    values
      ('Walter', 'Acero', 'Walter Acero', 'Unknown', array['MID', 'DEF', 'GK']::text[], 'core', 'core'),
      ('Jeff', 'Arce', 'Jeff Arce', 'Costa Rica', array['ATT', 'MID', 'GK']::text[], 'core', 'core'),
      ('José', 'Blanco', 'José Blanco', 'Mexico', array['ATT', 'DEF', 'GK']::text[], 'core', 'core'),
      ('Min', 'Kim', 'Min Kim', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Joseph', 'M.', 'Joseph M.', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Luis', 'Marroquin', 'Luis Marroquin', 'Mexico', array['MID']::text[], 'core', 'core'),
      ('Alex', 'Player', 'Alex', 'Peru', array['MID', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Alexis', 'Player', 'Alexis', 'Mexico', array['MID']::text[], 'core', 'core'),
      ('Andrés', 'Player', 'Andrés', 'Ecuador', array['DEF', 'ATT', 'ATT']::text[], 'core', 'core'),
      ('Asdruval', 'Player', 'Asdruval', 'Mexico', array['DEF', 'ATT', 'GK']::text[], 'core', 'core'),
      ('Carlos', 'Player', 'Carlos S', 'Peru', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Cevallos', 'Player', 'Cevallos', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Chato', 'Player', 'Chato', 'Chile', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Chavito', 'Player', 'Chavito', 'Mexico', array['DEF', 'MID', 'GK']::text[], 'rotation', 'rotation'),
      ('Coti', 'Player', 'Coti', 'Peru', array['DEF', 'GK', 'DEF']::text[], 'core', 'core'),
      ('Cuñis', 'Player', 'Cuñis', 'Mexico', array['DEF', 'ATT', 'GK']::text[], 'core', 'core'),
      ('David', 'Player', 'David', 'Ecuador', array['MID', 'MID', 'MID']::text[], 'core', 'core'),
      ('Eder', 'Player', 'Eder', 'Mexico', array['MID', 'ATT', 'GK']::text[], 'core', 'core'),
      ('Efra', 'Player', 'Efra', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Efraín', 'Player', 'Efraín', 'Mexico', array['DEF', 'MID', 'DEF']::text[], 'rotation', 'rotation'),
      ('Fabián', 'Player', 'Fabián', 'Mexico', array['GK', 'DEF', 'MID']::text[], 'rotation', 'rotation'),
      ('Fer', 'Player', 'Fer', 'Mexico', array['GK', 'GK', 'GK']::text[], 'core', 'core'),
      ('Gabo', 'Player', 'Gabo', 'Ecuador', array['DEF', 'MID', 'DEF']::text[], 'core', 'core'),
      ('Gerardo', 'Player', 'Gerardo', 'Mexico', array['MID', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Guille', 'Player', 'Guille', 'Bolivia', array['DEF', 'MID', 'ATT']::text[], 'core', 'core'),
      ('Gus', 'Player', 'Gus', 'El Salvador', array['ATT', 'DEF', 'MID']::text[], 'core', 'core'),
      ('Gustavo', 'Player', 'Gustavo', 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Javier', 'Player', 'Javier', 'Mexico', array['ATT', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Jesús', 'Player', 'Jesús', 'Unknown', array['MID', 'ATT', 'ATT']::text[], 'core', 'core'),
      ('Jhony', 'Player', 'Jhony', 'Mexico', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Jordan', 'Player', 'Jordan', 'Mexico', array['DEF', 'MID', 'ATT']::text[], 'core', 'core'),
      ('Karter', 'Player', 'Karter', 'USA', array['MID']::text[], 'core', 'core'),
      ('Kevin', 'Player', 'Kevin', 'El Salvador', array['ATT', 'DEF', 'MID']::text[], 'rotation', 'rotation'),
      ('López', 'Player', 'López', 'Mexico', array['DEF', 'GK', 'DEF']::text[], 'rotation', 'rotation'),
      ('Miguel', 'Player', 'Miguel A', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Mike', 'Player', 'Mike', 'El Salvador', array['DEF', 'GK', 'MID']::text[], 'rotation', 'rotation'),
      ('Mikey', 'Player', 'Mikey', 'Mexico', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Nicky', 'Player', 'Nicky', 'Peru', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Nizama', 'Player', 'Nizama', 'Peru', array['DEF', 'GK', 'ATT']::text[], 'core', 'core'),
      ('Núñez', 'Player', 'Núñez', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Osmin', 'Player', 'Osmin', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Pablo', 'Player', 'Pablo', 'Chile', array['MID']::text[], 'core', 'core'),
      ('Pirlo', 'Player', 'Pirlo', 'El Salvador', array['MID', 'MID', 'MID']::text[], 'core', 'core'),
      ('Ramón', 'Player', 'Ramón', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rob', 'Player', 'Rob', 'El Salvador', array['DEF', 'GK', 'DEF']::text[], 'core', 'core'),
      ('Rodolfo', 'Player', 'Rodolfo', 'Mexico', array['GK', 'DEF', 'MID']::text[], 'core', 'core'),
      ('Rodrigo', 'Player', 'Rodrigo', 'Nicaragua', array['MID', 'DEF', 'GK']::text[], 'core', 'core'),
      ('Rubén', 'Player', 'Rubén', 'Peru', array['ATT', 'MID', 'DEF']::text[], 'core', 'core'),
      ('Rudy', 'Player', 'Rudy', 'Unknown', array['MID', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Saul', 'Player', 'Saul', 'Ecuador', array['MID']::text[], 'core', 'core'),
      ('Sergio', 'Player', 'Sergio', 'Chile', array['ATT', 'MID', 'DEF']::text[], 'core', 'core'),
      ('Uriel', 'Player', 'Uriel', 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Valencia', 'Player', 'Valencia', 'Mexico', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Valverde', 'Player', 'Valverde', 'Mexico', array['ATT', 'MID', 'ATT']::text[], 'core', 'core'),
      ('José', 'Sarza', 'José Sarza', 'Mexico', array['DEF', 'DEF', 'DEF']::text[], 'core', 'core')
  ) as seed(first_name, last_name, nickname, nationality, positions, desired_tier, status)
)
update public.players p
set
  nickname = player_seed.nickname,
  nationality = player_seed.nationality,
  positions = player_seed.positions,
  desired_tier = player_seed.desired_tier,
  status = player_seed.status
from player_seed
where lower(trim(p.first_name)) = lower(trim(player_seed.first_name))
  and lower(trim(p.last_name)) = lower(trim(player_seed.last_name));

with player_seed as (
  select *
  from (
    values
      ('Walter', 'Acero', 'Walter Acero', 'Unknown', array['MID', 'DEF', 'GK']::text[], 'core', 'core'),
      ('Jeff', 'Arce', 'Jeff Arce', 'Costa Rica', array['ATT', 'MID', 'GK']::text[], 'core', 'core'),
      ('José', 'Blanco', 'José Blanco', 'Mexico', array['ATT', 'DEF', 'GK']::text[], 'core', 'core'),
      ('Min', 'Kim', 'Min Kim', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Joseph', 'M.', 'Joseph M.', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Luis', 'Marroquin', 'Luis Marroquin', 'Mexico', array['MID']::text[], 'core', 'core'),
      ('Alex', 'Player', 'Alex', 'Peru', array['MID', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Alexis', 'Player', 'Alexis', 'Mexico', array['MID']::text[], 'core', 'core'),
      ('Andrés', 'Player', 'Andrés', 'Ecuador', array['DEF', 'ATT', 'ATT']::text[], 'core', 'core'),
      ('Asdruval', 'Player', 'Asdruval', 'Mexico', array['DEF', 'ATT', 'GK']::text[], 'core', 'core'),
      ('Carlos', 'Player', 'Carlos S', 'Peru', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Cevallos', 'Player', 'Cevallos', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Chato', 'Player', 'Chato', 'Chile', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Chavito', 'Player', 'Chavito', 'Mexico', array['DEF', 'MID', 'GK']::text[], 'rotation', 'rotation'),
      ('Coti', 'Player', 'Coti', 'Peru', array['DEF', 'GK', 'DEF']::text[], 'core', 'core'),
      ('Cuñis', 'Player', 'Cuñis', 'Mexico', array['DEF', 'ATT', 'GK']::text[], 'core', 'core'),
      ('David', 'Player', 'David', 'Ecuador', array['MID', 'MID', 'MID']::text[], 'core', 'core'),
      ('Eder', 'Player', 'Eder', 'Mexico', array['MID', 'ATT', 'GK']::text[], 'core', 'core'),
      ('Efra', 'Player', 'Efra', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Efraín', 'Player', 'Efraín', 'Mexico', array['DEF', 'MID', 'DEF']::text[], 'rotation', 'rotation'),
      ('Fabián', 'Player', 'Fabián', 'Mexico', array['GK', 'DEF', 'MID']::text[], 'rotation', 'rotation'),
      ('Fer', 'Player', 'Fer', 'Mexico', array['GK', 'GK', 'GK']::text[], 'core', 'core'),
      ('Gabo', 'Player', 'Gabo', 'Ecuador', array['DEF', 'MID', 'DEF']::text[], 'core', 'core'),
      ('Gerardo', 'Player', 'Gerardo', 'Mexico', array['MID', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Guille', 'Player', 'Guille', 'Bolivia', array['DEF', 'MID', 'ATT']::text[], 'core', 'core'),
      ('Gus', 'Player', 'Gus', 'El Salvador', array['ATT', 'DEF', 'MID']::text[], 'core', 'core'),
      ('Gustavo', 'Player', 'Gustavo', 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Javier', 'Player', 'Javier', 'Mexico', array['ATT', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Jesús', 'Player', 'Jesús', 'Unknown', array['MID', 'ATT', 'ATT']::text[], 'core', 'core'),
      ('Jhony', 'Player', 'Jhony', 'Mexico', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Jordan', 'Player', 'Jordan', 'Mexico', array['DEF', 'MID', 'ATT']::text[], 'core', 'core'),
      ('Karter', 'Player', 'Karter', 'USA', array['MID']::text[], 'core', 'core'),
      ('Kevin', 'Player', 'Kevin', 'El Salvador', array['ATT', 'DEF', 'MID']::text[], 'rotation', 'rotation'),
      ('López', 'Player', 'López', 'Mexico', array['DEF', 'GK', 'DEF']::text[], 'rotation', 'rotation'),
      ('Miguel', 'Player', 'Miguel A', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Mike', 'Player', 'Mike', 'El Salvador', array['DEF', 'GK', 'MID']::text[], 'rotation', 'rotation'),
      ('Mikey', 'Player', 'Mikey', 'Mexico', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Nicky', 'Player', 'Nicky', 'Peru', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Nizama', 'Player', 'Nizama', 'Peru', array['DEF', 'GK', 'ATT']::text[], 'core', 'core'),
      ('Núñez', 'Player', 'Núñez', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Osmin', 'Player', 'Osmin', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Pablo', 'Player', 'Pablo', 'Chile', array['MID']::text[], 'core', 'core'),
      ('Pirlo', 'Player', 'Pirlo', 'El Salvador', array['MID', 'MID', 'MID']::text[], 'core', 'core'),
      ('Ramón', 'Player', 'Ramón', 'Unknown', array['MID']::text[], 'core', 'core'),
      ('Rob', 'Player', 'Rob', 'El Salvador', array['DEF', 'GK', 'DEF']::text[], 'core', 'core'),
      ('Rodolfo', 'Player', 'Rodolfo', 'Mexico', array['GK', 'DEF', 'MID']::text[], 'core', 'core'),
      ('Rodrigo', 'Player', 'Rodrigo', 'Nicaragua', array['MID', 'DEF', 'GK']::text[], 'core', 'core'),
      ('Rubén', 'Player', 'Rubén', 'Peru', array['ATT', 'MID', 'DEF']::text[], 'core', 'core'),
      ('Rudy', 'Player', 'Rudy', 'Unknown', array['MID', 'DEF', 'ATT']::text[], 'core', 'core'),
      ('Saul', 'Player', 'Saul', 'Ecuador', array['MID']::text[], 'core', 'core'),
      ('Sergio', 'Player', 'Sergio', 'Chile', array['ATT', 'MID', 'DEF']::text[], 'core', 'core'),
      ('Uriel', 'Player', 'Uriel', 'Mexico', array['MID']::text[], 'rotation', 'rotation'),
      ('Valencia', 'Player', 'Valencia', 'Mexico', array['MID', 'ATT', 'DEF']::text[], 'core', 'core'),
      ('Valverde', 'Player', 'Valverde', 'Mexico', array['ATT', 'MID', 'ATT']::text[], 'core', 'core'),
      ('José', 'Sarza', 'José Sarza', 'Mexico', array['DEF', 'DEF', 'DEF']::text[], 'core', 'core')
  ) as seed(first_name, last_name, nickname, nationality, positions, desired_tier, status)
)
insert into public.players (
  first_name,
  last_name,
  nickname,
  nationality,
  positions,
  desired_tier,
  status
)
select
  player_seed.first_name,
  player_seed.last_name,
  player_seed.nickname,
  player_seed.nationality,
  player_seed.positions,
  player_seed.desired_tier,
  player_seed.status
from player_seed
where not exists (
  select 1
  from public.players p
  where lower(trim(p.first_name)) = lower(trim(player_seed.first_name))
    and lower(trim(p.last_name)) = lower(trim(player_seed.last_name))
);

insert into public.seasons (
  name,
  total_matchdays,
  core_spots,
  rotation_spots,
  model_start_matchday,
  attendance_points,
  win_points,
  draw_points,
  loss_points,
  goal_keep_points,
  team_goal_points
)
values (
  '2026 Spring',
  8,
  47,
  8,
  1,
  2,
  2,
  1,
  0,
  1,
  1
);

with season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_seed as (
  select *
  from (
    values
      (1, timestamptz '2026-03-05 12:00:00 America/Los_Angeles', false),
      (2, timestamptz '2026-03-12 12:00:00 America/Los_Angeles', false),
      (3, timestamptz '2026-03-19 12:00:00 America/Los_Angeles', false),
      (4, timestamptz '2026-03-26 12:00:00 America/Los_Angeles', false),
      (5, timestamptz '2026-04-02 12:00:00 America/Los_Angeles', true),
      (6, timestamptz '2026-04-09 12:00:00 America/Los_Angeles', true),
      (7, timestamptz '2026-04-16 12:00:00 America/Los_Angeles', true),
      (8, timestamptz '2026-04-23 12:00:00 America/Los_Angeles', true)
  ) as seed(matchday_number, kickoff_at, goals_count_as_points)
)
insert into public.matchdays (season_id, matchday_number, kickoff_at, goals_count_as_points)
select
  season_row.id,
  matchday_seed.matchday_number,
  matchday_seed.kickoff_at,
  matchday_seed.goals_count_as_points
from season_row
cross join matchday_seed;

with season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_lookup as (
  select md.id, md.matchday_number
  from public.matchdays md
  join season_row on season_row.id = md.season_id
),
match_seed as (
  select *
  from (
    values
      (1, 1, 1, 'blue', 'magenta', 0, 3),
      (1, 1, 2, 'orange', 'green', 1, 4),
      (1, 2, 1, 'magenta', 'green', 2, 1),
      (1, 2, 2, 'orange', 'blue', 1, 2),
      (2, 1, 1, 'blue', 'magenta', 3, 2),
      (2, 1, 2, 'green', 'orange', 0, 0),
      (2, 2, 1, 'blue', 'green', 4, 1),
      (2, 2, 2, 'magenta', 'orange', 1, 1),
      (3, 1, 1, 'blue', 'magenta', 5, 0),
      (3, 1, 2, 'orange', 'green', 3, 1),
      (3, 2, 1, 'blue', 'orange', 1, 3),
      (3, 2, 2, 'magenta', 'green', 0, 6),
      (4, 1, 1, 'blue', 'magenta', 1, 3),
      (4, 1, 2, 'green', 'orange', 0, 1),
      (4, 2, 1, 'blue', 'green', 1, 2),
      (4, 2, 2, 'orange', 'magenta', 3, 2),
      (5, 1, 1, 'magenta', 'blue', 7, 1),
      (5, 1, 2, 'green', 'orange', 2, 4),
      (5, 2, 1, 'blue', 'green', 1, 7),
      (5, 2, 2, 'magenta', 'orange', 0, 0),
      (6, 1, 1, 'blue', 'magenta', 2, 0),
      (6, 1, 2, 'green', 'orange', 3, 3),
      (6, 2, 1, 'blue', 'green', 7, 1),
      (6, 2, 2, 'magenta', 'orange', 2, 1),
      (7, 1, 1, 'blue', 'magenta', 0, 0),
      (7, 1, 2, 'green', 'orange', 1, 2),
      (7, 2, 1, 'orange', 'magenta', 0, 0),
      (7, 2, 2, 'green', 'blue', 3, 4),
      (8, 1, 1, null, null, null, null),
      (8, 1, 2, null, null, null, null),
      (8, 2, 1, null, null, null, null),
      (8, 2, 2, null, null, null, null)
  ) as seed(matchday_number, round_number, match_order, home_team_code, away_team_code, home_score, away_score)
)
insert into public.matchday_matches (
  matchday_id,
  round_number,
  match_order,
  home_team_code,
  away_team_code,
  home_score,
  away_score
)
select
  matchday_lookup.id,
  match_seed.round_number,
  match_seed.match_order,
  match_seed.home_team_code,
  match_seed.away_team_code,
  match_seed.home_score,
  match_seed.away_score
from match_seed
join matchday_lookup
  on matchday_lookup.matchday_number = match_seed.matchday_number;

with player_aliases as (
  select *
  from (
    values
      ('ALEX', 'Alex', 'Player'),
      ('ALEXIS', 'Alexis', 'Player'),
      ('ANDRÉS', 'Andrés', 'Player'),
      ('ASDRUVAL', 'Asdruval', 'Player'),
      ('CARLOS S', 'Carlos', 'Player'),
      ('CEVALLOS', 'Cevallos', 'Player'),
      ('CHATO', 'Chato', 'Player'),
      ('CHAVITO', 'Chavito', 'Player'),
      ('COTI', 'Coti', 'Player'),
      ('CUÑIS', 'Cuñis', 'Player'),
      ('DAVID', 'David', 'Player'),
      ('EDER', 'Eder', 'Player'),
      ('EFRA', 'Efra', 'Player'),
      ('EFRAÍN', 'Efraín', 'Player'),
      ('FABIÁN', 'Fabián', 'Player'),
      ('FER', 'Fer', 'Player'),
      ('GABO', 'Gabo', 'Player'),
      ('GERARDO', 'Gerardo', 'Player'),
      ('GUILLE', 'Guille', 'Player'),
      ('GUS', 'Gus', 'Player'),
      ('GUSTAVO', 'Gustavo', 'Player'),
      ('JAVIER', 'Javier', 'Player'),
      ('JEFF ARCE', 'Jeff', 'Arce'),
      ('JESÚS', 'Jesús', 'Player'),
      ('JHONY', 'Jhony', 'Player'),
      ('JORDAN', 'Jordan', 'Player'),
      ('JOSEPH M.', 'Joseph', 'M.'),
      ('JOSÉ BLANCO', 'José', 'Blanco'),
      ('JOSÉ SARZA', 'José', 'Sarza'),
      ('KARTER', 'Karter', 'Player'),
      ('KEVIN', 'Kevin', 'Player'),
      ('LUIS MARROQUIN', 'Luis', 'Marroquin'),
      ('LÓPEZ', 'López', 'Player'),
      ('MIGUEL A', 'Miguel', 'Player'),
      ('MIKE', 'Mike', 'Player'),
      ('MIKEY', 'Mikey', 'Player'),
      ('MIN KIM', 'Min', 'Kim'),
      ('NICKY', 'Nicky', 'Player'),
      ('NIZAMA', 'Nizama', 'Player'),
      ('NÚÑEZ', 'Núñez', 'Player'),
      ('OSMIN', 'Osmin', 'Player'),
      ('PABLO', 'Pablo', 'Player'),
      ('PIRLO', 'Pirlo', 'Player'),
      ('RAMÓN', 'Ramón', 'Player'),
      ('ROB', 'Rob', 'Player'),
      ('RODOLFO', 'Rodolfo', 'Player'),
      ('RODRIGO', 'Rodrigo', 'Player'),
      ('RUBÉN', 'Rubén', 'Player'),
      ('RUDY', 'Rudy', 'Player'),
      ('SAUL', 'Saul', 'Player'),
      ('SERGIO', 'Sergio', 'Player'),
      ('URIEL', 'Uriel', 'Player'),
      ('VALENCIA', 'Valencia', 'Player'),
      ('VALVERDE', 'Valverde', 'Player'),
      ('WALTER ACERO', 'Walter', 'Acero')
  ) as seed(import_label, first_name, last_name)
),
player_lookup as (
  select
    player_aliases.import_label,
    p.id as player_id
  from player_aliases
  join public.players p
    on lower(trim(p.first_name)) = lower(trim(player_aliases.first_name))
   and lower(trim(p.last_name)) = lower(trim(player_aliases.last_name))
),
season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_lookup as (
  select md.id, md.matchday_number
  from public.matchdays md
  join season_row on season_row.id = md.season_id
),
assignment_seed as (
  select *
  from (
    values
      ('KARTER', 1, 'green'),
      ('NÚÑEZ', 1, 'blue'),
      ('PABLO', 1, 'green'),
      ('ROB', 1, 'orange'),
      ('ALEX', 1, 'green'),
      ('ALEXIS', 1, 'blue'),
      ('ANDRÉS', 1, 'magenta'),
      ('ASDRUVAL', 1, 'blue'),
      ('CARLOS S', 1, 'green'),
      ('CEVALLOS', 1, 'orange'),
      ('CHATO', 1, 'magenta'),
      ('DAVID', 1, 'blue'),
      ('EDER', 1, 'orange'),
      ('EFRAÍN', 1, 'magenta'),
      ('GABO', 1, 'green'),
      ('GERARDO', 1, 'magenta'),
      ('GUS', 1, 'green'),
      ('JAVIER', 1, 'magenta'),
      ('JESÚS', 1, 'orange'),
      ('JORDAN', 1, 'magenta'),
      ('JOSÉ BLANCO', 1, 'blue'),
      ('JOSÉ SARZA', 1, 'magenta'),
      ('KEVIN', 1, 'green'),
      ('MIGUEL A', 1, 'blue'),
      ('MIKEY', 1, 'orange'),
      ('NICKY', 1, 'green'),
      ('NIZAMA', 1, 'orange'),
      ('RODOLFO', 1, 'magenta'),
      ('RUBÉN', 1, 'green'),
      ('RUDY', 1, 'magenta'),
      ('SERGIO', 1, 'blue'),
      ('URIEL', 1, 'blue'),
      ('VALENCIA', 1, 'blue'),
      ('VALVERDE', 1, 'orange'),
      ('COTI', 2, 'orange'),
      ('EFRA', 2, 'green'),
      ('GUILLE', 2, 'magenta'),
      ('LUIS MARROQUIN', 2, 'magenta'),
      ('NÚÑEZ', 2, 'magenta'),
      ('ALEX', 2, 'blue'),
      ('LÓPEZ', 2, 'orange'),
      ('ANDRÉS', 2, 'green'),
      ('ASDRUVAL', 2, 'blue'),
      ('CARLOS S', 2, 'orange'),
      ('CEVALLOS', 2, 'magenta'),
      ('CHATO', 2, 'magenta'),
      ('CHAVITO', 2, 'orange'),
      ('CUÑIS', 2, 'green'),
      ('DAVID', 2, 'green'),
      ('EDER', 2, 'green'),
      ('FABIÁN', 2, 'magenta'),
      ('GABO', 2, 'magenta'),
      ('GERARDO', 2, 'blue'),
      ('GUS', 2, 'green'),
      ('JAVIER', 2, 'magenta'),
      ('JESÚS', 2, 'blue'),
      ('JORDAN', 2, 'orange'),
      ('JOSÉ BLANCO', 2, 'green'),
      ('JOSÉ SARZA', 2, 'green'),
      ('MIKEY', 2, 'orange'),
      ('NICKY', 2, 'blue'),
      ('NIZAMA', 2, 'blue'),
      ('PIRLO', 2, 'green'),
      ('RODOLFO', 2, 'blue'),
      ('RUBÉN', 2, 'orange'),
      ('SERGIO', 2, 'blue'),
      ('GUSTAVO', 2, 'orange'),
      ('VALVERDE', 2, 'orange'),
      ('FER', 3, 'magenta'),
      ('GUILLE', 3, 'orange'),
      ('KARTER', 3, 'blue'),
      ('NÚÑEZ', 3, 'magenta'),
      ('PABLO', 3, 'orange'),
      ('ROB', 3, 'magenta'),
      ('ALEX', 3, 'green'),
      ('ALEXIS', 3, 'green'),
      ('ANDRÉS', 3, 'blue'),
      ('ASDRUVAL', 3, 'magenta'),
      ('CARLOS S', 3, 'orange'),
      ('CHATO', 3, 'blue'),
      ('CHAVITO', 3, 'blue'),
      ('DAVID', 3, 'green'),
      ('EDER', 3, 'magenta'),
      ('EFRAÍN', 3, 'blue'),
      ('GABO', 3, 'green'),
      ('GERARDO', 3, 'green'),
      ('JAVIER', 3, 'magenta'),
      ('JESÚS', 3, 'orange'),
      ('JORDAN', 3, 'magenta'),
      ('JOSÉ BLANCO', 3, 'green'),
      ('JOSÉ SARZA', 3, 'orange'),
      ('MIKE', 3, 'blue'),
      ('MIGUEL A', 3, 'magenta'),
      ('MIKEY', 3, 'blue'),
      ('NICKY', 3, 'blue'),
      ('NIZAMA', 3, 'green'),
      ('PIRLO', 3, 'magenta'),
      ('RODOLFO', 3, 'green'),
      ('RODRIGO', 3, 'magenta'),
      ('RUBÉN', 3, 'orange'),
      ('RUDY', 3, 'orange'),
      ('SERGIO', 3, 'blue'),
      ('URIEL', 3, 'green'),
      ('VALENCIA', 3, 'orange'),
      ('GUILLE', 4, 'blue'),
      ('NÚÑEZ', 4, 'magenta'),
      ('ROB', 4, 'blue'),
      ('ALEX', 4, 'orange'),
      ('LÓPEZ', 4, 'magenta'),
      ('ANDRÉS', 4, 'green'),
      ('ASDRUVAL', 4, 'blue'),
      ('CARLOS S', 4, 'magenta'),
      ('CEVALLOS', 4, 'blue'),
      ('CHATO', 4, 'green'),
      ('CUÑIS', 4, 'orange'),
      ('DAVID', 4, 'green'),
      ('FABIÁN', 4, 'green'),
      ('GABO', 4, 'green'),
      ('GERARDO', 4, 'magenta'),
      ('GUS', 4, 'blue'),
      ('JAVIER', 4, 'orange'),
      ('JESÚS', 4, 'green'),
      ('JORDAN', 4, 'orange'),
      ('JOSÉ BLANCO', 4, 'orange'),
      ('JOSÉ SARZA', 4, 'blue'),
      ('KEVIN', 4, 'green'),
      ('MIGUEL A', 4, 'green'),
      ('MIKEY', 4, 'magenta'),
      ('NICKY', 4, 'orange'),
      ('NIZAMA', 4, 'orange'),
      ('PIRLO', 4, 'blue'),
      ('RAMÓN', 4, 'orange'),
      ('RODOLFO', 4, 'magenta'),
      ('RODRIGO', 4, 'magenta'),
      ('RUBÉN', 4, 'magenta'),
      ('RUDY', 4, 'blue'),
      ('GUSTAVO', 4, 'magenta'),
      ('VALVERDE', 4, 'green'),
      ('WALTER ACERO', 4, 'blue'),
      ('GUILLE', 5, 'orange'),
      ('JHONY', 5, 'green'),
      ('JOSEPH M.', 5, 'orange'),
      ('LUIS MARROQUIN', 5, 'green'),
      ('NÚÑEZ', 5, 'orange'),
      ('PABLO', 5, 'green'),
      ('ROB', 5, 'blue'),
      ('SAUL', 5, 'blue'),
      ('ALEX', 5, 'orange'),
      ('ALEXIS', 5, 'orange'),
      ('ANDRÉS', 5, 'blue'),
      ('ASDRUVAL', 5, 'magenta'),
      ('CARLOS S', 5, 'magenta'),
      ('CHATO', 5, 'blue'),
      ('EDER', 5, 'magenta'),
      ('EFRAÍN', 5, 'blue'),
      ('GABO', 5, 'magenta'),
      ('GERARDO', 5, 'blue'),
      ('GUS', 5, 'green'),
      ('JAVIER', 5, 'green'),
      ('JESÚS', 5, 'green'),
      ('JORDAN', 5, 'green'),
      ('JOSÉ SARZA', 5, 'orange'),
      ('MIGUEL A', 5, 'orange'),
      ('MIKEY', 5, 'magenta'),
      ('NICKY', 5, 'orange'),
      ('NIZAMA', 5, 'blue'),
      ('PIRLO', 5, 'green'),
      ('RODOLFO', 5, 'orange'),
      ('RUBÉN', 5, 'blue'),
      ('RUDY', 5, 'magenta'),
      ('URIEL', 5, 'magenta'),
      ('WALTER ACERO', 5, 'blue'),
      ('ALEXIS', 6, 'magenta'),
      ('FER', 6, 'green'),
      ('JHONY', 6, 'orange'),
      ('JOSEPH M.', 6, 'blue'),
      ('KARTER', 6, 'orange'),
      ('MIN KIM', 6, 'orange'),
      ('NÚÑEZ', 6, 'orange'),
      ('PABLO', 6, 'orange'),
      ('ROB', 6, 'green'),
      ('ALEX', 6, 'magenta'),
      ('LÓPEZ', 6, 'magenta'),
      ('ANDRÉS', 6, 'blue'),
      ('ASDRUVAL', 6, 'green'),
      ('CARLOS S', 6, 'blue'),
      ('CEVALLOS', 6, 'magenta'),
      ('CHATO', 6, 'green'),
      ('CUÑIS', 6, 'green'),
      ('DAVID', 6, 'blue'),
      ('EDER', 6, 'magenta'),
      ('FABIÁN', 6, 'blue'),
      ('GABO', 6, 'green'),
      ('GERARDO', 6, 'green'),
      ('GUS', 6, 'orange'),
      ('JAVIER', 6, 'blue'),
      ('JESÚS', 6, 'orange'),
      ('JOSÉ SARZA', 6, 'blue'),
      ('MIKEY', 6, 'orange'),
      ('NICKY', 6, 'magenta'),
      ('NIZAMA', 6, 'orange'),
      ('RODOLFO', 6, 'magenta'),
      ('RODRIGO', 6, 'blue'),
      ('RUBÉN', 6, 'blue'),
      ('RUDY', 6, 'green'),
      ('VALENCIA', 6, 'magenta'),
      ('VALVERDE', 6, 'green'),
      ('FER', 7, 'magenta'),
      ('GUILLE', 7, 'orange'),
      ('JHONY', 7, 'green'),
      ('JOSEPH M.', 7, 'green'),
      ('KARTER', 7, 'magenta'),
      ('MIN KIM', 7, 'magenta'),
      ('OSMIN', 7, 'orange'),
      ('ALEX', 7, 'magenta'),
      ('LÓPEZ', 7, 'green'),
      ('ASDRUVAL', 7, 'green'),
      ('CARLOS S', 7, 'blue'),
      ('CEVALLOS', 7, 'orange'),
      ('CHATO', 7, 'green'),
      ('CUÑIS', 7, 'orange'),
      ('EFRAÍN', 7, 'blue'),
      ('GABO', 7, 'green'),
      ('GUS', 7, 'green'),
      ('JAVIER', 7, 'blue'),
      ('JESÚS', 7, 'orange'),
      ('JORDAN', 7, 'magenta'),
      ('JOSÉ BLANCO', 7, 'blue'),
      ('JOSÉ SARZA', 7, 'orange'),
      ('MIKE', 7, 'blue'),
      ('MIGUEL A', 7, 'blue'),
      ('MIKEY', 7, 'blue'),
      ('NICKY', 7, 'magenta'),
      ('NIZAMA', 7, 'blue'),
      ('PIRLO', 7, 'orange'),
      ('RODOLFO', 7, 'magenta'),
      ('RUBÉN', 7, 'orange'),
      ('RUDY', 7, 'blue'),
      ('SERGIO', 7, 'orange'),
      ('GUSTAVO', 7, 'green'),
      ('VALENCIA', 7, 'green'),
      ('VALVERDE', 7, 'magenta'),
      ('WALTER ACERO', 7, 'magenta')
  ) as seed(import_label, matchday_number, team_code)
)
insert into public.matchday_assignments (matchday_id, player_id, team_code)
select
  matchday_lookup.id,
  player_lookup.player_id,
  assignment_seed.team_code
from assignment_seed
join player_lookup
  on player_lookup.import_label = assignment_seed.import_label
join matchday_lookup
  on matchday_lookup.matchday_number = assignment_seed.matchday_number;

with player_aliases as (
  select *
  from (
    values
      ('ALEX', 'Alex', 'Player'),
      ('ALEXIS', 'Alexis', 'Player'),
      ('ANDRÉS', 'Andrés', 'Player'),
      ('ASDRUVAL', 'Asdruval', 'Player'),
      ('CARLOS S', 'Carlos', 'Player'),
      ('CEVALLOS', 'Cevallos', 'Player'),
      ('CHATO', 'Chato', 'Player'),
      ('CHAVITO', 'Chavito', 'Player'),
      ('COTI', 'Coti', 'Player'),
      ('CUÑIS', 'Cuñis', 'Player'),
      ('DAVID', 'David', 'Player'),
      ('EDER', 'Eder', 'Player'),
      ('EFRA', 'Efra', 'Player'),
      ('EFRAÍN', 'Efraín', 'Player'),
      ('FABIÁN', 'Fabián', 'Player'),
      ('FER', 'Fer', 'Player'),
      ('GABO', 'Gabo', 'Player'),
      ('GERARDO', 'Gerardo', 'Player'),
      ('GUILLE', 'Guille', 'Player'),
      ('GUS', 'Gus', 'Player'),
      ('GUSTAVO', 'Gustavo', 'Player'),
      ('JAVIER', 'Javier', 'Player'),
      ('JEFF ARCE', 'Jeff', 'Arce'),
      ('JESÚS', 'Jesús', 'Player'),
      ('JHONY', 'Jhony', 'Player'),
      ('JORDAN', 'Jordan', 'Player'),
      ('JOSEPH M.', 'Joseph', 'M.'),
      ('JOSÉ BLANCO', 'José', 'Blanco'),
      ('JOSÉ SARZA', 'José', 'Sarza'),
      ('KARTER', 'Karter', 'Player'),
      ('KEVIN', 'Kevin', 'Player'),
      ('LUIS MARROQUIN', 'Luis', 'Marroquin'),
      ('LÓPEZ', 'López', 'Player'),
      ('MIGUEL A', 'Miguel', 'Player'),
      ('MIKE', 'Mike', 'Player'),
      ('MIKEY', 'Mikey', 'Player'),
      ('MIN KIM', 'Min', 'Kim'),
      ('NICKY', 'Nicky', 'Player'),
      ('NIZAMA', 'Nizama', 'Player'),
      ('NÚÑEZ', 'Núñez', 'Player'),
      ('OSMIN', 'Osmin', 'Player'),
      ('PABLO', 'Pablo', 'Player'),
      ('PIRLO', 'Pirlo', 'Player'),
      ('RAMÓN', 'Ramón', 'Player'),
      ('ROB', 'Rob', 'Player'),
      ('RODOLFO', 'Rodolfo', 'Player'),
      ('RODRIGO', 'Rodrigo', 'Player'),
      ('RUBÉN', 'Rubén', 'Player'),
      ('RUDY', 'Rudy', 'Player'),
      ('SAUL', 'Saul', 'Player'),
      ('SERGIO', 'Sergio', 'Player'),
      ('URIEL', 'Uriel', 'Player'),
      ('VALENCIA', 'Valencia', 'Player'),
      ('VALVERDE', 'Valverde', 'Player'),
      ('WALTER ACERO', 'Walter', 'Acero')
  ) as seed(import_label, first_name, last_name)
),
player_lookup as (
  select
    player_aliases.import_label,
    p.id as player_id
  from player_aliases
  join public.players p
    on lower(trim(p.first_name)) = lower(trim(player_aliases.first_name))
   and lower(trim(p.last_name)) = lower(trim(player_aliases.last_name))
),
season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
matchday_lookup as (
  select md.id, md.matchday_number
  from public.matchdays md
  join season_row on season_row.id = md.season_id
),
stat_seed as (
  select *
  from (
    values
      ('ALEX', 1, true, 'in', 2, 0, false),
      ('ALEXIS', 1, true, 'in', 0, 0, false),
      ('ANDRÉS', 1, true, 'in', 1, 0, false),
      ('ASDRUVAL', 1, true, 'in', 0, 0, false),
      ('CARLOS S', 1, true, 'in', 0, 0, false),
      ('CEVALLOS', 1, true, 'in', 0, 1, false),
      ('CHATO', 1, true, 'in', 0, 0, false),
      ('DAVID', 1, true, 'in', 0, 0, false),
      ('EDER', 1, true, 'in', 0, 0, false),
      ('EFRAÍN', 1, true, 'in', 0, 0, false),
      ('GABO', 1, true, 'in', 0, 0, false),
      ('GERARDO', 1, true, 'in', 3, 0, false),
      ('GUS', 1, true, 'in', 0, 0, false),
      ('JAVIER', 1, true, 'in', 0, 0, false),
      ('JESÚS', 1, true, 'in', 1, 0, false),
      ('JORDAN', 1, true, 'in', 1, 0, false),
      ('JOSÉ BLANCO', 1, true, 'in', 1, 0, false),
      ('JOSÉ SARZA', 1, true, 'in', 0, 0, false),
      ('KARTER', 1, true, 'in', 0, 0, false),
      ('KEVIN', 1, true, 'in', 0, 0, false),
      ('MIGUEL A', 1, true, 'in', 0, 0, false),
      ('MIKEY', 1, true, 'in', 0, 0, false),
      ('NICKY', 1, true, 'in', 1, 0, false),
      ('NIZAMA', 1, true, 'in', 0, 0, false),
      ('NÚÑEZ', 1, true, 'in', 0, 0, false),
      ('PABLO', 1, true, 'in', 0, 0, false),
      ('ROB', 1, true, 'in', 0, 1, false),
      ('RODOLFO', 1, true, 'in', 0, 1, true),
      ('RUBÉN', 1, true, 'in', 0, 0, false),
      ('RUDY', 1, true, 'in', 0, 0, false),
      ('SERGIO', 1, true, 'in', 0, 0, false),
      ('URIEL', 1, true, 'in', 0, 1, false),
      ('VALENCIA', 1, true, 'in', 1, 0, false),
      ('VALVERDE', 1, true, 'in', 0, 0, false),
      ('ALEX', 2, true, 'in', 0, 0, false),
      ('ANDRÉS', 2, true, 'in', 0, 1, true),
      ('ASDRUVAL', 2, true, 'in', 0, 0, false),
      ('CARLOS S', 2, true, 'in', 0, 0, false),
      ('CEVALLOS', 2, true, 'in', 0, 0, false),
      ('CHATO', 2, true, 'in', 1, 0, false),
      ('CHAVITO', 2, true, 'in', 0, 1, true),
      ('COTI', 2, true, 'in', 0, 0, false),
      ('CUÑIS', 2, true, 'in', 0, 0, false),
      ('DAVID', 2, true, 'in', 0, 0, false),
      ('EDER', 2, true, 'in', 1, 0, false),
      ('EFRA', 2, true, 'in', 0, 0, false),
      ('FABIÁN', 2, true, 'in', 0, 1, false),
      ('GABO', 2, true, 'in', 1, 0, false),
      ('GERARDO', 2, true, 'in', 1, 0, false),
      ('GUILLE', 2, true, 'in', 0, 0, false),
      ('GUS', 2, true, 'in', 0, 0, false),
      ('GUSTAVO', 2, true, 'in', 0, 0, false),
      ('JAVIER', 2, true, 'in', 0, 0, false),
      ('JESÚS', 2, true, 'in', 1, 0, false),
      ('JORDAN', 2, true, 'in', 1, 0, false),
      ('JOSÉ BLANCO', 2, true, 'in', 0, 0, false),
      ('JOSÉ SARZA', 2, true, 'in', 0, 0, false),
      ('LUIS MARROQUIN', 2, true, 'in', 0, 0, false),
      ('LÓPEZ', 2, true, 'in', 0, 0, false),
      ('MIKEY', 2, true, 'in', 0, 0, false),
      ('NICKY', 2, true, 'in', 2, 0, false),
      ('NIZAMA', 2, true, 'in', 0, 0, false),
      ('NÚÑEZ', 2, true, 'in', 0, 0, false),
      ('PIRLO', 2, true, 'in', 0, 0, false),
      ('RODOLFO', 2, true, 'in', 0, 1, false),
      ('RUBÉN', 2, true, 'in', 0, 0, false),
      ('SERGIO', 2, true, 'in', 3, 0, false),
      ('VALVERDE', 2, true, 'in', 0, 0, false),
      ('ALEX', 3, true, 'in', 2, 0, false),
      ('ALEXIS', 3, true, 'in', 0, 0, false),
      ('ANDRÉS', 3, true, 'in', 2, 0, false),
      ('ASDRUVAL', 3, true, 'in', 0, 0, false),
      ('CARLOS S', 3, true, 'in', 0, 0, false),
      ('CHATO', 3, true, 'in', 1, 0, false),
      ('CHAVITO', 3, true, 'in', 0, 0, false),
      ('DAVID', 3, true, 'in', 0, 0, false),
      ('EDER', 3, true, 'in', 0, 0, false),
      ('EFRAÍN', 3, true, 'in', 0, 0, false),
      ('FER', 3, true, 'in', 0, 0, false),
      ('GABO', 3, true, 'in', 2, 0, false),
      ('GERARDO', 3, true, 'in', 3, 0, false),
      ('GUILLE', 3, true, 'in', 0, 0, false),
      ('JAVIER', 3, true, 'in', 0, 0, false),
      ('JESÚS', 3, true, 'in', 2, 0, false),
      ('JORDAN', 3, true, 'in', 0, 0, false),
      ('JOSÉ BLANCO', 3, true, 'in', 0, 0, false),
      ('JOSÉ SARZA', 3, true, 'in', 0, 0, false),
      ('KARTER', 3, true, 'in', 0, 0, false),
      ('MIGUEL A', 3, true, 'in', 0, 0, false),
      ('MIKE', 3, true, 'in', 0, 1, true),
      ('MIKEY', 3, true, 'in', 1, 0, false),
      ('NICKY', 3, true, 'in', 1, 0, false),
      ('NIZAMA', 3, true, 'in', 0, 0, false),
      ('NÚÑEZ', 3, true, 'in', 0, 0, false),
      ('PABLO', 3, true, 'in', 0, 0, false),
      ('PIRLO', 3, true, 'in', 0, 0, false),
      ('ROB', 3, true, 'in', 0, 1, false),
      ('RODOLFO', 3, true, 'in', 0, 1, true),
      ('RODRIGO', 3, true, 'in', 0, 1, false),
      ('RUBÉN', 3, true, 'in', 1, 0, false),
      ('RUDY', 3, true, 'in', 1, 0, false),
      ('SERGIO', 3, true, 'in', 1, 0, false),
      ('URIEL', 3, true, 'in', 0, 0, false),
      ('VALENCIA', 3, true, 'in', 2, 0, false),
      ('ALEX', 4, true, 'in', 0, 0, false),
      ('ANDRÉS', 4, true, 'in', 0, 0, false),
      ('ASDRUVAL', 4, true, 'in', 0, 0, false),
      ('CARLOS S', 4, true, 'in', 0, 0, false),
      ('CEVALLOS', 4, true, 'in', 0, 0, false),
      ('CHATO', 4, true, 'in', 1, 0, false),
      ('CUÑIS', 4, true, 'in', 0, 0, false),
      ('DAVID', 4, true, 'in', 0, 0, false),
      ('FABIÁN', 4, true, 'in', 0, 0, false),
      ('GABO', 4, true, 'in', 0, 0, false),
      ('GERARDO', 4, true, 'in', 0, 0, false),
      ('GUILLE', 4, true, 'in', 0, 0, false),
      ('GUS', 4, true, 'in', 0, 0, false),
      ('GUSTAVO', 4, true, 'in', 0, 0, false),
      ('JAVIER', 4, true, 'in', 0, 0, false),
      ('JESÚS', 4, true, 'in', 1, 0, false),
      ('JORDAN', 4, true, 'in', 0, 1, true),
      ('JOSÉ BLANCO', 4, true, 'in', 1, 0, false),
      ('JOSÉ SARZA', 4, true, 'in', 0, 0, false),
      ('KEVIN', 4, true, 'in', 0, 1, false),
      ('LÓPEZ', 4, true, 'in', 0, 0, false),
      ('MIGUEL A', 4, true, 'in', 0, 0, false),
      ('MIKEY', 4, true, 'in', 3, 0, false),
      ('NICKY', 4, true, 'in', 3, 0, false),
      ('NIZAMA', 4, true, 'in', 0, 0, false),
      ('NÚÑEZ', 4, true, 'in', 0, 0, false),
      ('PIRLO', 4, true, 'in', 0, 0, false),
      ('RAMÓN', 4, true, 'in', 0, 0, false),
      ('ROB', 4, true, 'in', 0, 0, false),
      ('RODOLFO', 4, true, 'in', 0, 0, false),
      ('RODRIGO', 4, true, 'in', 0, 0, false),
      ('RUBÉN', 4, true, 'in', 1, 0, false),
      ('RUDY', 4, true, 'in', 1, 0, false),
      ('VALVERDE', 4, true, 'in', 0, 0, false),
      ('WALTER ACERO', 4, true, 'in', 0, 0, false),
      ('ALEX', 5, true, 'in', 1, 0, false),
      ('ALEXIS', 5, true, 'in', 0, 0, false),
      ('ANDRÉS', 5, true, 'in', 0, 0, false),
      ('ASDRUVAL', 5, true, 'in', 0, 0, false),
      ('CARLOS S', 5, true, 'in', 1, 0, false),
      ('CHATO', 5, true, 'in', 0, 0, false),
      ('EDER', 5, true, 'in', 4, 0, true),
      ('EFRAÍN', 5, true, 'in', 0, 0, false),
      ('GABO', 5, true, 'in', 1, 0, false),
      ('GERARDO', 5, true, 'in', 0, 0, false),
      ('GUILLE', 5, true, 'in', 0, 0, false),
      ('GUS', 5, true, 'in', 0, 0, false),
      ('JAVIER', 5, true, 'in', 0, 0, false),
      ('JESÚS', 5, true, 'in', 4, 0, false),
      ('JHONY', 5, true, 'in', 0, 0, false),
      ('JORDAN', 5, true, 'in', 0, 0, false),
      ('JOSEPH M.', 5, true, 'in', 0, 0, false),
      ('JOSÉ SARZA', 5, true, 'in', 0, 0, false),
      ('LUIS MARROQUIN', 5, true, 'in', 0, 0, false),
      ('MIGUEL A', 5, true, 'in', 0, 0, false),
      ('MIKEY', 5, true, 'in', 1, 0, false),
      ('NICKY', 5, true, 'in', 0, 0, false),
      ('NIZAMA', 5, true, 'in', 0, 0, false),
      ('NÚÑEZ', 5, true, 'in', 0, 0, false),
      ('PABLO', 5, true, 'in', 0, 0, false),
      ('PIRLO', 5, true, 'in', 0, 0, false),
      ('ROB', 5, true, 'in', 0, 0, false),
      ('RODOLFO', 5, true, 'in', 0, 1, true),
      ('RUBÉN', 5, true, 'in', 0, 0, false),
      ('RUDY', 5, true, 'in', 0, 0, false),
      ('SAUL', 5, true, 'in', 0, 0, false),
      ('URIEL', 5, true, 'in', 0, 0, false),
      ('WALTER ACERO', 5, true, 'in', 0, 0, false),
      ('ALEX', 6, true, 'in', 1, 0, false),
      ('ALEXIS', 6, true, 'in', 0, 0, false),
      ('ANDRÉS', 6, true, 'in', 0, 1, true),
      ('ASDRUVAL', 6, true, 'in', 1, 0, false),
      ('CARLOS S', 6, true, 'in', 3, 0, false),
      ('CEVALLOS', 6, true, 'in', 0, 0, false),
      ('CHATO', 6, true, 'in', 1, 0, false),
      ('CUÑIS', 6, true, 'in', 0, 0, false),
      ('DAVID', 6, true, 'in', 1, 0, false),
      ('EDER', 6, true, 'in', 0, 0, false),
      ('FABIÁN', 6, true, 'in', 0, 0, false),
      ('FER', 6, true, 'in', 0, 0, false),
      ('GABO', 6, true, 'in', 2, 0, false),
      ('GERARDO', 6, true, 'in', 0, 0, false),
      ('GUS', 6, true, 'in', 0, 0, false),
      ('JAVIER', 6, true, 'in', 0, 0, false),
      ('JESÚS', 6, true, 'in', 3, 0, false),
      ('JHONY', 6, true, 'in', 0, 0, false),
      ('JOSEPH M.', 6, true, 'in', 0, 0, false),
      ('JOSÉ SARZA', 6, true, 'in', 0, 0, false),
      ('KARTER', 6, true, 'in', 0, 0, false),
      ('LÓPEZ', 6, true, 'in', 0, 0, false),
      ('MIKEY', 6, true, 'in', 1, 0, false),
      ('MIN KIM', 6, true, 'in', 0, 0, false),
      ('NICKY', 6, true, 'in', 1, 0, false),
      ('NIZAMA', 6, true, 'in', 0, 1, false),
      ('NÚÑEZ', 6, true, 'in', 0, 0, false),
      ('PABLO', 6, true, 'in', 0, 0, false),
      ('ROB', 6, true, 'in', 0, 0, false),
      ('RODOLFO', 6, true, 'in', 0, 0, false),
      ('RODRIGO', 6, true, 'in', 0, 0, false),
      ('RUBÉN', 6, true, 'in', 3, 0, false),
      ('RUDY', 6, true, 'in', 0, 0, false),
      ('VALENCIA', 6, true, 'in', 0, 0, false),
      ('VALVERDE', 6, true, 'in', 0, 0, false),
      ('ALEX', 7, true, 'in', 0, 0, false),
      ('ASDRUVAL', 7, true, 'in', 0, 0, false),
      ('CARLOS S', 7, true, 'in', 0, 0, false),
      ('CEVALLOS', 7, true, 'in', 0, 0, false),
      ('CHATO', 7, true, 'in', 1, 0, false),
      ('CUÑIS', 7, true, 'in', 0, 0, false),
      ('EFRAÍN', 7, true, 'in', 0, 0, false),
      ('FER', 7, true, 'in', 0, 0, false),
      ('GABO', 7, true, 'in', 0, 0, false),
      ('GUILLE', 7, true, 'in', 0, 0, false),
      ('GUS', 7, true, 'in', 0, 0, false),
      ('GUSTAVO', 7, true, 'in', 0, 0, false),
      ('JAVIER', 7, true, 'in', 0, 0, false),
      ('JESÚS', 7, true, 'in', 0, 0, false),
      ('JHONY', 7, true, 'in', 0, 0, false),
      ('JORDAN', 7, true, 'in', 0, 0, false),
      ('JOSEPH M.', 7, true, 'in', 0, 0, false),
      ('JOSÉ BLANCO', 7, true, 'in', 1, 0, false),
      ('JOSÉ SARZA', 7, true, 'in', 0, 0, false),
      ('KARTER', 7, true, 'in', 0, 0, false),
      ('LÓPEZ', 7, true, 'in', 0, 0, false),
      ('MIGUEL A', 7, true, 'in', 2, 0, false),
      ('MIKE', 7, true, 'in', 0, 1, false),
      ('MIKEY', 7, true, 'in', 0, 0, false),
      ('MIN KIM', 7, true, 'in', 0, 0, false),
      ('NICKY', 7, true, 'in', 0, 0, false),
      ('NIZAMA', 7, true, 'in', 0, 0, false),
      ('OSMIN', 7, true, 'in', 0, 0, false),
      ('PIRLO', 7, true, 'in', 0, 0, false),
      ('RODOLFO', 7, true, 'in', 0, 1, true),
      ('RUBÉN', 7, true, 'in', 1, 0, false),
      ('RUDY', 7, true, 'in', 0, 0, false),
      ('SERGIO', 7, true, 'in', 0, 0, false),
      ('VALENCIA', 7, true, 'in', 0, 0, false),
      ('VALVERDE', 7, true, 'in', 0, 0, false),
      ('WALTER ACERO', 7, true, 'in', 0, 0, false)
  ) as seed(import_label, matchday_number, attended, attendance_status, goals, goal_keeps, clean_sheet)
)
insert into public.matchday_player_stats (
  matchday_id,
  player_id,
  attended,
  attendance_status,
  goals,
  goal_keeps,
  clean_sheet
)
select
  matchday_lookup.id,
  player_lookup.player_id,
  stat_seed.attended,
  stat_seed.attendance_status,
  stat_seed.goals,
  stat_seed.goal_keeps,
  stat_seed.clean_sheet
from stat_seed
join player_lookup
  on player_lookup.import_label = stat_seed.import_label
join matchday_lookup
  on matchday_lookup.matchday_number = stat_seed.matchday_number;

with player_aliases as (
  select *
  from (
    values
      ('ALEX', 'Alex', 'Player'),
      ('ALEXIS', 'Alexis', 'Player'),
      ('ANDRÉS', 'Andrés', 'Player'),
      ('ASDRUVAL', 'Asdruval', 'Player'),
      ('CARLOS S', 'Carlos', 'Player'),
      ('CEVALLOS', 'Cevallos', 'Player'),
      ('CHATO', 'Chato', 'Player'),
      ('CHAVITO', 'Chavito', 'Player'),
      ('COTI', 'Coti', 'Player'),
      ('CUÑIS', 'Cuñis', 'Player'),
      ('DAVID', 'David', 'Player'),
      ('EDER', 'Eder', 'Player'),
      ('EFRA', 'Efra', 'Player'),
      ('EFRAÍN', 'Efraín', 'Player'),
      ('FABIÁN', 'Fabián', 'Player'),
      ('FER', 'Fer', 'Player'),
      ('GABO', 'Gabo', 'Player'),
      ('GERARDO', 'Gerardo', 'Player'),
      ('GUILLE', 'Guille', 'Player'),
      ('GUS', 'Gus', 'Player'),
      ('GUSTAVO', 'Gustavo', 'Player'),
      ('JAVIER', 'Javier', 'Player'),
      ('JEFF ARCE', 'Jeff', 'Arce'),
      ('JESÚS', 'Jesús', 'Player'),
      ('JHONY', 'Jhony', 'Player'),
      ('JORDAN', 'Jordan', 'Player'),
      ('JOSEPH M.', 'Joseph', 'M.'),
      ('JOSÉ BLANCO', 'José', 'Blanco'),
      ('JOSÉ SARZA', 'José', 'Sarza'),
      ('KARTER', 'Karter', 'Player'),
      ('KEVIN', 'Kevin', 'Player'),
      ('LUIS MARROQUIN', 'Luis', 'Marroquin'),
      ('LÓPEZ', 'López', 'Player'),
      ('MIGUEL A', 'Miguel', 'Player'),
      ('MIKE', 'Mike', 'Player'),
      ('MIKEY', 'Mikey', 'Player'),
      ('MIN KIM', 'Min', 'Kim'),
      ('NICKY', 'Nicky', 'Player'),
      ('NIZAMA', 'Nizama', 'Player'),
      ('NÚÑEZ', 'Núñez', 'Player'),
      ('OSMIN', 'Osmin', 'Player'),
      ('PABLO', 'Pablo', 'Player'),
      ('PIRLO', 'Pirlo', 'Player'),
      ('RAMÓN', 'Ramón', 'Player'),
      ('ROB', 'Rob', 'Player'),
      ('RODOLFO', 'Rodolfo', 'Player'),
      ('RODRIGO', 'Rodrigo', 'Player'),
      ('RUBÉN', 'Rubén', 'Player'),
      ('RUDY', 'Rudy', 'Player'),
      ('SAUL', 'Saul', 'Player'),
      ('SERGIO', 'Sergio', 'Player'),
      ('URIEL', 'Uriel', 'Player'),
      ('VALENCIA', 'Valencia', 'Player'),
      ('VALVERDE', 'Valverde', 'Player'),
      ('WALTER ACERO', 'Walter', 'Acero')
  ) as seed(import_label, first_name, last_name)
),
player_lookup as (
  select
    player_aliases.import_label,
    p.id as player_id
  from player_aliases
  join public.players p
    on lower(trim(p.first_name)) = lower(trim(player_aliases.first_name))
   and lower(trim(p.last_name)) = lower(trim(player_aliases.last_name))
),
season_row as (
  select id
  from public.seasons
  where lower(trim(name)) = lower('2026 Spring')
),
season_player_seed as (
  select *
  from (
    values
      ('ALEX', 'core'),
      ('ALEXIS', 'core'),
      ('ANDRÉS', 'core'),
      ('ASDRUVAL', 'core'),
      ('CARLOS S', 'core'),
      ('CEVALLOS', 'core'),
      ('CHATO', 'core'),
      ('CHAVITO', 'rotation'),
      ('COTI', 'core'),
      ('CUÑIS', 'core'),
      ('DAVID', 'core'),
      ('EDER', 'core'),
      ('EFRA', 'core'),
      ('EFRAÍN', 'rotation'),
      ('FABIÁN', 'rotation'),
      ('FER', 'core'),
      ('GABO', 'core'),
      ('GERARDO', 'core'),
      ('GUILLE', 'core'),
      ('GUS', 'core'),
      ('GUSTAVO', 'rotation'),
      ('JAVIER', 'core'),
      ('JEFF ARCE', 'core'),
      ('JESÚS', 'core'),
      ('JHONY', 'core'),
      ('JORDAN', 'core'),
      ('JOSEPH M.', 'core'),
      ('JOSÉ BLANCO', 'core'),
      ('JOSÉ SARZA', 'core'),
      ('KARTER', 'core'),
      ('KEVIN', 'rotation'),
      ('LUIS MARROQUIN', 'core'),
      ('LÓPEZ', 'rotation'),
      ('MIGUEL A', 'core'),
      ('MIKE', 'rotation'),
      ('MIKEY', 'core'),
      ('MIN KIM', 'core'),
      ('NICKY', 'core'),
      ('NIZAMA', 'core'),
      ('NÚÑEZ', 'core'),
      ('OSMIN', 'core'),
      ('PABLO', 'core'),
      ('PIRLO', 'core'),
      ('RAMÓN', 'core'),
      ('ROB', 'core'),
      ('RODOLFO', 'core'),
      ('RODRIGO', 'core'),
      ('RUBÉN', 'core'),
      ('RUDY', 'core'),
      ('SAUL', 'core'),
      ('SERGIO', 'core'),
      ('URIEL', 'rotation'),
      ('VALENCIA', 'core'),
      ('VALVERDE', 'core'),
      ('WALTER ACERO', 'core')
  ) as seed(import_label, tier_status)
)
insert into public.season_players (
  season_id,
  player_id,
  tier_status,
  tier_reason,
  movement_note,
  is_eligible
)
select distinct
  season_row.id,
  player_lookup.player_id,
  season_player_seed.tier_status,
  'Seeded from the latest 2026 Spring workbook.',
  'Recalculate after reviewing availability, late cancels, and no-shows.',
  true
from season_row
join season_player_seed
  on true
join player_lookup
  on player_lookup.import_label = season_player_seed.import_label;

commit;

-- Final verification query so Supabase SQL Editor has a safe SELECT result to return.
select
  exists (select 1 from public.seasons where lower(trim(name)) = lower('2026 Spring')) as season_2026_spring_ready,
  exists (
    select 1
    from public.matchdays md
    join public.seasons s on s.id = md.season_id
    where lower(trim(s.name)) = lower('2026 Spring')
  ) as season_2026_spring_matchdays_ready,
  exists (
    select 1
    from public.season_players sp
    join public.seasons s on s.id = sp.season_id
    where lower(trim(s.name)) = lower('2026 Spring')
  ) as season_2026_spring_roster_ready;
