select
  to_regclass('public.players') is not null as players_ready,
  to_regclass('public.seasons') is not null as seasons_ready,
  to_regclass('public.season_players') is not null as season_players_ready,
  to_regclass('public.season_roster_requests') is not null as season_roster_requests_ready,
  to_regclass('public.matchdays') is not null as matchdays_ready,
  to_regclass('public.matchday_matches') is not null as matchday_matches_ready,
  to_regclass('public.matchday_player_stats') is not null as matchday_player_stats_ready,
  to_regclass('public.matchday_suggestions') is not null as matchday_suggestions_ready,
  to_regclass('public.matchday_suggestion_replies') is not null as matchday_suggestion_replies_ready,
  to_regclass('public.matchday_suggestion_likes') is not null as matchday_suggestion_likes_ready,
  to_regclass('public.matchday_assignments') is not null as matchday_assignments_ready,
  to_regclass('public.matchday_team_captains') is not null as matchday_team_captains_ready,
  to_regclass('public.v_season_tier_scores') is not null as v_season_tier_scores_ready,
  to_regclass('public.v_season_tier_transparency') is not null as v_season_tier_transparency_ready,
  to_regclass('public.v_rotation_priority') is not null as v_rotation_priority_ready;
